// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopchda_asyncannotations

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	dtyp "github.com/oiweiwei/go-msrpc/msrpc/dtyp"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
	opchda "github.com/oiweiwei/go-opcda/opc/opchda"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom.GoPackage
	_ = iunknown.GoPackage
	_ = opchda.GoPackage
	_ = dtyp.GoPackage
)

var (
	// import guard
	GoPackage = "opchda"
)

var (
	// IOPCHDA_AsyncAnnotations interface identifier 1f1217b7-dee0-11d2-a5e5-000086339399
	AsyncAnnotationsIID = &dcom.IID{Data1: 0x1f1217b7, Data2: 0xdee0, Data3: 0x11d2, Data4: []byte{0xa5, 0xe5, 0x00, 0x00, 0x86, 0x33, 0x93, 0x99}}
	// Syntax UUID
	AsyncAnnotationsSyntaxUUID = &uuid.UUID{TimeLow: 0x1f1217b7, TimeMid: 0xdee0, TimeHiAndVersion: 0x11d2, ClockSeqHiAndReserved: 0xa5, ClockSeqLow: 0xe5, Node: [6]uint8{0x0, 0x0, 0x86, 0x33, 0x93, 0x99}}
	// Syntax ID
	AsyncAnnotationsSyntaxV0_0 = &dcerpc.SyntaxID{IfUUID: AsyncAnnotationsSyntaxUUID, IfVersionMajor: 0, IfVersionMinor: 0}
)

// IOPCHDA_AsyncAnnotations interface.
type AsyncAnnotationsClient interface {

	// IUnknown retrieval method.
	Unknown() iunknown.UnknownClient

	// QueryCapabilities operation.
	QueryCapabilities(context.Context, *QueryCapabilitiesRequest, ...dcerpc.CallOption) (*QueryCapabilitiesResponse, error)

	// Read operation.
	Read(context.Context, *ReadRequest, ...dcerpc.CallOption) (*ReadResponse, error)

	// Insert operation.
	Insert(context.Context, *InsertRequest, ...dcerpc.CallOption) (*InsertResponse, error)

	// Cancel operation.
	Cancel(context.Context, *CancelRequest, ...dcerpc.CallOption) (*CancelResponse, error)

	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn

	// IPID sets the object interface identifier.
	IPID(context.Context, *dcom.IPID) AsyncAnnotationsClient
}

type xxx_DefaultAsyncAnnotationsClient struct {
	iunknown.UnknownClient
	cc   dcerpc.Conn
	ipid *dcom.IPID
}

func (o *xxx_DefaultAsyncAnnotationsClient) Unknown() iunknown.UnknownClient {
	return o.UnknownClient
}

func (o *xxx_DefaultAsyncAnnotationsClient) QueryCapabilities(ctx context.Context, in *QueryCapabilitiesRequest, opts ...dcerpc.CallOption) (*QueryCapabilitiesResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &QueryCapabilitiesResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultAsyncAnnotationsClient) Read(ctx context.Context, in *ReadRequest, opts ...dcerpc.CallOption) (*ReadResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &ReadResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultAsyncAnnotationsClient) Insert(ctx context.Context, in *InsertRequest, opts ...dcerpc.CallOption) (*InsertResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &InsertResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultAsyncAnnotationsClient) Cancel(ctx context.Context, in *CancelRequest, opts ...dcerpc.CallOption) (*CancelResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &CancelResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultAsyncAnnotationsClient) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultAsyncAnnotationsClient) Conn() dcerpc.Conn {
	return o.cc
}

func (o *xxx_DefaultAsyncAnnotationsClient) IPID(ctx context.Context, ipid *dcom.IPID) AsyncAnnotationsClient {
	if ipid == nil {
		ipid = &dcom.IPID{}
	}
	return &xxx_DefaultAsyncAnnotationsClient{
		UnknownClient: o.UnknownClient.IPID(ctx, ipid),
		cc:            o.cc,
		ipid:          ipid,
	}
}

func NewAsyncAnnotationsClient(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (AsyncAnnotationsClient, error) {
	var err error
	if !dcom.IsSuperclass(opts) {
		cc, err = cc.Bind(ctx, append(opts, dcerpc.WithAbstractSyntax(AsyncAnnotationsSyntaxV0_0))...)
		if err != nil {
			return nil, err
		}
	}
	base, err := iunknown.NewUnknownClient(ctx, cc, append(opts, dcom.Superclass(cc))...)
	if err != nil {
		return nil, err
	}
	ipid, ok := dcom.HasIPID(opts)
	if ok {
		base = base.IPID(ctx, ipid)
	}
	return &xxx_DefaultAsyncAnnotationsClient{
		UnknownClient: base,
		cc:            cc,
		ipid:          ipid,
	}, nil
}

// xxx_QueryCapabilitiesOperation structure represents the QueryCapabilities operation
type xxx_QueryCapabilitiesOperation struct {
	This         *dcom.ORPCThis                `idl:"name:This" json:"this"`
	That         *dcom.ORPCThat                `idl:"name:That" json:"that"`
	Capabilities opchda.AnnotationCapabilities `idl:"name:pCapabilities" json:"capabilities"`
	Return       int32                         `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of QueryCapabilities operation.
func (o *xxx_QueryCapabilitiesOperation) OpNum() int { return 3 }

// OpName returns the operation name of QueryCapabilities operation.
func (o *xxx_QueryCapabilitiesOperation) OpName() string {
	return "/IOPCHDA_AsyncAnnotations/v0/QueryCapabilities"
}

func (o *xxx_QueryCapabilitiesOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_QueryCapabilitiesOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_QueryCapabilitiesOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_QueryCapabilitiesOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_QueryCapabilitiesOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pCapabilities {out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_ANNOTATIONCAPABILITIES}(enum))
	{
		if err := w.WriteEnum(uint16(o.Capabilities)); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_QueryCapabilitiesOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pCapabilities {out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_ANNOTATIONCAPABILITIES}(enum))
	{
		if err := w.ReadEnum((*uint16)(&o.Capabilities)); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// QueryCapabilitiesRequest structure represents the QueryCapabilities operation request
type QueryCapabilitiesRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This *dcom.ORPCThis `idl:"name:This" json:"this"`
}

func (o *QueryCapabilitiesRequest) xxx_ToOp(ctx context.Context, op *xxx_QueryCapabilitiesOperation) *xxx_QueryCapabilitiesOperation {
	if op == nil {
		op = &xxx_QueryCapabilitiesOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	return op
}

func (o *QueryCapabilitiesRequest) xxx_FromOp(ctx context.Context, op *xxx_QueryCapabilitiesOperation) {
	if o == nil {
		return
	}
	o.This = op.This
}
func (o *QueryCapabilitiesRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *QueryCapabilitiesRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_QueryCapabilitiesOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeQueryCapabilitiesRequest build a response structure from the given request structure.
func (o *QueryCapabilitiesRequest) MakeResponse() *QueryCapabilitiesResponse {
	return &QueryCapabilitiesResponse{}
}

// OpNum returns the operation number of QueryCapabilities operation.
func (o *QueryCapabilitiesRequest) OpNum() int { return 3 }

// OpName returns the operation name of QueryCapabilities operation.
func (o *QueryCapabilitiesRequest) OpName() string {
	return "/IOPCHDA_AsyncAnnotations/v0/QueryCapabilities"
}

// QueryCapabilitiesResponse structure represents the QueryCapabilities operation response
type QueryCapabilitiesResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That         *dcom.ORPCThat                `idl:"name:That" json:"that"`
	Capabilities opchda.AnnotationCapabilities `idl:"name:pCapabilities" json:"capabilities"`
	// Return: The QueryCapabilities return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *QueryCapabilitiesResponse) xxx_ToOp(ctx context.Context, op *xxx_QueryCapabilitiesOperation) *xxx_QueryCapabilitiesOperation {
	if op == nil {
		op = &xxx_QueryCapabilitiesOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Capabilities = o.Capabilities
	op.Return = o.Return
	return op
}

func (o *QueryCapabilitiesResponse) xxx_FromOp(ctx context.Context, op *xxx_QueryCapabilitiesOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Capabilities = op.Capabilities
	o.Return = op.Return
}
func (o *QueryCapabilitiesResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *QueryCapabilitiesResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_QueryCapabilitiesOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_ReadOperation structure represents the Read operation
type xxx_ReadOperation struct {
	This          *dcom.ORPCThis `idl:"name:This" json:"this"`
	That          *dcom.ORPCThat `idl:"name:That" json:"that"`
	TransactionID uint32         `idl:"name:dwTransactionID" json:"transaction_id"`
	StartTime     *opchda.Time   `idl:"name:htStartTime" json:"start_time"`
	EndTime       *opchda.Time   `idl:"name:htEndTime" json:"end_time"`
	NumItems      uint32         `idl:"name:dwNumItems" json:"num_items"`
	Server        []uint32       `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
	CancelID      uint32         `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors        []int32        `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	Return        int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of Read operation.
func (o *xxx_ReadOperation) OpNum() int { return 4 }

// OpName returns the operation name of Read operation.
func (o *xxx_ReadOperation) OpName() string { return "/IOPCHDA_AsyncAnnotations/v0/Read" }

func (o *xxx_ReadOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if o.Server != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Server))
	}
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_ReadOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.TransactionID); err != nil {
			return err
		}
	}
	// htStartTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.StartTime != nil {
			if err := o.StartTime.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&opchda.Time{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// htEndTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.EndTime != nil {
			if err := o.EndTime.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&opchda.Time{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Server {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if err := w.WriteData(o.Server[i1]); err != nil {
				return err
			}
		}
		for i1 := len(o.Server); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WriteData(uint32(0)); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_ReadOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.TransactionID); err != nil {
			return err
		}
	}
	// htStartTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.StartTime == nil {
			o.StartTime = &opchda.Time{}
		}
		if err := o.StartTime.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// htEndTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.EndTime == nil {
			o.EndTime = &opchda.Time{}
		}
		if err := o.EndTime.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Server", sizeInfo[0])
		}
		o.Server = make([]uint32, sizeInfo[0])
		for i1 := range o.Server {
			i1 := i1
			if err := w.ReadData(&o.Server[i1]); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_ReadOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_ReadOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// htStartTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.StartTime != nil {
			if err := o.StartTime.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&opchda.Time{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// htEndTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.EndTime != nil {
			if err := o.EndTime.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&opchda.Time{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		if o.Errors != nil || o.NumItems > 0 {
			_ptr_ppErrors := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				dimSize1 := uint64(o.NumItems)
				if err := w.WriteSize(dimSize1); err != nil {
					return err
				}
				sizeInfo := []uint64{
					dimSize1,
				}
				for i1 := range o.Errors {
					i1 := i1
					if uint64(i1) >= sizeInfo[0] {
						break
					}
					if err := w.WriteData(o.Errors[i1]); err != nil {
						return err
					}
				}
				for i1 := len(o.Errors); uint64(i1) < sizeInfo[0]; i1++ {
					if err := w.WriteData(int32(0)); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Errors, _ptr_ppErrors); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_ReadOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// htStartTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.StartTime == nil {
			o.StartTime = &opchda.Time{}
		}
		if err := o.StartTime.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// htEndTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.EndTime == nil {
			o.EndTime = &opchda.Time{}
		}
		if err := o.EndTime.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		_ptr_ppErrors := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			sizeInfo := []uint64{
				0,
			}
			for sz1 := range sizeInfo {
				if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
					return err
				}
			}
			if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
				return fmt.Errorf("buffer overflow for size %d of array o.Errors", sizeInfo[0])
			}
			o.Errors = make([]int32, sizeInfo[0])
			for i1 := range o.Errors {
				i1 := i1
				if err := w.ReadData(&o.Errors[i1]); err != nil {
					return err
				}
			}
			return nil
		})
		_s_ppErrors := func(ptr interface{}) { o.Errors = *ptr.(*[]int32) }
		if err := w.ReadPointer(&o.Errors, _s_ppErrors, _ptr_ppErrors); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// ReadRequest structure represents the Read operation request
type ReadRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This          *dcom.ORPCThis `idl:"name:This" json:"this"`
	TransactionID uint32         `idl:"name:dwTransactionID" json:"transaction_id"`
	StartTime     *opchda.Time   `idl:"name:htStartTime" json:"start_time"`
	EndTime       *opchda.Time   `idl:"name:htEndTime" json:"end_time"`
	NumItems      uint32         `idl:"name:dwNumItems" json:"num_items"`
	Server        []uint32       `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
}

func (o *ReadRequest) xxx_ToOp(ctx context.Context, op *xxx_ReadOperation) *xxx_ReadOperation {
	if op == nil {
		op = &xxx_ReadOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.TransactionID = o.TransactionID
	op.StartTime = o.StartTime
	op.EndTime = o.EndTime
	op.NumItems = o.NumItems
	op.Server = o.Server
	return op
}

func (o *ReadRequest) xxx_FromOp(ctx context.Context, op *xxx_ReadOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.TransactionID = op.TransactionID
	o.StartTime = op.StartTime
	o.EndTime = op.EndTime
	o.NumItems = op.NumItems
	o.Server = op.Server
}
func (o *ReadRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *ReadRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_ReadOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeReadRequest build a response structure from the given request structure.
func (o *ReadRequest) MakeResponse() *ReadResponse {
	if o == nil {
		return &ReadResponse{}
	}
	return &ReadResponse{
		NumItems: o.NumItems,
	}
}

// OpNum returns the operation number of Read operation.
func (o *ReadRequest) OpNum() int { return 4 }

// OpName returns the operation name of Read operation.
func (o *ReadRequest) OpName() string { return "/IOPCHDA_AsyncAnnotations/v0/Read" }

// ReadResponse structure represents the Read operation response
type ReadResponse struct {
	// XXX: dwNumItems is an implicit input depedency for output parameters
	NumItems uint32 `idl:"name:dwNumItems" json:"num_items"`

	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That      *dcom.ORPCThat `idl:"name:That" json:"that"`
	StartTime *opchda.Time   `idl:"name:htStartTime" json:"start_time"`
	EndTime   *opchda.Time   `idl:"name:htEndTime" json:"end_time"`
	CancelID  uint32         `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors    []int32        `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	// Return: The Read return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *ReadResponse) xxx_ToOp(ctx context.Context, op *xxx_ReadOperation) *xxx_ReadOperation {
	if op == nil {
		op = &xxx_ReadOperation{}
	}
	if o == nil {
		return op
	}
	// XXX: implicit input dependencies for output parameters
	if op.NumItems == uint32(0) {
		op.NumItems = o.NumItems
	}

	op.That = o.That
	op.StartTime = o.StartTime
	op.EndTime = o.EndTime
	op.CancelID = o.CancelID
	op.Errors = o.Errors
	op.Return = o.Return
	return op
}

func (o *ReadResponse) xxx_FromOp(ctx context.Context, op *xxx_ReadOperation) {
	if o == nil {
		return
	}
	// XXX: implicit input dependencies for output parameters
	o.NumItems = op.NumItems

	o.That = op.That
	o.StartTime = op.StartTime
	o.EndTime = op.EndTime
	o.CancelID = op.CancelID
	o.Errors = op.Errors
	o.Return = op.Return
}
func (o *ReadResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *ReadResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_ReadOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_InsertOperation structure represents the Insert operation
type xxx_InsertOperation struct {
	This             *dcom.ORPCThis       `idl:"name:This" json:"this"`
	That             *dcom.ORPCThat       `idl:"name:That" json:"that"`
	TransactionID    uint32               `idl:"name:dwTransactionID" json:"transaction_id"`
	NumItems         uint32               `idl:"name:dwNumItems" json:"num_items"`
	Server           []uint32             `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
	Timestamps       []*dtyp.Filetime     `idl:"name:ftTimeStamps;size_is:(dwNumItems)" json:"timestamps"`
	AnnotationValues []*opchda.Annotation `idl:"name:pAnnotationValues;size_is:(dwNumItems)" json:"annotation_values"`
	CancelID         uint32               `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors           []int32              `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	Return           int32                `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of Insert operation.
func (o *xxx_InsertOperation) OpNum() int { return 5 }

// OpName returns the operation name of Insert operation.
func (o *xxx_InsertOperation) OpName() string { return "/IOPCHDA_AsyncAnnotations/v0/Insert" }

func (o *xxx_InsertOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if o.Server != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Server))
	}
	if o.Timestamps != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Timestamps))
	}
	if o.AnnotationValues != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.AnnotationValues))
	}
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_InsertOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.TransactionID); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Server {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if err := w.WriteData(o.Server[i1]); err != nil {
				return err
			}
		}
		for i1 := len(o.Server); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WriteData(uint32(0)); err != nil {
				return err
			}
		}
	}
	// ftTimeStamps {in} (1:{pointer=ref}*(1))(2:{alias=FILETIME}[dim:0,size_is=dwNumItems](struct))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Timestamps {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if o.Timestamps[i1] != nil {
				if err := o.Timestamps[i1].MarshalNDR(ctx, w); err != nil {
					return err
				}
			} else {
				if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
		}
		for i1 := len(o.Timestamps); uint64(i1) < sizeInfo[0]; i1++ {
			if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
	}
	// pAnnotationValues {in} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_ANNOTATION}[dim:0,size_is=dwNumItems](struct))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.AnnotationValues {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if o.AnnotationValues[i1] != nil {
				if err := o.AnnotationValues[i1].MarshalNDR(ctx, w); err != nil {
					return err
				}
			} else {
				if err := (&opchda.Annotation{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
		}
		for i1 := len(o.AnnotationValues); uint64(i1) < sizeInfo[0]; i1++ {
			if err := (&opchda.Annotation{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_InsertOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.TransactionID); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Server", sizeInfo[0])
		}
		o.Server = make([]uint32, sizeInfo[0])
		for i1 := range o.Server {
			i1 := i1
			if err := w.ReadData(&o.Server[i1]); err != nil {
				return err
			}
		}
	}
	// ftTimeStamps {in} (1:{pointer=ref}*(1))(2:{alias=FILETIME}[dim:0,size_is=dwNumItems](struct))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Timestamps", sizeInfo[0])
		}
		o.Timestamps = make([]*dtyp.Filetime, sizeInfo[0])
		for i1 := range o.Timestamps {
			i1 := i1
			if o.Timestamps[i1] == nil {
				o.Timestamps[i1] = &dtyp.Filetime{}
			}
			if err := o.Timestamps[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
	}
	// pAnnotationValues {in} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_ANNOTATION}[dim:0,size_is=dwNumItems](struct))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.AnnotationValues", sizeInfo[0])
		}
		o.AnnotationValues = make([]*opchda.Annotation, sizeInfo[0])
		for i1 := range o.AnnotationValues {
			i1 := i1
			if o.AnnotationValues[i1] == nil {
				o.AnnotationValues[i1] = &opchda.Annotation{}
			}
			if err := o.AnnotationValues[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_InsertOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_InsertOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		if o.Errors != nil || o.NumItems > 0 {
			_ptr_ppErrors := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				dimSize1 := uint64(o.NumItems)
				if err := w.WriteSize(dimSize1); err != nil {
					return err
				}
				sizeInfo := []uint64{
					dimSize1,
				}
				for i1 := range o.Errors {
					i1 := i1
					if uint64(i1) >= sizeInfo[0] {
						break
					}
					if err := w.WriteData(o.Errors[i1]); err != nil {
						return err
					}
				}
				for i1 := len(o.Errors); uint64(i1) < sizeInfo[0]; i1++ {
					if err := w.WriteData(int32(0)); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Errors, _ptr_ppErrors); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_InsertOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		_ptr_ppErrors := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			sizeInfo := []uint64{
				0,
			}
			for sz1 := range sizeInfo {
				if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
					return err
				}
			}
			if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
				return fmt.Errorf("buffer overflow for size %d of array o.Errors", sizeInfo[0])
			}
			o.Errors = make([]int32, sizeInfo[0])
			for i1 := range o.Errors {
				i1 := i1
				if err := w.ReadData(&o.Errors[i1]); err != nil {
					return err
				}
			}
			return nil
		})
		_s_ppErrors := func(ptr interface{}) { o.Errors = *ptr.(*[]int32) }
		if err := w.ReadPointer(&o.Errors, _s_ppErrors, _ptr_ppErrors); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// InsertRequest structure represents the Insert operation request
type InsertRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This             *dcom.ORPCThis       `idl:"name:This" json:"this"`
	TransactionID    uint32               `idl:"name:dwTransactionID" json:"transaction_id"`
	NumItems         uint32               `idl:"name:dwNumItems" json:"num_items"`
	Server           []uint32             `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
	Timestamps       []*dtyp.Filetime     `idl:"name:ftTimeStamps;size_is:(dwNumItems)" json:"timestamps"`
	AnnotationValues []*opchda.Annotation `idl:"name:pAnnotationValues;size_is:(dwNumItems)" json:"annotation_values"`
}

func (o *InsertRequest) xxx_ToOp(ctx context.Context, op *xxx_InsertOperation) *xxx_InsertOperation {
	if op == nil {
		op = &xxx_InsertOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.TransactionID = o.TransactionID
	op.NumItems = o.NumItems
	op.Server = o.Server
	op.Timestamps = o.Timestamps
	op.AnnotationValues = o.AnnotationValues
	return op
}

func (o *InsertRequest) xxx_FromOp(ctx context.Context, op *xxx_InsertOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.TransactionID = op.TransactionID
	o.NumItems = op.NumItems
	o.Server = op.Server
	o.Timestamps = op.Timestamps
	o.AnnotationValues = op.AnnotationValues
}
func (o *InsertRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *InsertRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_InsertOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeInsertRequest build a response structure from the given request structure.
func (o *InsertRequest) MakeResponse() *InsertResponse {
	if o == nil {
		return &InsertResponse{}
	}
	return &InsertResponse{
		NumItems: o.NumItems,
	}
}

// OpNum returns the operation number of Insert operation.
func (o *InsertRequest) OpNum() int { return 5 }

// OpName returns the operation name of Insert operation.
func (o *InsertRequest) OpName() string { return "/IOPCHDA_AsyncAnnotations/v0/Insert" }

// InsertResponse structure represents the Insert operation response
type InsertResponse struct {
	// XXX: dwNumItems is an implicit input depedency for output parameters
	NumItems uint32 `idl:"name:dwNumItems" json:"num_items"`

	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That     *dcom.ORPCThat `idl:"name:That" json:"that"`
	CancelID uint32         `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors   []int32        `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	// Return: The Insert return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *InsertResponse) xxx_ToOp(ctx context.Context, op *xxx_InsertOperation) *xxx_InsertOperation {
	if op == nil {
		op = &xxx_InsertOperation{}
	}
	if o == nil {
		return op
	}
	// XXX: implicit input dependencies for output parameters
	if op.NumItems == uint32(0) {
		op.NumItems = o.NumItems
	}

	op.That = o.That
	op.CancelID = o.CancelID
	op.Errors = o.Errors
	op.Return = o.Return
	return op
}

func (o *InsertResponse) xxx_FromOp(ctx context.Context, op *xxx_InsertOperation) {
	if o == nil {
		return
	}
	// XXX: implicit input dependencies for output parameters
	o.NumItems = op.NumItems

	o.That = op.That
	o.CancelID = op.CancelID
	o.Errors = op.Errors
	o.Return = op.Return
}
func (o *InsertResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *InsertResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_InsertOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_CancelOperation structure represents the Cancel operation
type xxx_CancelOperation struct {
	This     *dcom.ORPCThis `idl:"name:This" json:"this"`
	That     *dcom.ORPCThat `idl:"name:That" json:"that"`
	CancelID uint32         `idl:"name:dwCancelID" json:"cancel_id"`
	Return   int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of Cancel operation.
func (o *xxx_CancelOperation) OpNum() int { return 6 }

// OpName returns the operation name of Cancel operation.
func (o *xxx_CancelOperation) OpName() string { return "/IOPCHDA_AsyncAnnotations/v0/Cancel" }

func (o *xxx_CancelOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CancelOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwCancelID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.CancelID); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CancelOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwCancelID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.CancelID); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CancelOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CancelOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CancelOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// CancelRequest structure represents the Cancel operation request
type CancelRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This     *dcom.ORPCThis `idl:"name:This" json:"this"`
	CancelID uint32         `idl:"name:dwCancelID" json:"cancel_id"`
}

func (o *CancelRequest) xxx_ToOp(ctx context.Context, op *xxx_CancelOperation) *xxx_CancelOperation {
	if op == nil {
		op = &xxx_CancelOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.CancelID = o.CancelID
	return op
}

func (o *CancelRequest) xxx_FromOp(ctx context.Context, op *xxx_CancelOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.CancelID = op.CancelID
}
func (o *CancelRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *CancelRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_CancelOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeCancelRequest build a response structure from the given request structure.
func (o *CancelRequest) MakeResponse() *CancelResponse {
	return &CancelResponse{}
}

// OpNum returns the operation number of Cancel operation.
func (o *CancelRequest) OpNum() int { return 6 }

// OpName returns the operation name of Cancel operation.
func (o *CancelRequest) OpName() string { return "/IOPCHDA_AsyncAnnotations/v0/Cancel" }

// CancelResponse structure represents the Cancel operation response
type CancelResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That *dcom.ORPCThat `idl:"name:That" json:"that"`
	// Return: The Cancel return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *CancelResponse) xxx_ToOp(ctx context.Context, op *xxx_CancelOperation) *xxx_CancelOperation {
	if op == nil {
		op = &xxx_CancelOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Return = o.Return
	return op
}

func (o *CancelResponse) xxx_FromOp(ctx context.Context, op *xxx_CancelOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Return = op.Return
}
func (o *CancelResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *CancelResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_CancelOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}
