// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopceventareabrowser

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	urlmon "github.com/oiweiwei/go-msrpc/msrpc/dcom/urlmon"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
	opcae "github.com/oiweiwei/go-opcda/opc/opcae"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom.GoPackage
	_ = iunknown.GoPackage
	_ = opcae.GoPackage
	_ = urlmon.GoPackage
)

var (
	// import guard
	GoPackage = "opcae"
)

var (
	// IOPCEventAreaBrowser interface identifier 65168857-5783-11d1-84a0-00608cb8a7e9
	EventAreaBrowserIID = &dcom.IID{Data1: 0x65168857, Data2: 0x5783, Data3: 0x11d1, Data4: []byte{0x84, 0xa0, 0x00, 0x60, 0x8c, 0xb8, 0xa7, 0xe9}}
	// Syntax UUID
	EventAreaBrowserSyntaxUUID = &uuid.UUID{TimeLow: 0x65168857, TimeMid: 0x5783, TimeHiAndVersion: 0x11d1, ClockSeqHiAndReserved: 0x84, ClockSeqLow: 0xa0, Node: [6]uint8{0x0, 0x60, 0x8c, 0xb8, 0xa7, 0xe9}}
	// Syntax ID
	EventAreaBrowserSyntaxV0_0 = &dcerpc.SyntaxID{IfUUID: EventAreaBrowserSyntaxUUID, IfVersionMajor: 0, IfVersionMinor: 0}
)

// IOPCEventAreaBrowser interface.
type EventAreaBrowserClient interface {

	// IUnknown retrieval method.
	Unknown() iunknown.UnknownClient

	// ChangeBrowsePosition operation.
	ChangeBrowsePosition(context.Context, *ChangeBrowsePositionRequest, ...dcerpc.CallOption) (*ChangeBrowsePositionResponse, error)

	// BrowseOPCAreas operation.
	BrowseOPCAreas(context.Context, *BrowseOPCAreasRequest, ...dcerpc.CallOption) (*BrowseOPCAreasResponse, error)

	// GetQualifiedAreaName operation.
	GetQualifiedAreaName(context.Context, *GetQualifiedAreaNameRequest, ...dcerpc.CallOption) (*GetQualifiedAreaNameResponse, error)

	// GetQualifiedSourceName operation.
	GetQualifiedSourceName(context.Context, *GetQualifiedSourceNameRequest, ...dcerpc.CallOption) (*GetQualifiedSourceNameResponse, error)

	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn

	// IPID sets the object interface identifier.
	IPID(context.Context, *dcom.IPID) EventAreaBrowserClient
}

type xxx_DefaultEventAreaBrowserClient struct {
	iunknown.UnknownClient
	cc   dcerpc.Conn
	ipid *dcom.IPID
}

func (o *xxx_DefaultEventAreaBrowserClient) Unknown() iunknown.UnknownClient {
	return o.UnknownClient
}

func (o *xxx_DefaultEventAreaBrowserClient) ChangeBrowsePosition(ctx context.Context, in *ChangeBrowsePositionRequest, opts ...dcerpc.CallOption) (*ChangeBrowsePositionResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &ChangeBrowsePositionResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultEventAreaBrowserClient) BrowseOPCAreas(ctx context.Context, in *BrowseOPCAreasRequest, opts ...dcerpc.CallOption) (*BrowseOPCAreasResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &BrowseOPCAreasResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultEventAreaBrowserClient) GetQualifiedAreaName(ctx context.Context, in *GetQualifiedAreaNameRequest, opts ...dcerpc.CallOption) (*GetQualifiedAreaNameResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &GetQualifiedAreaNameResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultEventAreaBrowserClient) GetQualifiedSourceName(ctx context.Context, in *GetQualifiedSourceNameRequest, opts ...dcerpc.CallOption) (*GetQualifiedSourceNameResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &GetQualifiedSourceNameResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultEventAreaBrowserClient) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultEventAreaBrowserClient) Conn() dcerpc.Conn {
	return o.cc
}

func (o *xxx_DefaultEventAreaBrowserClient) IPID(ctx context.Context, ipid *dcom.IPID) EventAreaBrowserClient {
	if ipid == nil {
		ipid = &dcom.IPID{}
	}
	return &xxx_DefaultEventAreaBrowserClient{
		UnknownClient: o.UnknownClient.IPID(ctx, ipid),
		cc:            o.cc,
		ipid:          ipid,
	}
}

func NewEventAreaBrowserClient(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (EventAreaBrowserClient, error) {
	var err error
	if !dcom.IsSuperclass(opts) {
		cc, err = cc.Bind(ctx, append(opts, dcerpc.WithAbstractSyntax(EventAreaBrowserSyntaxV0_0))...)
		if err != nil {
			return nil, err
		}
	}
	base, err := iunknown.NewUnknownClient(ctx, cc, append(opts, dcom.Superclass(cc))...)
	if err != nil {
		return nil, err
	}
	ipid, ok := dcom.HasIPID(opts)
	if ok {
		base = base.IPID(ctx, ipid)
	}
	return &xxx_DefaultEventAreaBrowserClient{
		UnknownClient: base,
		cc:            cc,
		ipid:          ipid,
	}, nil
}

// xxx_ChangeBrowsePositionOperation structure represents the ChangeBrowsePosition operation
type xxx_ChangeBrowsePositionOperation struct {
	This            *dcom.ORPCThis        `idl:"name:This" json:"this"`
	That            *dcom.ORPCThat        `idl:"name:That" json:"that"`
	BrowseDirection opcae.BrowseDirection `idl:"name:dwBrowseDirection" json:"browse_direction"`
	String          string                `idl:"name:szString;string" json:"string"`
	Return          int32                 `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of ChangeBrowsePosition operation.
func (o *xxx_ChangeBrowsePositionOperation) OpNum() int { return 3 }

// OpName returns the operation name of ChangeBrowsePosition operation.
func (o *xxx_ChangeBrowsePositionOperation) OpName() string {
	return "/IOPCEventAreaBrowser/v0/ChangeBrowsePosition"
}

func (o *xxx_ChangeBrowsePositionOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_ChangeBrowsePositionOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwBrowseDirection {in} (1:{alias=OPCAEBROWSEDIRECTION}(enum))
	{
		if err := w.WriteEnum(uint16(o.BrowseDirection)); err != nil {
			return err
		}
	}
	// szString {in} (1:{string, alias=LPCWSTR}*(1)[dim:0,string,null](wchar))
	{
		if err := ndr.WriteUTF16NString(ctx, w, o.String); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_ChangeBrowsePositionOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwBrowseDirection {in} (1:{alias=OPCAEBROWSEDIRECTION}(enum))
	{
		if err := w.ReadEnum((*uint16)(&o.BrowseDirection)); err != nil {
			return err
		}
	}
	// szString {in} (1:{string, alias=LPCWSTR,pointer=ref}*(1)[dim:0,string,null](wchar))
	{
		if err := ndr.ReadUTF16NString(ctx, w, &o.String); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_ChangeBrowsePositionOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_ChangeBrowsePositionOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_ChangeBrowsePositionOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// ChangeBrowsePositionRequest structure represents the ChangeBrowsePosition operation request
type ChangeBrowsePositionRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This            *dcom.ORPCThis        `idl:"name:This" json:"this"`
	BrowseDirection opcae.BrowseDirection `idl:"name:dwBrowseDirection" json:"browse_direction"`
	String          string                `idl:"name:szString;string" json:"string"`
}

func (o *ChangeBrowsePositionRequest) xxx_ToOp(ctx context.Context, op *xxx_ChangeBrowsePositionOperation) *xxx_ChangeBrowsePositionOperation {
	if op == nil {
		op = &xxx_ChangeBrowsePositionOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.BrowseDirection = o.BrowseDirection
	op.String = o.String
	return op
}

func (o *ChangeBrowsePositionRequest) xxx_FromOp(ctx context.Context, op *xxx_ChangeBrowsePositionOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.BrowseDirection = op.BrowseDirection
	o.String = op.String
}
func (o *ChangeBrowsePositionRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *ChangeBrowsePositionRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_ChangeBrowsePositionOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeChangeBrowsePositionRequest build a response structure from the given request structure.
func (o *ChangeBrowsePositionRequest) MakeResponse() *ChangeBrowsePositionResponse {
	return &ChangeBrowsePositionResponse{}
}

// OpNum returns the operation number of ChangeBrowsePosition operation.
func (o *ChangeBrowsePositionRequest) OpNum() int { return 3 }

// OpName returns the operation name of ChangeBrowsePosition operation.
func (o *ChangeBrowsePositionRequest) OpName() string {
	return "/IOPCEventAreaBrowser/v0/ChangeBrowsePosition"
}

// ChangeBrowsePositionResponse structure represents the ChangeBrowsePosition operation response
type ChangeBrowsePositionResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That *dcom.ORPCThat `idl:"name:That" json:"that"`
	// Return: The ChangeBrowsePosition return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *ChangeBrowsePositionResponse) xxx_ToOp(ctx context.Context, op *xxx_ChangeBrowsePositionOperation) *xxx_ChangeBrowsePositionOperation {
	if op == nil {
		op = &xxx_ChangeBrowsePositionOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Return = o.Return
	return op
}

func (o *ChangeBrowsePositionResponse) xxx_FromOp(ctx context.Context, op *xxx_ChangeBrowsePositionOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Return = op.Return
}
func (o *ChangeBrowsePositionResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *ChangeBrowsePositionResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_ChangeBrowsePositionOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_BrowseOPCAreasOperation structure represents the BrowseOPCAreas operation
type xxx_BrowseOPCAreasOperation struct {
	This             *dcom.ORPCThis     `idl:"name:This" json:"this"`
	That             *dcom.ORPCThat     `idl:"name:That" json:"that"`
	BrowseFilterType opcae.BrowseType   `idl:"name:dwBrowseFilterType" json:"browse_filter_type"`
	FilterCriteria   string             `idl:"name:szFilterCriteria;string" json:"filter_criteria"`
	IEnumString      *urlmon.EnumString `idl:"name:ppIEnumString" json:"i_enum_string"`
	Return           int32              `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of BrowseOPCAreas operation.
func (o *xxx_BrowseOPCAreasOperation) OpNum() int { return 4 }

// OpName returns the operation name of BrowseOPCAreas operation.
func (o *xxx_BrowseOPCAreasOperation) OpName() string {
	return "/IOPCEventAreaBrowser/v0/BrowseOPCAreas"
}

func (o *xxx_BrowseOPCAreasOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_BrowseOPCAreasOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwBrowseFilterType {in} (1:{alias=OPCAEBROWSETYPE}(enum))
	{
		if err := w.WriteEnum(uint16(o.BrowseFilterType)); err != nil {
			return err
		}
	}
	// szFilterCriteria {in} (1:{string, alias=LPCWSTR}*(1)[dim:0,string,null](wchar))
	{
		if err := ndr.WriteUTF16NString(ctx, w, o.FilterCriteria); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_BrowseOPCAreasOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwBrowseFilterType {in} (1:{alias=OPCAEBROWSETYPE}(enum))
	{
		if err := w.ReadEnum((*uint16)(&o.BrowseFilterType)); err != nil {
			return err
		}
	}
	// szFilterCriteria {in} (1:{string, alias=LPCWSTR,pointer=ref}*(1)[dim:0,string,null](wchar))
	{
		if err := ndr.ReadUTF16NString(ctx, w, &o.FilterCriteria); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_BrowseOPCAreasOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_BrowseOPCAreasOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// ppIEnumString {out} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=LPENUMSTRING}*(1))(3:{alias=IEnumString}(interface))
	{
		if o.IEnumString != nil {
			_ptr_ppIEnumString := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.IEnumString != nil {
					if err := o.IEnumString.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&urlmon.EnumString{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.IEnumString, _ptr_ppIEnumString); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_BrowseOPCAreasOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// ppIEnumString {out} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=LPENUMSTRING}*(1))(3:{alias=IEnumString}(interface))
	{
		_ptr_ppIEnumString := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.IEnumString == nil {
				o.IEnumString = &urlmon.EnumString{}
			}
			if err := o.IEnumString.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_ppIEnumString := func(ptr interface{}) { o.IEnumString = *ptr.(**urlmon.EnumString) }
		if err := w.ReadPointer(&o.IEnumString, _s_ppIEnumString, _ptr_ppIEnumString); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// BrowseOPCAreasRequest structure represents the BrowseOPCAreas operation request
type BrowseOPCAreasRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This             *dcom.ORPCThis   `idl:"name:This" json:"this"`
	BrowseFilterType opcae.BrowseType `idl:"name:dwBrowseFilterType" json:"browse_filter_type"`
	FilterCriteria   string           `idl:"name:szFilterCriteria;string" json:"filter_criteria"`
}

func (o *BrowseOPCAreasRequest) xxx_ToOp(ctx context.Context, op *xxx_BrowseOPCAreasOperation) *xxx_BrowseOPCAreasOperation {
	if op == nil {
		op = &xxx_BrowseOPCAreasOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.BrowseFilterType = o.BrowseFilterType
	op.FilterCriteria = o.FilterCriteria
	return op
}

func (o *BrowseOPCAreasRequest) xxx_FromOp(ctx context.Context, op *xxx_BrowseOPCAreasOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.BrowseFilterType = op.BrowseFilterType
	o.FilterCriteria = op.FilterCriteria
}
func (o *BrowseOPCAreasRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *BrowseOPCAreasRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_BrowseOPCAreasOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeBrowseOPCAreasRequest build a response structure from the given request structure.
func (o *BrowseOPCAreasRequest) MakeResponse() *BrowseOPCAreasResponse {
	return &BrowseOPCAreasResponse{}
}

// OpNum returns the operation number of BrowseOPCAreas operation.
func (o *BrowseOPCAreasRequest) OpNum() int { return 4 }

// OpName returns the operation name of BrowseOPCAreas operation.
func (o *BrowseOPCAreasRequest) OpName() string { return "/IOPCEventAreaBrowser/v0/BrowseOPCAreas" }

// BrowseOPCAreasResponse structure represents the BrowseOPCAreas operation response
type BrowseOPCAreasResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That        *dcom.ORPCThat     `idl:"name:That" json:"that"`
	IEnumString *urlmon.EnumString `idl:"name:ppIEnumString" json:"i_enum_string"`
	// Return: The BrowseOPCAreas return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *BrowseOPCAreasResponse) xxx_ToOp(ctx context.Context, op *xxx_BrowseOPCAreasOperation) *xxx_BrowseOPCAreasOperation {
	if op == nil {
		op = &xxx_BrowseOPCAreasOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.IEnumString = o.IEnumString
	op.Return = o.Return
	return op
}

func (o *BrowseOPCAreasResponse) xxx_FromOp(ctx context.Context, op *xxx_BrowseOPCAreasOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.IEnumString = op.IEnumString
	o.Return = op.Return
}
func (o *BrowseOPCAreasResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *BrowseOPCAreasResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_BrowseOPCAreasOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_GetQualifiedAreaNameOperation structure represents the GetQualifiedAreaName operation
type xxx_GetQualifiedAreaNameOperation struct {
	This              *dcom.ORPCThis `idl:"name:This" json:"this"`
	That              *dcom.ORPCThat `idl:"name:That" json:"that"`
	AreaName          string         `idl:"name:szAreaName" json:"area_name"`
	QualifiedAreaName string         `idl:"name:pszQualifiedAreaName;string" json:"qualified_area_name"`
	Return            int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of GetQualifiedAreaName operation.
func (o *xxx_GetQualifiedAreaNameOperation) OpNum() int { return 5 }

// OpName returns the operation name of GetQualifiedAreaName operation.
func (o *xxx_GetQualifiedAreaNameOperation) OpName() string {
	return "/IOPCEventAreaBrowser/v0/GetQualifiedAreaName"
}

func (o *xxx_GetQualifiedAreaNameOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetQualifiedAreaNameOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// szAreaName {in} (1:{alias=LPCWSTR}*(1)[dim:0,string](wchar))
	{
		if err := ndr.WriteUTF16String(ctx, w, o.AreaName); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetQualifiedAreaNameOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// szAreaName {in} (1:{alias=LPCWSTR,pointer=ref}*(1)[dim:0,string](wchar))
	{
		if err := ndr.ReadUTF16String(ctx, w, &o.AreaName); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetQualifiedAreaNameOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetQualifiedAreaNameOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pszQualifiedAreaName {out} (1:{string, pointer=ref}*(2))(2:{alias=LPWSTR}*(1)[dim:0,string,null](wchar))
	{
		if o.QualifiedAreaName != "" {
			_ptr_pszQualifiedAreaName := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if err := ndr.WriteUTF16NString(ctx, w, o.QualifiedAreaName); err != nil {
					return err
				}
				return nil
			})
			if err := w.WritePointer(&o.QualifiedAreaName, _ptr_pszQualifiedAreaName); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetQualifiedAreaNameOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pszQualifiedAreaName {out} (1:{string, pointer=ref}*(2))(2:{alias=LPWSTR,pointer=ref}*(1)[dim:0,string,null](wchar))
	{
		_ptr_pszQualifiedAreaName := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if err := ndr.ReadUTF16NString(ctx, w, &o.QualifiedAreaName); err != nil {
				return err
			}
			return nil
		})
		_s_pszQualifiedAreaName := func(ptr interface{}) { o.QualifiedAreaName = *ptr.(*string) }
		if err := w.ReadPointer(&o.QualifiedAreaName, _s_pszQualifiedAreaName, _ptr_pszQualifiedAreaName); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// GetQualifiedAreaNameRequest structure represents the GetQualifiedAreaName operation request
type GetQualifiedAreaNameRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This     *dcom.ORPCThis `idl:"name:This" json:"this"`
	AreaName string         `idl:"name:szAreaName" json:"area_name"`
}

func (o *GetQualifiedAreaNameRequest) xxx_ToOp(ctx context.Context, op *xxx_GetQualifiedAreaNameOperation) *xxx_GetQualifiedAreaNameOperation {
	if op == nil {
		op = &xxx_GetQualifiedAreaNameOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.AreaName = o.AreaName
	return op
}

func (o *GetQualifiedAreaNameRequest) xxx_FromOp(ctx context.Context, op *xxx_GetQualifiedAreaNameOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.AreaName = op.AreaName
}
func (o *GetQualifiedAreaNameRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *GetQualifiedAreaNameRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GetQualifiedAreaNameOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeGetQualifiedAreaNameRequest build a response structure from the given request structure.
func (o *GetQualifiedAreaNameRequest) MakeResponse() *GetQualifiedAreaNameResponse {
	return &GetQualifiedAreaNameResponse{}
}

// OpNum returns the operation number of GetQualifiedAreaName operation.
func (o *GetQualifiedAreaNameRequest) OpNum() int { return 5 }

// OpName returns the operation name of GetQualifiedAreaName operation.
func (o *GetQualifiedAreaNameRequest) OpName() string {
	return "/IOPCEventAreaBrowser/v0/GetQualifiedAreaName"
}

// GetQualifiedAreaNameResponse structure represents the GetQualifiedAreaName operation response
type GetQualifiedAreaNameResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That              *dcom.ORPCThat `idl:"name:That" json:"that"`
	QualifiedAreaName string         `idl:"name:pszQualifiedAreaName;string" json:"qualified_area_name"`
	// Return: The GetQualifiedAreaName return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *GetQualifiedAreaNameResponse) xxx_ToOp(ctx context.Context, op *xxx_GetQualifiedAreaNameOperation) *xxx_GetQualifiedAreaNameOperation {
	if op == nil {
		op = &xxx_GetQualifiedAreaNameOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.QualifiedAreaName = o.QualifiedAreaName
	op.Return = o.Return
	return op
}

func (o *GetQualifiedAreaNameResponse) xxx_FromOp(ctx context.Context, op *xxx_GetQualifiedAreaNameOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.QualifiedAreaName = op.QualifiedAreaName
	o.Return = op.Return
}
func (o *GetQualifiedAreaNameResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *GetQualifiedAreaNameResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GetQualifiedAreaNameOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_GetQualifiedSourceNameOperation structure represents the GetQualifiedSourceName operation
type xxx_GetQualifiedSourceNameOperation struct {
	This                *dcom.ORPCThis `idl:"name:This" json:"this"`
	That                *dcom.ORPCThat `idl:"name:That" json:"that"`
	SourceName          string         `idl:"name:szSourceName" json:"source_name"`
	QualifiedSourceName string         `idl:"name:pszQualifiedSourceName;string" json:"qualified_source_name"`
	Return              int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of GetQualifiedSourceName operation.
func (o *xxx_GetQualifiedSourceNameOperation) OpNum() int { return 6 }

// OpName returns the operation name of GetQualifiedSourceName operation.
func (o *xxx_GetQualifiedSourceNameOperation) OpName() string {
	return "/IOPCEventAreaBrowser/v0/GetQualifiedSourceName"
}

func (o *xxx_GetQualifiedSourceNameOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetQualifiedSourceNameOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// szSourceName {in} (1:{alias=LPCWSTR}*(1)[dim:0,string](wchar))
	{
		if err := ndr.WriteUTF16String(ctx, w, o.SourceName); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetQualifiedSourceNameOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// szSourceName {in} (1:{alias=LPCWSTR,pointer=ref}*(1)[dim:0,string](wchar))
	{
		if err := ndr.ReadUTF16String(ctx, w, &o.SourceName); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetQualifiedSourceNameOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetQualifiedSourceNameOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pszQualifiedSourceName {out} (1:{string, pointer=ref}*(2))(2:{alias=LPWSTR}*(1)[dim:0,string,null](wchar))
	{
		if o.QualifiedSourceName != "" {
			_ptr_pszQualifiedSourceName := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if err := ndr.WriteUTF16NString(ctx, w, o.QualifiedSourceName); err != nil {
					return err
				}
				return nil
			})
			if err := w.WritePointer(&o.QualifiedSourceName, _ptr_pszQualifiedSourceName); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetQualifiedSourceNameOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pszQualifiedSourceName {out} (1:{string, pointer=ref}*(2))(2:{alias=LPWSTR,pointer=ref}*(1)[dim:0,string,null](wchar))
	{
		_ptr_pszQualifiedSourceName := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if err := ndr.ReadUTF16NString(ctx, w, &o.QualifiedSourceName); err != nil {
				return err
			}
			return nil
		})
		_s_pszQualifiedSourceName := func(ptr interface{}) { o.QualifiedSourceName = *ptr.(*string) }
		if err := w.ReadPointer(&o.QualifiedSourceName, _s_pszQualifiedSourceName, _ptr_pszQualifiedSourceName); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// GetQualifiedSourceNameRequest structure represents the GetQualifiedSourceName operation request
type GetQualifiedSourceNameRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This       *dcom.ORPCThis `idl:"name:This" json:"this"`
	SourceName string         `idl:"name:szSourceName" json:"source_name"`
}

func (o *GetQualifiedSourceNameRequest) xxx_ToOp(ctx context.Context, op *xxx_GetQualifiedSourceNameOperation) *xxx_GetQualifiedSourceNameOperation {
	if op == nil {
		op = &xxx_GetQualifiedSourceNameOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.SourceName = o.SourceName
	return op
}

func (o *GetQualifiedSourceNameRequest) xxx_FromOp(ctx context.Context, op *xxx_GetQualifiedSourceNameOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.SourceName = op.SourceName
}
func (o *GetQualifiedSourceNameRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *GetQualifiedSourceNameRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GetQualifiedSourceNameOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeGetQualifiedSourceNameRequest build a response structure from the given request structure.
func (o *GetQualifiedSourceNameRequest) MakeResponse() *GetQualifiedSourceNameResponse {
	return &GetQualifiedSourceNameResponse{}
}

// OpNum returns the operation number of GetQualifiedSourceName operation.
func (o *GetQualifiedSourceNameRequest) OpNum() int { return 6 }

// OpName returns the operation name of GetQualifiedSourceName operation.
func (o *GetQualifiedSourceNameRequest) OpName() string {
	return "/IOPCEventAreaBrowser/v0/GetQualifiedSourceName"
}

// GetQualifiedSourceNameResponse structure represents the GetQualifiedSourceName operation response
type GetQualifiedSourceNameResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That                *dcom.ORPCThat `idl:"name:That" json:"that"`
	QualifiedSourceName string         `idl:"name:pszQualifiedSourceName;string" json:"qualified_source_name"`
	// Return: The GetQualifiedSourceName return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *GetQualifiedSourceNameResponse) xxx_ToOp(ctx context.Context, op *xxx_GetQualifiedSourceNameOperation) *xxx_GetQualifiedSourceNameOperation {
	if op == nil {
		op = &xxx_GetQualifiedSourceNameOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.QualifiedSourceName = o.QualifiedSourceName
	op.Return = o.Return
	return op
}

func (o *GetQualifiedSourceNameResponse) xxx_FromOp(ctx context.Context, op *xxx_GetQualifiedSourceNameOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.QualifiedSourceName = op.QualifiedSourceName
	o.Return = op.Return
}
func (o *GetQualifiedSourceNameResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *GetQualifiedSourceNameResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GetQualifiedSourceNameOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}
