// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopcbrowseserveraddressspace

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = iunknown.GoPackage
)

// IOPCBrowseServerAddressSpace server interface.
type BrowseServerAddressSpaceServer interface {

	// IUnknown base class.
	iunknown.UnknownServer

	// QueryOrganization operation.
	QueryOrganization(context.Context, *QueryOrganizationRequest) (*QueryOrganizationResponse, error)

	// ChangeBrowsePosition operation.
	ChangeBrowsePosition(context.Context, *ChangeBrowsePositionRequest) (*ChangeBrowsePositionResponse, error)

	// BrowseOPCItemIDs operation.
	BrowseOPCItemIDs(context.Context, *BrowseOPCItemIDsRequest) (*BrowseOPCItemIDsResponse, error)

	// GetItemID operation.
	GetItemID(context.Context, *GetItemIDRequest) (*GetItemIDResponse, error)

	// BrowseAccessPaths operation.
	BrowseAccessPaths(context.Context, *BrowseAccessPathsRequest) (*BrowseAccessPathsResponse, error)
}

func RegisterBrowseServerAddressSpaceServer(conn dcerpc.Conn, o BrowseServerAddressSpaceServer, opts ...dcerpc.Option) {
	conn.RegisterServer(NewBrowseServerAddressSpaceServerHandle(o), append(opts, dcerpc.WithAbstractSyntax(BrowseServerAddressSpaceSyntaxV0_0))...)
}

func NewBrowseServerAddressSpaceServerHandle(o BrowseServerAddressSpaceServer) dcerpc.ServerHandle {
	return func(ctx context.Context, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
		return BrowseServerAddressSpaceServerHandle(ctx, o, opNum, r)
	}
}

func BrowseServerAddressSpaceServerHandle(ctx context.Context, o BrowseServerAddressSpaceServer, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
	if opNum < 3 {
		// IUnknown base method.
		return iunknown.UnknownServerHandle(ctx, o, opNum, r)
	}
	switch opNum {
	case 3: // QueryOrganization
		op := &xxx_QueryOrganizationOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &QueryOrganizationRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.QueryOrganization(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 4: // ChangeBrowsePosition
		op := &xxx_ChangeBrowsePositionOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &ChangeBrowsePositionRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.ChangeBrowsePosition(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 5: // BrowseOPCItemIDs
		op := &xxx_BrowseOPCItemIDsOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &BrowseOPCItemIDsRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.BrowseOPCItemIDs(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 6: // GetItemID
		op := &xxx_GetItemIDOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &GetItemIDRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.GetItemID(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 7: // BrowseAccessPaths
		op := &xxx_BrowseAccessPathsOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &BrowseAccessPathsRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.BrowseAccessPaths(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	}
	return nil, nil
}

// Unimplemented IOPCBrowseServerAddressSpace
type UnimplementedBrowseServerAddressSpaceServer struct {
	iunknown.UnimplementedUnknownServer
}

func (UnimplementedBrowseServerAddressSpaceServer) QueryOrganization(context.Context, *QueryOrganizationRequest) (*QueryOrganizationResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedBrowseServerAddressSpaceServer) ChangeBrowsePosition(context.Context, *ChangeBrowsePositionRequest) (*ChangeBrowsePositionResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedBrowseServerAddressSpaceServer) BrowseOPCItemIDs(context.Context, *BrowseOPCItemIDsRequest) (*BrowseOPCItemIDsResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedBrowseServerAddressSpaceServer) GetItemID(context.Context, *GetItemIDRequest) (*GetItemIDResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedBrowseServerAddressSpaceServer) BrowseAccessPaths(context.Context, *BrowseAccessPathsRequest) (*BrowseAccessPathsResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}

var _ BrowseServerAddressSpaceServer = (*UnimplementedBrowseServerAddressSpaceServer)(nil)
