// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopcasyncio2

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = iunknown.GoPackage
)

// IOPCAsyncIO2 server interface.
type AsyncIO2Server interface {

	// IUnknown base class.
	iunknown.UnknownServer

	// Read operation.
	Read(context.Context, *ReadRequest) (*ReadResponse, error)

	// Write operation.
	Write(context.Context, *WriteRequest) (*WriteResponse, error)

	// Refresh2 operation.
	Refresh2(context.Context, *Refresh2Request) (*Refresh2Response, error)

	// Cancel2 operation.
	Cancel2(context.Context, *Cancel2Request) (*Cancel2Response, error)

	// SetEnable operation.
	SetEnable(context.Context, *SetEnableRequest) (*SetEnableResponse, error)

	// GetEnable operation.
	GetEnable(context.Context, *GetEnableRequest) (*GetEnableResponse, error)
}

func RegisterAsyncIO2Server(conn dcerpc.Conn, o AsyncIO2Server, opts ...dcerpc.Option) {
	conn.RegisterServer(NewAsyncIO2ServerHandle(o), append(opts, dcerpc.WithAbstractSyntax(AsyncIO2SyntaxV0_0))...)
}

func NewAsyncIO2ServerHandle(o AsyncIO2Server) dcerpc.ServerHandle {
	return func(ctx context.Context, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
		return AsyncIO2ServerHandle(ctx, o, opNum, r)
	}
}

func AsyncIO2ServerHandle(ctx context.Context, o AsyncIO2Server, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
	if opNum < 3 {
		// IUnknown base method.
		return iunknown.UnknownServerHandle(ctx, o, opNum, r)
	}
	switch opNum {
	case 3: // Read
		op := &xxx_ReadOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &ReadRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.Read(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 4: // Write
		op := &xxx_WriteOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &WriteRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.Write(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 5: // Refresh2
		op := &xxx_Refresh2Operation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &Refresh2Request{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.Refresh2(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 6: // Cancel2
		op := &xxx_Cancel2Operation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &Cancel2Request{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.Cancel2(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 7: // SetEnable
		op := &xxx_SetEnableOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &SetEnableRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.SetEnable(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 8: // GetEnable
		op := &xxx_GetEnableOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &GetEnableRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.GetEnable(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	}
	return nil, nil
}

// Unimplemented IOPCAsyncIO2
type UnimplementedAsyncIO2Server struct {
	iunknown.UnimplementedUnknownServer
}

func (UnimplementedAsyncIO2Server) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedAsyncIO2Server) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedAsyncIO2Server) Refresh2(context.Context, *Refresh2Request) (*Refresh2Response, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedAsyncIO2Server) Cancel2(context.Context, *Cancel2Request) (*Cancel2Response, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedAsyncIO2Server) SetEnable(context.Context, *SetEnableRequest) (*SetEnableResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedAsyncIO2Server) GetEnable(context.Context, *GetEnableRequest) (*GetEnableResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}

var _ AsyncIO2Server = (*UnimplementedAsyncIO2Server)(nil)
