// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopchda_datacallback

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = iunknown.GoPackage
)

// IOPCHDA_DataCallback server interface.
type DataCallbackServer interface {

	// IUnknown base class.
	iunknown.UnknownServer

	// OnDataChange operation.
	OnDataChange(context.Context, *OnDataChangeRequest) (*OnDataChangeResponse, error)

	// OnReadComplete operation.
	OnReadComplete(context.Context, *OnReadCompleteRequest) (*OnReadCompleteResponse, error)

	// OnReadModifiedComplete operation.
	OnReadModifiedComplete(context.Context, *OnReadModifiedCompleteRequest) (*OnReadModifiedCompleteResponse, error)

	// OnReadAttributeComplete operation.
	OnReadAttributeComplete(context.Context, *OnReadAttributeCompleteRequest) (*OnReadAttributeCompleteResponse, error)

	// OnReadAnnotations operation.
	OnReadAnnotations(context.Context, *OnReadAnnotationsRequest) (*OnReadAnnotationsResponse, error)

	// OnInsertAnnotations operation.
	OnInsertAnnotations(context.Context, *OnInsertAnnotationsRequest) (*OnInsertAnnotationsResponse, error)

	// OnPlayback operation.
	OnPlayback(context.Context, *OnPlaybackRequest) (*OnPlaybackResponse, error)

	// OnUpdateComplete operation.
	OnUpdateComplete(context.Context, *OnUpdateCompleteRequest) (*OnUpdateCompleteResponse, error)

	// OnCancelComplete operation.
	OnCancelComplete(context.Context, *OnCancelCompleteRequest) (*OnCancelCompleteResponse, error)
}

func RegisterDataCallbackServer(conn dcerpc.Conn, o DataCallbackServer, opts ...dcerpc.Option) {
	conn.RegisterServer(NewDataCallbackServerHandle(o), append(opts, dcerpc.WithAbstractSyntax(DataCallbackSyntaxV0_0))...)
}

func NewDataCallbackServerHandle(o DataCallbackServer) dcerpc.ServerHandle {
	return func(ctx context.Context, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
		return DataCallbackServerHandle(ctx, o, opNum, r)
	}
}

func DataCallbackServerHandle(ctx context.Context, o DataCallbackServer, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
	if opNum < 3 {
		// IUnknown base method.
		return iunknown.UnknownServerHandle(ctx, o, opNum, r)
	}
	switch opNum {
	case 3: // OnDataChange
		op := &xxx_OnDataChangeOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &OnDataChangeRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.OnDataChange(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 4: // OnReadComplete
		op := &xxx_OnReadCompleteOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &OnReadCompleteRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.OnReadComplete(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 5: // OnReadModifiedComplete
		op := &xxx_OnReadModifiedCompleteOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &OnReadModifiedCompleteRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.OnReadModifiedComplete(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 6: // OnReadAttributeComplete
		op := &xxx_OnReadAttributeCompleteOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &OnReadAttributeCompleteRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.OnReadAttributeComplete(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 7: // OnReadAnnotations
		op := &xxx_OnReadAnnotationsOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &OnReadAnnotationsRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.OnReadAnnotations(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 8: // OnInsertAnnotations
		op := &xxx_OnInsertAnnotationsOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &OnInsertAnnotationsRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.OnInsertAnnotations(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 9: // OnPlayback
		op := &xxx_OnPlaybackOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &OnPlaybackRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.OnPlayback(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 10: // OnUpdateComplete
		op := &xxx_OnUpdateCompleteOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &OnUpdateCompleteRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.OnUpdateComplete(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 11: // OnCancelComplete
		op := &xxx_OnCancelCompleteOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &OnCancelCompleteRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.OnCancelComplete(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	}
	return nil, nil
}

// Unimplemented IOPCHDA_DataCallback
type UnimplementedDataCallbackServer struct {
	iunknown.UnimplementedUnknownServer
}

func (UnimplementedDataCallbackServer) OnDataChange(context.Context, *OnDataChangeRequest) (*OnDataChangeResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedDataCallbackServer) OnReadComplete(context.Context, *OnReadCompleteRequest) (*OnReadCompleteResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedDataCallbackServer) OnReadModifiedComplete(context.Context, *OnReadModifiedCompleteRequest) (*OnReadModifiedCompleteResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedDataCallbackServer) OnReadAttributeComplete(context.Context, *OnReadAttributeCompleteRequest) (*OnReadAttributeCompleteResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedDataCallbackServer) OnReadAnnotations(context.Context, *OnReadAnnotationsRequest) (*OnReadAnnotationsResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedDataCallbackServer) OnInsertAnnotations(context.Context, *OnInsertAnnotationsRequest) (*OnInsertAnnotationsResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedDataCallbackServer) OnPlayback(context.Context, *OnPlaybackRequest) (*OnPlaybackResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedDataCallbackServer) OnUpdateComplete(context.Context, *OnUpdateCompleteRequest) (*OnUpdateCompleteResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedDataCallbackServer) OnCancelComplete(context.Context, *OnCancelCompleteRequest) (*OnCancelCompleteResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}

var _ DataCallbackServer = (*UnimplementedDataCallbackServer)(nil)
