// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopchda_server

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = iunknown.GoPackage
)

// IOPCHDA_Server server interface.
type ServerServer interface {

	// IUnknown base class.
	iunknown.UnknownServer

	// GetItemAttributes operation.
	GetItemAttributes(context.Context, *GetItemAttributesRequest) (*GetItemAttributesResponse, error)

	// GetAggregates operation.
	GetAggregates(context.Context, *GetAggregatesRequest) (*GetAggregatesResponse, error)

	// GetHistorianStatus operation.
	GetHistorianStatus(context.Context, *GetHistorianStatusRequest) (*GetHistorianStatusResponse, error)

	// GetItemHandles operation.
	GetItemHandles(context.Context, *GetItemHandlesRequest) (*GetItemHandlesResponse, error)

	// ReleaseItemHandles operation.
	ReleaseItemHandles(context.Context, *ReleaseItemHandlesRequest) (*ReleaseItemHandlesResponse, error)

	// ValidateItemIDs operation.
	ValidateItemIDs(context.Context, *ValidateItemIDsRequest) (*ValidateItemIDsResponse, error)

	// CreateBrowse operation.
	CreateBrowse(context.Context, *CreateBrowseRequest) (*CreateBrowseResponse, error)
}

func RegisterServerServer(conn dcerpc.Conn, o ServerServer, opts ...dcerpc.Option) {
	conn.RegisterServer(NewServerServerHandle(o), append(opts, dcerpc.WithAbstractSyntax(ServerSyntaxV0_0))...)
}

func NewServerServerHandle(o ServerServer) dcerpc.ServerHandle {
	return func(ctx context.Context, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
		return ServerServerHandle(ctx, o, opNum, r)
	}
}

func ServerServerHandle(ctx context.Context, o ServerServer, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
	if opNum < 3 {
		// IUnknown base method.
		return iunknown.UnknownServerHandle(ctx, o, opNum, r)
	}
	switch opNum {
	case 3: // GetItemAttributes
		op := &xxx_GetItemAttributesOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &GetItemAttributesRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.GetItemAttributes(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 4: // GetAggregates
		op := &xxx_GetAggregatesOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &GetAggregatesRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.GetAggregates(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 5: // GetHistorianStatus
		op := &xxx_GetHistorianStatusOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &GetHistorianStatusRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.GetHistorianStatus(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 6: // GetItemHandles
		op := &xxx_GetItemHandlesOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &GetItemHandlesRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.GetItemHandles(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 7: // ReleaseItemHandles
		op := &xxx_ReleaseItemHandlesOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &ReleaseItemHandlesRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.ReleaseItemHandles(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 8: // ValidateItemIDs
		op := &xxx_ValidateItemIDsOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &ValidateItemIDsRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.ValidateItemIDs(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 9: // CreateBrowse
		op := &xxx_CreateBrowseOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &CreateBrowseRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.CreateBrowse(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	}
	return nil, nil
}

// Unimplemented IOPCHDA_Server
type UnimplementedServerServer struct {
	iunknown.UnimplementedUnknownServer
}

func (UnimplementedServerServer) GetItemAttributes(context.Context, *GetItemAttributesRequest) (*GetItemAttributesResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedServerServer) GetAggregates(context.Context, *GetAggregatesRequest) (*GetAggregatesResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedServerServer) GetHistorianStatus(context.Context, *GetHistorianStatusRequest) (*GetHistorianStatusResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedServerServer) GetItemHandles(context.Context, *GetItemHandlesRequest) (*GetItemHandlesResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedServerServer) ReleaseItemHandles(context.Context, *ReleaseItemHandlesRequest) (*ReleaseItemHandlesResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedServerServer) ValidateItemIDs(context.Context, *ValidateItemIDsRequest) (*ValidateItemIDsResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedServerServer) CreateBrowse(context.Context, *CreateBrowseRequest) (*CreateBrowseResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}

var _ ServerServer = (*UnimplementedServerServer)(nil)
