// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopcserverpublicgroups

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom.GoPackage
	_ = iunknown.GoPackage
)

var (
	// import guard
	GoPackage = "opcda"
)

var (
	// IOPCServerPublicGroups interface identifier 39c13a4e-011e-11d0-9675-0020afd8adb3
	ServerPublicGroupsIID = &dcom.IID{Data1: 0x39c13a4e, Data2: 0x011e, Data3: 0x11d0, Data4: []byte{0x96, 0x75, 0x00, 0x20, 0xaf, 0xd8, 0xad, 0xb3}}
	// Syntax UUID
	ServerPublicGroupsSyntaxUUID = &uuid.UUID{TimeLow: 0x39c13a4e, TimeMid: 0x11e, TimeHiAndVersion: 0x11d0, ClockSeqHiAndReserved: 0x96, ClockSeqLow: 0x75, Node: [6]uint8{0x0, 0x20, 0xaf, 0xd8, 0xad, 0xb3}}
	// Syntax ID
	ServerPublicGroupsSyntaxV0_0 = &dcerpc.SyntaxID{IfUUID: ServerPublicGroupsSyntaxUUID, IfVersionMajor: 0, IfVersionMinor: 0}
)

// IOPCServerPublicGroups interface.
type ServerPublicGroupsClient interface {

	// IUnknown retrieval method.
	Unknown() iunknown.UnknownClient

	// GetPublicGroupByName operation.
	GetPublicGroupByName(context.Context, *GetPublicGroupByNameRequest, ...dcerpc.CallOption) (*GetPublicGroupByNameResponse, error)

	// RemovePublicGroup operation.
	RemovePublicGroup(context.Context, *RemovePublicGroupRequest, ...dcerpc.CallOption) (*RemovePublicGroupResponse, error)

	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn

	// IPID sets the object interface identifier.
	IPID(context.Context, *dcom.IPID) ServerPublicGroupsClient
}

type xxx_DefaultServerPublicGroupsClient struct {
	iunknown.UnknownClient
	cc   dcerpc.Conn
	ipid *dcom.IPID
}

func (o *xxx_DefaultServerPublicGroupsClient) Unknown() iunknown.UnknownClient {
	return o.UnknownClient
}

func (o *xxx_DefaultServerPublicGroupsClient) GetPublicGroupByName(ctx context.Context, in *GetPublicGroupByNameRequest, opts ...dcerpc.CallOption) (*GetPublicGroupByNameResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &GetPublicGroupByNameResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultServerPublicGroupsClient) RemovePublicGroup(ctx context.Context, in *RemovePublicGroupRequest, opts ...dcerpc.CallOption) (*RemovePublicGroupResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &RemovePublicGroupResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultServerPublicGroupsClient) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultServerPublicGroupsClient) Conn() dcerpc.Conn {
	return o.cc
}

func (o *xxx_DefaultServerPublicGroupsClient) IPID(ctx context.Context, ipid *dcom.IPID) ServerPublicGroupsClient {
	if ipid == nil {
		ipid = &dcom.IPID{}
	}
	return &xxx_DefaultServerPublicGroupsClient{
		UnknownClient: o.UnknownClient.IPID(ctx, ipid),
		cc:            o.cc,
		ipid:          ipid,
	}
}

func NewServerPublicGroupsClient(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (ServerPublicGroupsClient, error) {
	var err error
	if !dcom.IsSuperclass(opts) {
		cc, err = cc.Bind(ctx, append(opts, dcerpc.WithAbstractSyntax(ServerPublicGroupsSyntaxV0_0))...)
		if err != nil {
			return nil, err
		}
	}
	base, err := iunknown.NewUnknownClient(ctx, cc, append(opts, dcom.Superclass(cc))...)
	if err != nil {
		return nil, err
	}
	ipid, ok := dcom.HasIPID(opts)
	if ok {
		base = base.IPID(ctx, ipid)
	}
	return &xxx_DefaultServerPublicGroupsClient{
		UnknownClient: base,
		cc:            cc,
		ipid:          ipid,
	}, nil
}

// xxx_GetPublicGroupByNameOperation structure represents the GetPublicGroupByName operation
type xxx_GetPublicGroupByNameOperation struct {
	This    *dcom.ORPCThis `idl:"name:This" json:"this"`
	That    *dcom.ORPCThat `idl:"name:That" json:"that"`
	Name    string         `idl:"name:szName;string" json:"name"`
	RIID    *dcom.IID      `idl:"name:riid" json:"riid"`
	Unknown *dcom.Unknown  `idl:"name:ppUnk" json:"unknown"`
	Return  int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of GetPublicGroupByName operation.
func (o *xxx_GetPublicGroupByNameOperation) OpNum() int { return 3 }

// OpName returns the operation name of GetPublicGroupByName operation.
func (o *xxx_GetPublicGroupByNameOperation) OpName() string {
	return "/IOPCServerPublicGroups/v0/GetPublicGroupByName"
}

func (o *xxx_GetPublicGroupByNameOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetPublicGroupByNameOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// szName {in} (1:{string, alias=LPCWSTR}*(1)[dim:0,string,null](wchar))
	{
		if err := ndr.WriteUTF16NString(ctx, w, o.Name); err != nil {
			return err
		}
	}
	// riid {in} (1:{alias=REFIID}*(1))(2:{alias=IID, names=GUID}(struct))
	{
		if o.RIID != nil {
			if err := o.RIID.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.IID{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_GetPublicGroupByNameOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// szName {in} (1:{string, alias=LPCWSTR,pointer=ref}*(1)[dim:0,string,null](wchar))
	{
		if err := ndr.ReadUTF16NString(ctx, w, &o.Name); err != nil {
			return err
		}
	}
	// riid {in} (1:{alias=REFIID,pointer=ref}*(1))(2:{alias=IID, names=GUID}(struct))
	{
		if o.RIID == nil {
			o.RIID = &dcom.IID{}
		}
		if err := o.RIID.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetPublicGroupByNameOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetPublicGroupByNameOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// ppUnk {out, iid_is={riid}} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=LPUNKNOWN}*(1))(3:{alias=IUnknown}(interface))
	{
		if o.Unknown != nil {
			_ptr_ppUnk := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.Unknown != nil {
					if err := o.Unknown.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&dcom.Unknown{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Unknown, _ptr_ppUnk); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetPublicGroupByNameOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// ppUnk {out, iid_is={riid}} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=LPUNKNOWN}*(1))(3:{alias=IUnknown}(interface))
	{
		_ptr_ppUnk := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.Unknown == nil {
				o.Unknown = &dcom.Unknown{}
			}
			if err := o.Unknown.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_ppUnk := func(ptr interface{}) { o.Unknown = *ptr.(**dcom.Unknown) }
		if err := w.ReadPointer(&o.Unknown, _s_ppUnk, _ptr_ppUnk); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// GetPublicGroupByNameRequest structure represents the GetPublicGroupByName operation request
type GetPublicGroupByNameRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This *dcom.ORPCThis `idl:"name:This" json:"this"`
	Name string         `idl:"name:szName;string" json:"name"`
	RIID *dcom.IID      `idl:"name:riid" json:"riid"`
}

func (o *GetPublicGroupByNameRequest) xxx_ToOp(ctx context.Context, op *xxx_GetPublicGroupByNameOperation) *xxx_GetPublicGroupByNameOperation {
	if op == nil {
		op = &xxx_GetPublicGroupByNameOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.Name = o.Name
	op.RIID = o.RIID
	return op
}

func (o *GetPublicGroupByNameRequest) xxx_FromOp(ctx context.Context, op *xxx_GetPublicGroupByNameOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.Name = op.Name
	o.RIID = op.RIID
}
func (o *GetPublicGroupByNameRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *GetPublicGroupByNameRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GetPublicGroupByNameOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeGetPublicGroupByNameRequest build a response structure from the given request structure.
func (o *GetPublicGroupByNameRequest) MakeResponse() *GetPublicGroupByNameResponse {
	return &GetPublicGroupByNameResponse{}
}

// OpNum returns the operation number of GetPublicGroupByName operation.
func (o *GetPublicGroupByNameRequest) OpNum() int { return 3 }

// OpName returns the operation name of GetPublicGroupByName operation.
func (o *GetPublicGroupByNameRequest) OpName() string {
	return "/IOPCServerPublicGroups/v0/GetPublicGroupByName"
}

// GetPublicGroupByNameResponse structure represents the GetPublicGroupByName operation response
type GetPublicGroupByNameResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That    *dcom.ORPCThat `idl:"name:That" json:"that"`
	Unknown *dcom.Unknown  `idl:"name:ppUnk" json:"unknown"`
	// Return: The GetPublicGroupByName return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *GetPublicGroupByNameResponse) xxx_ToOp(ctx context.Context, op *xxx_GetPublicGroupByNameOperation) *xxx_GetPublicGroupByNameOperation {
	if op == nil {
		op = &xxx_GetPublicGroupByNameOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Unknown = o.Unknown
	op.Return = o.Return
	return op
}

func (o *GetPublicGroupByNameResponse) xxx_FromOp(ctx context.Context, op *xxx_GetPublicGroupByNameOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Unknown = op.Unknown
	o.Return = op.Return
}
func (o *GetPublicGroupByNameResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *GetPublicGroupByNameResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GetPublicGroupByNameOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_RemovePublicGroupOperation structure represents the RemovePublicGroup operation
type xxx_RemovePublicGroupOperation struct {
	This        *dcom.ORPCThis `idl:"name:This" json:"this"`
	That        *dcom.ORPCThat `idl:"name:That" json:"that"`
	ServerGroup uint32         `idl:"name:hServerGroup" json:"server_group"`
	Force       bool           `idl:"name:bForce" json:"force"`
	Return      int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of RemovePublicGroup operation.
func (o *xxx_RemovePublicGroupOperation) OpNum() int { return 4 }

// OpName returns the operation name of RemovePublicGroup operation.
func (o *xxx_RemovePublicGroupOperation) OpName() string {
	return "/IOPCServerPublicGroups/v0/RemovePublicGroup"
}

func (o *xxx_RemovePublicGroupOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_RemovePublicGroupOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// hServerGroup {in} (1:{alias=OPCHANDLE, names=DWORD}(uint32))
	{
		if err := w.WriteData(o.ServerGroup); err != nil {
			return err
		}
	}
	// bForce {in} (1:{alias=BOOL}(int32))
	{
		if !o.Force {
			if err := w.WriteData(int32(0)); err != nil {
				return err
			}
		} else {
			if err := w.WriteData(int32(1)); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_RemovePublicGroupOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// hServerGroup {in} (1:{alias=OPCHANDLE, names=DWORD}(uint32))
	{
		if err := w.ReadData(&o.ServerGroup); err != nil {
			return err
		}
	}
	// bForce {in} (1:{alias=BOOL}(int32))
	{
		var _bForce int32
		if err := w.ReadData(&_bForce); err != nil {
			return err
		}
		o.Force = _bForce != 0
	}
	return nil
}

func (o *xxx_RemovePublicGroupOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_RemovePublicGroupOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_RemovePublicGroupOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// RemovePublicGroupRequest structure represents the RemovePublicGroup operation request
type RemovePublicGroupRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This        *dcom.ORPCThis `idl:"name:This" json:"this"`
	ServerGroup uint32         `idl:"name:hServerGroup" json:"server_group"`
	Force       bool           `idl:"name:bForce" json:"force"`
}

func (o *RemovePublicGroupRequest) xxx_ToOp(ctx context.Context, op *xxx_RemovePublicGroupOperation) *xxx_RemovePublicGroupOperation {
	if op == nil {
		op = &xxx_RemovePublicGroupOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.ServerGroup = o.ServerGroup
	op.Force = o.Force
	return op
}

func (o *RemovePublicGroupRequest) xxx_FromOp(ctx context.Context, op *xxx_RemovePublicGroupOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.ServerGroup = op.ServerGroup
	o.Force = op.Force
}
func (o *RemovePublicGroupRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *RemovePublicGroupRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_RemovePublicGroupOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeRemovePublicGroupRequest build a response structure from the given request structure.
func (o *RemovePublicGroupRequest) MakeResponse() *RemovePublicGroupResponse {
	return &RemovePublicGroupResponse{}
}

// OpNum returns the operation number of RemovePublicGroup operation.
func (o *RemovePublicGroupRequest) OpNum() int { return 4 }

// OpName returns the operation name of RemovePublicGroup operation.
func (o *RemovePublicGroupRequest) OpName() string {
	return "/IOPCServerPublicGroups/v0/RemovePublicGroup"
}

// RemovePublicGroupResponse structure represents the RemovePublicGroup operation response
type RemovePublicGroupResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That *dcom.ORPCThat `idl:"name:That" json:"that"`
	// Return: The RemovePublicGroup return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *RemovePublicGroupResponse) xxx_ToOp(ctx context.Context, op *xxx_RemovePublicGroupOperation) *xxx_RemovePublicGroupOperation {
	if op == nil {
		op = &xxx_RemovePublicGroupOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Return = o.Return
	return op
}

func (o *RemovePublicGroupResponse) xxx_FromOp(ctx context.Context, op *xxx_RemovePublicGroupOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Return = op.Return
}
func (o *RemovePublicGroupResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *RemovePublicGroupResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_RemovePublicGroupOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}
