// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopcgroupstatemgt

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom.GoPackage
	_ = iunknown.GoPackage
)

var (
	// import guard
	GoPackage = "opcda"
)

var (
	// IOPCGroupStateMgt interface identifier 39c13a50-011e-11d0-9675-0020afd8adb3
	GroupStateManagementIID = &dcom.IID{Data1: 0x39c13a50, Data2: 0x011e, Data3: 0x11d0, Data4: []byte{0x96, 0x75, 0x00, 0x20, 0xaf, 0xd8, 0xad, 0xb3}}
	// Syntax UUID
	GroupStateManagementSyntaxUUID = &uuid.UUID{TimeLow: 0x39c13a50, TimeMid: 0x11e, TimeHiAndVersion: 0x11d0, ClockSeqHiAndReserved: 0x96, ClockSeqLow: 0x75, Node: [6]uint8{0x0, 0x20, 0xaf, 0xd8, 0xad, 0xb3}}
	// Syntax ID
	GroupStateManagementSyntaxV0_0 = &dcerpc.SyntaxID{IfUUID: GroupStateManagementSyntaxUUID, IfVersionMajor: 0, IfVersionMinor: 0}
)

// IOPCGroupStateMgt interface.
type GroupStateManagementClient interface {

	// IUnknown retrieval method.
	Unknown() iunknown.UnknownClient

	// GetState operation.
	GetState(context.Context, *GetStateRequest, ...dcerpc.CallOption) (*GetStateResponse, error)

	// SetState operation.
	SetState(context.Context, *SetStateRequest, ...dcerpc.CallOption) (*SetStateResponse, error)

	// SetName operation.
	SetName(context.Context, *SetNameRequest, ...dcerpc.CallOption) (*SetNameResponse, error)

	// CloneGroup operation.
	CloneGroup(context.Context, *CloneGroupRequest, ...dcerpc.CallOption) (*CloneGroupResponse, error)

	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn

	// IPID sets the object interface identifier.
	IPID(context.Context, *dcom.IPID) GroupStateManagementClient
}

type xxx_DefaultGroupStateManagementClient struct {
	iunknown.UnknownClient
	cc   dcerpc.Conn
	ipid *dcom.IPID
}

func (o *xxx_DefaultGroupStateManagementClient) Unknown() iunknown.UnknownClient {
	return o.UnknownClient
}

func (o *xxx_DefaultGroupStateManagementClient) GetState(ctx context.Context, in *GetStateRequest, opts ...dcerpc.CallOption) (*GetStateResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &GetStateResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultGroupStateManagementClient) SetState(ctx context.Context, in *SetStateRequest, opts ...dcerpc.CallOption) (*SetStateResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &SetStateResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultGroupStateManagementClient) SetName(ctx context.Context, in *SetNameRequest, opts ...dcerpc.CallOption) (*SetNameResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &SetNameResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultGroupStateManagementClient) CloneGroup(ctx context.Context, in *CloneGroupRequest, opts ...dcerpc.CallOption) (*CloneGroupResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &CloneGroupResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultGroupStateManagementClient) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultGroupStateManagementClient) Conn() dcerpc.Conn {
	return o.cc
}

func (o *xxx_DefaultGroupStateManagementClient) IPID(ctx context.Context, ipid *dcom.IPID) GroupStateManagementClient {
	if ipid == nil {
		ipid = &dcom.IPID{}
	}
	return &xxx_DefaultGroupStateManagementClient{
		UnknownClient: o.UnknownClient.IPID(ctx, ipid),
		cc:            o.cc,
		ipid:          ipid,
	}
}

func NewGroupStateManagementClient(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (GroupStateManagementClient, error) {
	var err error
	if !dcom.IsSuperclass(opts) {
		cc, err = cc.Bind(ctx, append(opts, dcerpc.WithAbstractSyntax(GroupStateManagementSyntaxV0_0))...)
		if err != nil {
			return nil, err
		}
	}
	base, err := iunknown.NewUnknownClient(ctx, cc, append(opts, dcom.Superclass(cc))...)
	if err != nil {
		return nil, err
	}
	ipid, ok := dcom.HasIPID(opts)
	if ok {
		base = base.IPID(ctx, ipid)
	}
	return &xxx_DefaultGroupStateManagementClient{
		UnknownClient: base,
		cc:            cc,
		ipid:          ipid,
	}, nil
}

// xxx_GetStateOperation structure represents the GetState operation
type xxx_GetStateOperation struct {
	This            *dcom.ORPCThis `idl:"name:This" json:"this"`
	That            *dcom.ORPCThat `idl:"name:That" json:"that"`
	UpdateRate      uint32         `idl:"name:pUpdateRate" json:"update_rate"`
	Active          bool           `idl:"name:pActive" json:"active"`
	Name            string         `idl:"name:ppName;string" json:"name"`
	TimeBias        int32          `idl:"name:pTimeBias" json:"time_bias"`
	PercentDeadband float32        `idl:"name:pPercentDeadband" json:"percent_deadband"`
	LCID            uint32         `idl:"name:pLCID" json:"lcid"`
	ClientGroup     uint32         `idl:"name:phClientGroup" json:"client_group"`
	ServerGroup     uint32         `idl:"name:phServerGroup" json:"server_group"`
	Return          int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of GetState operation.
func (o *xxx_GetStateOperation) OpNum() int { return 3 }

// OpName returns the operation name of GetState operation.
func (o *xxx_GetStateOperation) OpName() string { return "/IOPCGroupStateMgt/v0/GetState" }

func (o *xxx_GetStateOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetStateOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetStateOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetStateOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetStateOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pUpdateRate {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.UpdateRate); err != nil {
			return err
		}
	}
	// pActive {out} (1:{pointer=ref}*(1))(2:{alias=BOOL}(int32))
	{
		if !o.Active {
			if err := w.WriteData(int32(0)); err != nil {
				return err
			}
		} else {
			if err := w.WriteData(int32(1)); err != nil {
				return err
			}
		}
	}
	// ppName {out} (1:{string, pointer=ref}*(2))(2:{alias=LPWSTR}*(1)[dim:0,string,null](wchar))
	{
		if o.Name != "" {
			_ptr_ppName := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if err := ndr.WriteUTF16NString(ctx, w, o.Name); err != nil {
					return err
				}
				return nil
			})
			if err := w.WritePointer(&o.Name, _ptr_ppName); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pTimeBias {out} (1:{pointer=ref}*(1))(2:{alias=LONG}(int32))
	{
		if err := w.WriteData(o.TimeBias); err != nil {
			return err
		}
	}
	// pPercentDeadband {out} (1:{pointer=ref}*(1))(2:{alias=FLOAT}(float32))
	{
		if err := w.WriteData(o.PercentDeadband); err != nil {
			return err
		}
	}
	// pLCID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.LCID); err != nil {
			return err
		}
	}
	// phClientGroup {out} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}(uint32))
	{
		if err := w.WriteData(o.ClientGroup); err != nil {
			return err
		}
	}
	// phServerGroup {out} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}(uint32))
	{
		if err := w.WriteData(o.ServerGroup); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_GetStateOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pUpdateRate {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.UpdateRate); err != nil {
			return err
		}
	}
	// pActive {out} (1:{pointer=ref}*(1))(2:{alias=BOOL}(int32))
	{
		var _bActive int32
		if err := w.ReadData(&_bActive); err != nil {
			return err
		}
		o.Active = _bActive != 0
	}
	// ppName {out} (1:{string, pointer=ref}*(2))(2:{alias=LPWSTR,pointer=ref}*(1)[dim:0,string,null](wchar))
	{
		_ptr_ppName := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if err := ndr.ReadUTF16NString(ctx, w, &o.Name); err != nil {
				return err
			}
			return nil
		})
		_s_ppName := func(ptr interface{}) { o.Name = *ptr.(*string) }
		if err := w.ReadPointer(&o.Name, _s_ppName, _ptr_ppName); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pTimeBias {out} (1:{pointer=ref}*(1))(2:{alias=LONG}(int32))
	{
		if err := w.ReadData(&o.TimeBias); err != nil {
			return err
		}
	}
	// pPercentDeadband {out} (1:{pointer=ref}*(1))(2:{alias=FLOAT}(float32))
	{
		if err := w.ReadData(&o.PercentDeadband); err != nil {
			return err
		}
	}
	// pLCID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.LCID); err != nil {
			return err
		}
	}
	// phClientGroup {out} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}(uint32))
	{
		if err := w.ReadData(&o.ClientGroup); err != nil {
			return err
		}
	}
	// phServerGroup {out} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}(uint32))
	{
		if err := w.ReadData(&o.ServerGroup); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// GetStateRequest structure represents the GetState operation request
type GetStateRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This *dcom.ORPCThis `idl:"name:This" json:"this"`
}

func (o *GetStateRequest) xxx_ToOp(ctx context.Context, op *xxx_GetStateOperation) *xxx_GetStateOperation {
	if op == nil {
		op = &xxx_GetStateOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	return op
}

func (o *GetStateRequest) xxx_FromOp(ctx context.Context, op *xxx_GetStateOperation) {
	if o == nil {
		return
	}
	o.This = op.This
}
func (o *GetStateRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *GetStateRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GetStateOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeGetStateRequest build a response structure from the given request structure.
func (o *GetStateRequest) MakeResponse() *GetStateResponse {
	return &GetStateResponse{}
}

// OpNum returns the operation number of GetState operation.
func (o *GetStateRequest) OpNum() int { return 3 }

// OpName returns the operation name of GetState operation.
func (o *GetStateRequest) OpName() string { return "/IOPCGroupStateMgt/v0/GetState" }

// GetStateResponse structure represents the GetState operation response
type GetStateResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That            *dcom.ORPCThat `idl:"name:That" json:"that"`
	UpdateRate      uint32         `idl:"name:pUpdateRate" json:"update_rate"`
	Active          bool           `idl:"name:pActive" json:"active"`
	Name            string         `idl:"name:ppName;string" json:"name"`
	TimeBias        int32          `idl:"name:pTimeBias" json:"time_bias"`
	PercentDeadband float32        `idl:"name:pPercentDeadband" json:"percent_deadband"`
	LCID            uint32         `idl:"name:pLCID" json:"lcid"`
	ClientGroup     uint32         `idl:"name:phClientGroup" json:"client_group"`
	ServerGroup     uint32         `idl:"name:phServerGroup" json:"server_group"`
	// Return: The GetState return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *GetStateResponse) xxx_ToOp(ctx context.Context, op *xxx_GetStateOperation) *xxx_GetStateOperation {
	if op == nil {
		op = &xxx_GetStateOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.UpdateRate = o.UpdateRate
	op.Active = o.Active
	op.Name = o.Name
	op.TimeBias = o.TimeBias
	op.PercentDeadband = o.PercentDeadband
	op.LCID = o.LCID
	op.ClientGroup = o.ClientGroup
	op.ServerGroup = o.ServerGroup
	op.Return = o.Return
	return op
}

func (o *GetStateResponse) xxx_FromOp(ctx context.Context, op *xxx_GetStateOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.UpdateRate = op.UpdateRate
	o.Active = op.Active
	o.Name = op.Name
	o.TimeBias = op.TimeBias
	o.PercentDeadband = op.PercentDeadband
	o.LCID = op.LCID
	o.ClientGroup = op.ClientGroup
	o.ServerGroup = op.ServerGroup
	o.Return = op.Return
}
func (o *GetStateResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *GetStateResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_GetStateOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_SetStateOperation structure represents the SetState operation
type xxx_SetStateOperation struct {
	This                *dcom.ORPCThis `idl:"name:This" json:"this"`
	That                *dcom.ORPCThat `idl:"name:That" json:"that"`
	RequestedUpdateRate uint32         `idl:"name:pRequestedUpdateRate;pointer:unique" json:"requested_update_rate"`
	RevisedUpdateRate   uint32         `idl:"name:pRevisedUpdateRate" json:"revised_update_rate"`
	Active              bool           `idl:"name:pActive;pointer:unique" json:"active"`
	TimeBias            int32          `idl:"name:pTimeBias;pointer:unique" json:"time_bias"`
	PercentDeadband     float32        `idl:"name:pPercentDeadband;pointer:unique" json:"percent_deadband"`
	LCID                uint32         `idl:"name:pLCID;pointer:unique" json:"lcid"`
	ClientGroup         uint32         `idl:"name:phClientGroup;pointer:unique" json:"client_group"`
	Return              int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of SetState operation.
func (o *xxx_SetStateOperation) OpNum() int { return 4 }

// OpName returns the operation name of SetState operation.
func (o *xxx_SetStateOperation) OpName() string { return "/IOPCGroupStateMgt/v0/SetState" }

func (o *xxx_SetStateOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SetStateOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pRequestedUpdateRate {in} (1:{pointer=unique}*(1))(2:{alias=DWORD}(uint32))
	{
		// XXX pointer to primitive type, default behavior is to write non-null pointer.
		// if this behavior is not desired, use goext_default_null([cond]) attribute.
		_ptr_pRequestedUpdateRate := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			if err := w.WriteData(o.RequestedUpdateRate); err != nil {
				return err
			}
			return nil
		})
		if err := w.WritePointer(&o.RequestedUpdateRate, _ptr_pRequestedUpdateRate); err != nil {
			return err
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pActive {in} (1:{pointer=unique}*(1))(2:{alias=BOOL}(int32))
	{
		// XXX pointer to primitive type, default behavior is to write non-null pointer.
		// if this behavior is not desired, use goext_default_null([cond]) attribute.
		_ptr_pActive := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			if !o.Active {
				if err := w.WriteData(int32(0)); err != nil {
					return err
				}
			} else {
				if err := w.WriteData(int32(1)); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.Active, _ptr_pActive); err != nil {
			return err
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pTimeBias {in} (1:{pointer=unique}*(1))(2:{alias=LONG}(int32))
	{
		// XXX pointer to primitive type, default behavior is to write non-null pointer.
		// if this behavior is not desired, use goext_default_null([cond]) attribute.
		_ptr_pTimeBias := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			if err := w.WriteData(o.TimeBias); err != nil {
				return err
			}
			return nil
		})
		if err := w.WritePointer(&o.TimeBias, _ptr_pTimeBias); err != nil {
			return err
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pPercentDeadband {in} (1:{pointer=unique}*(1))(2:{alias=FLOAT}(float32))
	{
		// XXX pointer to primitive type, default behavior is to write non-null pointer.
		// if this behavior is not desired, use goext_default_null([cond]) attribute.
		_ptr_pPercentDeadband := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			if err := w.WriteData(o.PercentDeadband); err != nil {
				return err
			}
			return nil
		})
		if err := w.WritePointer(&o.PercentDeadband, _ptr_pPercentDeadband); err != nil {
			return err
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pLCID {in} (1:{pointer=unique}*(1))(2:{alias=DWORD}(uint32))
	{
		// XXX pointer to primitive type, default behavior is to write non-null pointer.
		// if this behavior is not desired, use goext_default_null([cond]) attribute.
		_ptr_pLCID := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			if err := w.WriteData(o.LCID); err != nil {
				return err
			}
			return nil
		})
		if err := w.WritePointer(&o.LCID, _ptr_pLCID); err != nil {
			return err
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// phClientGroup {in} (1:{pointer=unique}*(1))(2:{alias=OPCHANDLE, names=DWORD}(uint32))
	{
		// XXX pointer to primitive type, default behavior is to write non-null pointer.
		// if this behavior is not desired, use goext_default_null([cond]) attribute.
		_ptr_phClientGroup := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			if err := w.WriteData(o.ClientGroup); err != nil {
				return err
			}
			return nil
		})
		if err := w.WritePointer(&o.ClientGroup, _ptr_phClientGroup); err != nil {
			return err
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SetStateOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pRequestedUpdateRate {in} (1:{pointer=unique}*(1))(2:{alias=DWORD}(uint32))
	{
		_ptr_pRequestedUpdateRate := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if err := w.ReadData(&o.RequestedUpdateRate); err != nil {
				return err
			}
			return nil
		})
		_s_pRequestedUpdateRate := func(ptr interface{}) { o.RequestedUpdateRate = *ptr.(*uint32) }
		if err := w.ReadPointer(&o.RequestedUpdateRate, _s_pRequestedUpdateRate, _ptr_pRequestedUpdateRate); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pActive {in} (1:{pointer=unique}*(1))(2:{alias=BOOL}(int32))
	{
		_ptr_pActive := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			var _bActive int32
			if err := w.ReadData(&_bActive); err != nil {
				return err
			}
			o.Active = _bActive != 0
			return nil
		})
		_s_pActive := func(ptr interface{}) { o.Active = *ptr.(*bool) }
		if err := w.ReadPointer(&o.Active, _s_pActive, _ptr_pActive); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pTimeBias {in} (1:{pointer=unique}*(1))(2:{alias=LONG}(int32))
	{
		_ptr_pTimeBias := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if err := w.ReadData(&o.TimeBias); err != nil {
				return err
			}
			return nil
		})
		_s_pTimeBias := func(ptr interface{}) { o.TimeBias = *ptr.(*int32) }
		if err := w.ReadPointer(&o.TimeBias, _s_pTimeBias, _ptr_pTimeBias); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pPercentDeadband {in} (1:{pointer=unique}*(1))(2:{alias=FLOAT}(float32))
	{
		_ptr_pPercentDeadband := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if err := w.ReadData(&o.PercentDeadband); err != nil {
				return err
			}
			return nil
		})
		_s_pPercentDeadband := func(ptr interface{}) { o.PercentDeadband = *ptr.(*float32) }
		if err := w.ReadPointer(&o.PercentDeadband, _s_pPercentDeadband, _ptr_pPercentDeadband); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pLCID {in} (1:{pointer=unique}*(1))(2:{alias=DWORD}(uint32))
	{
		_ptr_pLCID := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if err := w.ReadData(&o.LCID); err != nil {
				return err
			}
			return nil
		})
		_s_pLCID := func(ptr interface{}) { o.LCID = *ptr.(*uint32) }
		if err := w.ReadPointer(&o.LCID, _s_pLCID, _ptr_pLCID); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// phClientGroup {in} (1:{pointer=unique}*(1))(2:{alias=OPCHANDLE, names=DWORD}(uint32))
	{
		_ptr_phClientGroup := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if err := w.ReadData(&o.ClientGroup); err != nil {
				return err
			}
			return nil
		})
		_s_phClientGroup := func(ptr interface{}) { o.ClientGroup = *ptr.(*uint32) }
		if err := w.ReadPointer(&o.ClientGroup, _s_phClientGroup, _ptr_phClientGroup); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SetStateOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SetStateOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pRevisedUpdateRate {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.RevisedUpdateRate); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SetStateOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pRevisedUpdateRate {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.RevisedUpdateRate); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// SetStateRequest structure represents the SetState operation request
type SetStateRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This                *dcom.ORPCThis `idl:"name:This" json:"this"`
	RequestedUpdateRate uint32         `idl:"name:pRequestedUpdateRate;pointer:unique" json:"requested_update_rate"`
	Active              bool           `idl:"name:pActive;pointer:unique" json:"active"`
	TimeBias            int32          `idl:"name:pTimeBias;pointer:unique" json:"time_bias"`
	PercentDeadband     float32        `idl:"name:pPercentDeadband;pointer:unique" json:"percent_deadband"`
	LCID                uint32         `idl:"name:pLCID;pointer:unique" json:"lcid"`
	ClientGroup         uint32         `idl:"name:phClientGroup;pointer:unique" json:"client_group"`
}

func (o *SetStateRequest) xxx_ToOp(ctx context.Context, op *xxx_SetStateOperation) *xxx_SetStateOperation {
	if op == nil {
		op = &xxx_SetStateOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.RequestedUpdateRate = o.RequestedUpdateRate
	op.Active = o.Active
	op.TimeBias = o.TimeBias
	op.PercentDeadband = o.PercentDeadband
	op.LCID = o.LCID
	op.ClientGroup = o.ClientGroup
	return op
}

func (o *SetStateRequest) xxx_FromOp(ctx context.Context, op *xxx_SetStateOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.RequestedUpdateRate = op.RequestedUpdateRate
	o.Active = op.Active
	o.TimeBias = op.TimeBias
	o.PercentDeadband = op.PercentDeadband
	o.LCID = op.LCID
	o.ClientGroup = op.ClientGroup
}
func (o *SetStateRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *SetStateRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_SetStateOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeSetStateRequest build a response structure from the given request structure.
func (o *SetStateRequest) MakeResponse() *SetStateResponse {
	return &SetStateResponse{}
}

// OpNum returns the operation number of SetState operation.
func (o *SetStateRequest) OpNum() int { return 4 }

// OpName returns the operation name of SetState operation.
func (o *SetStateRequest) OpName() string { return "/IOPCGroupStateMgt/v0/SetState" }

// SetStateResponse structure represents the SetState operation response
type SetStateResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That              *dcom.ORPCThat `idl:"name:That" json:"that"`
	RevisedUpdateRate uint32         `idl:"name:pRevisedUpdateRate" json:"revised_update_rate"`
	// Return: The SetState return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *SetStateResponse) xxx_ToOp(ctx context.Context, op *xxx_SetStateOperation) *xxx_SetStateOperation {
	if op == nil {
		op = &xxx_SetStateOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.RevisedUpdateRate = o.RevisedUpdateRate
	op.Return = o.Return
	return op
}

func (o *SetStateResponse) xxx_FromOp(ctx context.Context, op *xxx_SetStateOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.RevisedUpdateRate = op.RevisedUpdateRate
	o.Return = op.Return
}
func (o *SetStateResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *SetStateResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_SetStateOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_SetNameOperation structure represents the SetName operation
type xxx_SetNameOperation struct {
	This   *dcom.ORPCThis `idl:"name:This" json:"this"`
	That   *dcom.ORPCThat `idl:"name:That" json:"that"`
	Name   string         `idl:"name:szName;string" json:"name"`
	Return int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of SetName operation.
func (o *xxx_SetNameOperation) OpNum() int { return 5 }

// OpName returns the operation name of SetName operation.
func (o *xxx_SetNameOperation) OpName() string { return "/IOPCGroupStateMgt/v0/SetName" }

func (o *xxx_SetNameOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SetNameOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// szName {in} (1:{string, alias=LPCWSTR}*(1)[dim:0,string,null](wchar))
	{
		if err := ndr.WriteUTF16NString(ctx, w, o.Name); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SetNameOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// szName {in} (1:{string, alias=LPCWSTR,pointer=ref}*(1)[dim:0,string,null](wchar))
	{
		if err := ndr.ReadUTF16NString(ctx, w, &o.Name); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SetNameOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SetNameOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SetNameOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// SetNameRequest structure represents the SetName operation request
type SetNameRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This *dcom.ORPCThis `idl:"name:This" json:"this"`
	Name string         `idl:"name:szName;string" json:"name"`
}

func (o *SetNameRequest) xxx_ToOp(ctx context.Context, op *xxx_SetNameOperation) *xxx_SetNameOperation {
	if op == nil {
		op = &xxx_SetNameOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.Name = o.Name
	return op
}

func (o *SetNameRequest) xxx_FromOp(ctx context.Context, op *xxx_SetNameOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.Name = op.Name
}
func (o *SetNameRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *SetNameRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_SetNameOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeSetNameRequest build a response structure from the given request structure.
func (o *SetNameRequest) MakeResponse() *SetNameResponse {
	return &SetNameResponse{}
}

// OpNum returns the operation number of SetName operation.
func (o *SetNameRequest) OpNum() int { return 5 }

// OpName returns the operation name of SetName operation.
func (o *SetNameRequest) OpName() string { return "/IOPCGroupStateMgt/v0/SetName" }

// SetNameResponse structure represents the SetName operation response
type SetNameResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That *dcom.ORPCThat `idl:"name:That" json:"that"`
	// Return: The SetName return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *SetNameResponse) xxx_ToOp(ctx context.Context, op *xxx_SetNameOperation) *xxx_SetNameOperation {
	if op == nil {
		op = &xxx_SetNameOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Return = o.Return
	return op
}

func (o *SetNameResponse) xxx_FromOp(ctx context.Context, op *xxx_SetNameOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Return = op.Return
}
func (o *SetNameResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *SetNameResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_SetNameOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_CloneGroupOperation structure represents the CloneGroup operation
type xxx_CloneGroupOperation struct {
	This    *dcom.ORPCThis `idl:"name:This" json:"this"`
	That    *dcom.ORPCThat `idl:"name:That" json:"that"`
	Name    string         `idl:"name:szName;string" json:"name"`
	RIID    *dcom.IID      `idl:"name:riid" json:"riid"`
	Unknown *dcom.Unknown  `idl:"name:ppUnk" json:"unknown"`
	Return  int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of CloneGroup operation.
func (o *xxx_CloneGroupOperation) OpNum() int { return 6 }

// OpName returns the operation name of CloneGroup operation.
func (o *xxx_CloneGroupOperation) OpName() string { return "/IOPCGroupStateMgt/v0/CloneGroup" }

func (o *xxx_CloneGroupOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CloneGroupOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// szName {in} (1:{string, alias=LPCWSTR}*(1)[dim:0,string,null](wchar))
	{
		if err := ndr.WriteUTF16NString(ctx, w, o.Name); err != nil {
			return err
		}
	}
	// riid {in} (1:{alias=REFIID}*(1))(2:{alias=IID, names=GUID}(struct))
	{
		if o.RIID != nil {
			if err := o.RIID.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.IID{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_CloneGroupOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// szName {in} (1:{string, alias=LPCWSTR,pointer=ref}*(1)[dim:0,string,null](wchar))
	{
		if err := ndr.ReadUTF16NString(ctx, w, &o.Name); err != nil {
			return err
		}
	}
	// riid {in} (1:{alias=REFIID,pointer=ref}*(1))(2:{alias=IID, names=GUID}(struct))
	{
		if o.RIID == nil {
			o.RIID = &dcom.IID{}
		}
		if err := o.RIID.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CloneGroupOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CloneGroupOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// ppUnk {out, iid_is={riid}} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=LPUNKNOWN}*(1))(3:{alias=IUnknown}(interface))
	{
		if o.Unknown != nil {
			_ptr_ppUnk := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.Unknown != nil {
					if err := o.Unknown.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&dcom.Unknown{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Unknown, _ptr_ppUnk); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CloneGroupOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// ppUnk {out, iid_is={riid}} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=LPUNKNOWN}*(1))(3:{alias=IUnknown}(interface))
	{
		_ptr_ppUnk := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.Unknown == nil {
				o.Unknown = &dcom.Unknown{}
			}
			if err := o.Unknown.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_ppUnk := func(ptr interface{}) { o.Unknown = *ptr.(**dcom.Unknown) }
		if err := w.ReadPointer(&o.Unknown, _s_ppUnk, _ptr_ppUnk); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// CloneGroupRequest structure represents the CloneGroup operation request
type CloneGroupRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This *dcom.ORPCThis `idl:"name:This" json:"this"`
	Name string         `idl:"name:szName;string" json:"name"`
	RIID *dcom.IID      `idl:"name:riid" json:"riid"`
}

func (o *CloneGroupRequest) xxx_ToOp(ctx context.Context, op *xxx_CloneGroupOperation) *xxx_CloneGroupOperation {
	if op == nil {
		op = &xxx_CloneGroupOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.Name = o.Name
	op.RIID = o.RIID
	return op
}

func (o *CloneGroupRequest) xxx_FromOp(ctx context.Context, op *xxx_CloneGroupOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.Name = op.Name
	o.RIID = op.RIID
}
func (o *CloneGroupRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *CloneGroupRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_CloneGroupOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeCloneGroupRequest build a response structure from the given request structure.
func (o *CloneGroupRequest) MakeResponse() *CloneGroupResponse {
	return &CloneGroupResponse{}
}

// OpNum returns the operation number of CloneGroup operation.
func (o *CloneGroupRequest) OpNum() int { return 6 }

// OpName returns the operation name of CloneGroup operation.
func (o *CloneGroupRequest) OpName() string { return "/IOPCGroupStateMgt/v0/CloneGroup" }

// CloneGroupResponse structure represents the CloneGroup operation response
type CloneGroupResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That    *dcom.ORPCThat `idl:"name:That" json:"that"`
	Unknown *dcom.Unknown  `idl:"name:ppUnk" json:"unknown"`
	// Return: The CloneGroup return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *CloneGroupResponse) xxx_ToOp(ctx context.Context, op *xxx_CloneGroupOperation) *xxx_CloneGroupOperation {
	if op == nil {
		op = &xxx_CloneGroupOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Unknown = o.Unknown
	op.Return = o.Return
	return op
}

func (o *CloneGroupResponse) xxx_FromOp(ctx context.Context, op *xxx_CloneGroupOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Unknown = op.Unknown
	o.Return = op.Return
}
func (o *CloneGroupResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *CloneGroupResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_CloneGroupOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}
