// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

// The opchda package implements the OPCHDA client protocol.
package opchda

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	oaut "github.com/oiweiwei/go-msrpc/msrpc/dcom/oaut"
	dtyp "github.com/oiweiwei/go-msrpc/msrpc/dtyp"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dtyp.GoPackage
	_ = oaut.GoPackage
	_ = dcom.GoPackage
)

var (
	// import guard
	GoPackage = "opchda"
)

// ServerStatus type represents OPCHDA_SERVERSTATUS RPC enumeration.
type ServerStatus uint16

var (
	ServerStatusUp            ServerStatus = 1
	ServerStatusDown          ServerStatus = 2
	ServerStatusIndeterminate ServerStatus = 3
)

func (o ServerStatus) String() string {
	switch o {
	case ServerStatusUp:
		return "ServerStatusUp"
	case ServerStatusDown:
		return "ServerStatusDown"
	case ServerStatusIndeterminate:
		return "ServerStatusIndeterminate"
	}
	return "Invalid"
}

// BrowseDirection type represents OPCHDA_BROWSEDIRECTION RPC enumeration.
type BrowseDirection uint16

var (
	BrowseDirectionUp     BrowseDirection = 1
	BrowseDirectionDown   BrowseDirection = 2
	BrowseDirectionDirect BrowseDirection = 3
)

func (o BrowseDirection) String() string {
	switch o {
	case BrowseDirectionUp:
		return "BrowseDirectionUp"
	case BrowseDirectionDown:
		return "BrowseDirectionDown"
	case BrowseDirectionDirect:
		return "BrowseDirectionDirect"
	}
	return "Invalid"
}

// BrowseType type represents OPCHDA_BROWSETYPE RPC enumeration.
type BrowseType uint16

var (
	BrowseTypeBranch BrowseType = 1
	BrowseTypeLeaf   BrowseType = 2
	BrowseTypeFlat   BrowseType = 3
	BrowseTypeItems  BrowseType = 4
)

func (o BrowseType) String() string {
	switch o {
	case BrowseTypeBranch:
		return "BrowseTypeBranch"
	case BrowseTypeLeaf:
		return "BrowseTypeLeaf"
	case BrowseTypeFlat:
		return "BrowseTypeFlat"
	case BrowseTypeItems:
		return "BrowseTypeItems"
	}
	return "Invalid"
}

// AnnotationCapabilities type represents OPCHDA_ANNOTATIONCAPABILITIES RPC enumeration.
type AnnotationCapabilities uint16

var (
	AnnotationCapabilitiesRead   AnnotationCapabilities = 1
	AnnotationCapabilitiesInsert AnnotationCapabilities = 2
)

func (o AnnotationCapabilities) String() string {
	switch o {
	case AnnotationCapabilitiesRead:
		return "AnnotationCapabilitiesRead"
	case AnnotationCapabilitiesInsert:
		return "AnnotationCapabilitiesInsert"
	}
	return "Invalid"
}

// UpdateCapabilities type represents OPCHDA_UPDATECAPABILITIES RPC enumeration.
type UpdateCapabilities uint16

var (
	UpdateCapabilitiesInsert           UpdateCapabilities = 1
	UpdateCapabilitiesReplace          UpdateCapabilities = 2
	UpdateCapabilitiesInsertreplacecap UpdateCapabilities = 4
	UpdateCapabilitiesDeleteRaw        UpdateCapabilities = 8
	UpdateCapabilitiesDeleteAtTime     UpdateCapabilities = 16
)

func (o UpdateCapabilities) String() string {
	switch o {
	case UpdateCapabilitiesInsert:
		return "UpdateCapabilitiesInsert"
	case UpdateCapabilitiesReplace:
		return "UpdateCapabilitiesReplace"
	case UpdateCapabilitiesInsertreplacecap:
		return "UpdateCapabilitiesInsertreplacecap"
	case UpdateCapabilitiesDeleteRaw:
		return "UpdateCapabilitiesDeleteRaw"
	case UpdateCapabilitiesDeleteAtTime:
		return "UpdateCapabilitiesDeleteAtTime"
	}
	return "Invalid"
}

// OperatorCodes type represents OPCHDA_OPERATORCODES RPC enumeration.
type OperatorCodes uint16

var (
	OperatorCodesEqual        OperatorCodes = 1
	OperatorCodesLess         OperatorCodes = 2
	OperatorCodesLessEqual    OperatorCodes = 3
	OperatorCodesGreater      OperatorCodes = 4
	OperatorCodesGreaterEqual OperatorCodes = 5
	OperatorCodesNotEqual     OperatorCodes = 6
)

func (o OperatorCodes) String() string {
	switch o {
	case OperatorCodesEqual:
		return "OperatorCodesEqual"
	case OperatorCodesLess:
		return "OperatorCodesLess"
	case OperatorCodesLessEqual:
		return "OperatorCodesLessEqual"
	case OperatorCodesGreater:
		return "OperatorCodesGreater"
	case OperatorCodesGreaterEqual:
		return "OperatorCodesGreaterEqual"
	case OperatorCodesNotEqual:
		return "OperatorCodesNotEqual"
	}
	return "Invalid"
}

// EditType type represents OPCHDA_EDITTYPE RPC enumeration.
type EditType uint16

var (
	EditTypeInsert        EditType = 1
	EditTypeReplace       EditType = 2
	EditTypeInsertReplace EditType = 3
	EditTypeDelete        EditType = 4
)

func (o EditType) String() string {
	switch o {
	case EditTypeInsert:
		return "EditTypeInsert"
	case EditTypeReplace:
		return "EditTypeReplace"
	case EditTypeInsertReplace:
		return "EditTypeInsertReplace"
	case EditTypeDelete:
		return "EditTypeDelete"
	}
	return "Invalid"
}

// Aggregate type represents OPCHDA_AGGREGATE RPC enumeration.
type Aggregate uint16

var (
	AggregateNoAggregate       Aggregate = 0
	AggregateInterpolative     Aggregate = 1
	AggregateTotal             Aggregate = 2
	AggregateAverage           Aggregate = 3
	AggregateTimeAverage       Aggregate = 4
	AggregateCount             Aggregate = 5
	AggregateStandardDeviation Aggregate = 6
	AggregateMinimumActualTime Aggregate = 7
	AggregateMinimum           Aggregate = 8
	AggregateMaximumActualTime Aggregate = 9
	AggregateMaximum           Aggregate = 10
	AggregateStart             Aggregate = 11
	AggregateEnd               Aggregate = 12
	AggregateDelta             Aggregate = 13
	AggregateRegisterSlope     Aggregate = 14
	AggregateRegisterConstant  Aggregate = 15
	AggregateRegisterDeviation Aggregate = 16
	AggregateVariance          Aggregate = 17
	AggregateRange             Aggregate = 18
	AggregateDurationGood      Aggregate = 19
	AggregateDurationBad       Aggregate = 20
	AggregatePercentGood       Aggregate = 21
	AggregatePercentBad        Aggregate = 22
	AggregateWorstQuality      Aggregate = 23
	AggregateAnnotations       Aggregate = 24
)

func (o Aggregate) String() string {
	switch o {
	case AggregateNoAggregate:
		return "AggregateNoAggregate"
	case AggregateInterpolative:
		return "AggregateInterpolative"
	case AggregateTotal:
		return "AggregateTotal"
	case AggregateAverage:
		return "AggregateAverage"
	case AggregateTimeAverage:
		return "AggregateTimeAverage"
	case AggregateCount:
		return "AggregateCount"
	case AggregateStandardDeviation:
		return "AggregateStandardDeviation"
	case AggregateMinimumActualTime:
		return "AggregateMinimumActualTime"
	case AggregateMinimum:
		return "AggregateMinimum"
	case AggregateMaximumActualTime:
		return "AggregateMaximumActualTime"
	case AggregateMaximum:
		return "AggregateMaximum"
	case AggregateStart:
		return "AggregateStart"
	case AggregateEnd:
		return "AggregateEnd"
	case AggregateDelta:
		return "AggregateDelta"
	case AggregateRegisterSlope:
		return "AggregateRegisterSlope"
	case AggregateRegisterConstant:
		return "AggregateRegisterConstant"
	case AggregateRegisterDeviation:
		return "AggregateRegisterDeviation"
	case AggregateVariance:
		return "AggregateVariance"
	case AggregateRange:
		return "AggregateRange"
	case AggregateDurationGood:
		return "AggregateDurationGood"
	case AggregateDurationBad:
		return "AggregateDurationBad"
	case AggregatePercentGood:
		return "AggregatePercentGood"
	case AggregatePercentBad:
		return "AggregatePercentBad"
	case AggregateWorstQuality:
		return "AggregateWorstQuality"
	case AggregateAnnotations:
		return "AggregateAnnotations"
	}
	return "Invalid"
}

// Annotation structure represents OPCHDA_ANNOTATION RPC structure.
type Annotation struct {
	Client         uint32           `idl:"name:hClient" json:"client"`
	NumValues      uint32           `idl:"name:dwNumValues" json:"num_values"`
	Timestamps     []*dtyp.Filetime `idl:"name:ftTimeStamps;size_is:(dwNumValues)" json:"timestamps"`
	Annotation     []string         `idl:"name:szAnnotation;size_is:(dwNumValues);string" json:"annotation"`
	AnnotationTime []*dtyp.Filetime `idl:"name:ftAnnotationTime;size_is:(dwNumValues)" json:"annotation_time"`
	User           []string         `idl:"name:szUser;size_is:(dwNumValues);string" json:"user"`
}

func (o *Annotation) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Timestamps != nil && o.NumValues == 0 {
		o.NumValues = uint32(len(o.Timestamps))
	}
	if o.Annotation != nil && o.NumValues == 0 {
		o.NumValues = uint32(len(o.Annotation))
	}
	if o.AnnotationTime != nil && o.NumValues == 0 {
		o.NumValues = uint32(len(o.AnnotationTime))
	}
	if o.User != nil && o.NumValues == 0 {
		o.NumValues = uint32(len(o.User))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}
func (o *Annotation) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	if err := w.WriteAlign(9); err != nil {
		return err
	}
	if err := w.WriteData(o.Client); err != nil {
		return err
	}
	if err := w.WriteData(o.NumValues); err != nil {
		return err
	}
	if o.Timestamps != nil || o.NumValues > 0 {
		_ptr_ftTimeStamps := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.NumValues)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.Timestamps {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if o.Timestamps[i1] != nil {
					if err := o.Timestamps[i1].MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
			}
			for i1 := len(o.Timestamps); uint64(i1) < sizeInfo[0]; i1++ {
				if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.Timestamps, _ptr_ftTimeStamps); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	if o.Annotation != nil || o.NumValues > 0 {
		_ptr_szAnnotation := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.NumValues)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.Annotation {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if o.Annotation[i1] != "" {
					_ptr_szAnnotation := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
						if err := ndr.WriteUTF16NString(ctx, w, o.Annotation[i1]); err != nil {
							return err
						}
						return nil
					})
					if err := w.WritePointer(&o.Annotation[i1], _ptr_szAnnotation); err != nil {
						return err
					}
				} else {
					if err := w.WritePointer(nil); err != nil {
						return err
					}
				}
			}
			for i1 := len(o.Annotation); uint64(i1) < sizeInfo[0]; i1++ {
				if err := w.WritePointer(nil); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.Annotation, _ptr_szAnnotation); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	if o.AnnotationTime != nil || o.NumValues > 0 {
		_ptr_ftAnnotationTime := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.NumValues)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.AnnotationTime {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if o.AnnotationTime[i1] != nil {
					if err := o.AnnotationTime[i1].MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
			}
			for i1 := len(o.AnnotationTime); uint64(i1) < sizeInfo[0]; i1++ {
				if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.AnnotationTime, _ptr_ftAnnotationTime); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	if o.User != nil || o.NumValues > 0 {
		_ptr_szUser := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.NumValues)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.User {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if o.User[i1] != "" {
					_ptr_szUser := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
						if err := ndr.WriteUTF16NString(ctx, w, o.User[i1]); err != nil {
							return err
						}
						return nil
					})
					if err := w.WritePointer(&o.User[i1], _ptr_szUser); err != nil {
						return err
					}
				} else {
					if err := w.WritePointer(nil); err != nil {
						return err
					}
				}
			}
			for i1 := len(o.User); uint64(i1) < sizeInfo[0]; i1++ {
				if err := w.WritePointer(nil); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.User, _ptr_szUser); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	return nil
}
func (o *Annotation) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	if err := w.ReadAlign(9); err != nil {
		return err
	}
	if err := w.ReadData(&o.Client); err != nil {
		return err
	}
	if err := w.ReadData(&o.NumValues); err != nil {
		return err
	}
	_ptr_ftTimeStamps := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.NumValues > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.NumValues)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Timestamps", sizeInfo[0])
		}
		o.Timestamps = make([]*dtyp.Filetime, sizeInfo[0])
		for i1 := range o.Timestamps {
			i1 := i1
			if o.Timestamps[i1] == nil {
				o.Timestamps[i1] = &dtyp.Filetime{}
			}
			if err := o.Timestamps[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		return nil
	})
	_s_ftTimeStamps := func(ptr interface{}) { o.Timestamps = *ptr.(*[]*dtyp.Filetime) }
	if err := w.ReadPointer(&o.Timestamps, _s_ftTimeStamps, _ptr_ftTimeStamps); err != nil {
		return err
	}
	_ptr_szAnnotation := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.NumValues > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.NumValues)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Annotation", sizeInfo[0])
		}
		o.Annotation = make([]string, sizeInfo[0])
		for i1 := range o.Annotation {
			i1 := i1
			_ptr_szAnnotation := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
				if err := ndr.ReadUTF16NString(ctx, w, &o.Annotation[i1]); err != nil {
					return err
				}
				return nil
			})
			_s_szAnnotation := func(ptr interface{}) { o.Annotation[i1] = *ptr.(*string) }
			if err := w.ReadPointer(&o.Annotation[i1], _s_szAnnotation, _ptr_szAnnotation); err != nil {
				return err
			}
		}
		return nil
	})
	_s_szAnnotation := func(ptr interface{}) { o.Annotation = *ptr.(*[]string) }
	if err := w.ReadPointer(&o.Annotation, _s_szAnnotation, _ptr_szAnnotation); err != nil {
		return err
	}
	_ptr_ftAnnotationTime := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.NumValues > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.NumValues)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.AnnotationTime", sizeInfo[0])
		}
		o.AnnotationTime = make([]*dtyp.Filetime, sizeInfo[0])
		for i1 := range o.AnnotationTime {
			i1 := i1
			if o.AnnotationTime[i1] == nil {
				o.AnnotationTime[i1] = &dtyp.Filetime{}
			}
			if err := o.AnnotationTime[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		return nil
	})
	_s_ftAnnotationTime := func(ptr interface{}) { o.AnnotationTime = *ptr.(*[]*dtyp.Filetime) }
	if err := w.ReadPointer(&o.AnnotationTime, _s_ftAnnotationTime, _ptr_ftAnnotationTime); err != nil {
		return err
	}
	_ptr_szUser := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.NumValues > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.NumValues)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.User", sizeInfo[0])
		}
		o.User = make([]string, sizeInfo[0])
		for i1 := range o.User {
			i1 := i1
			_ptr_szUser := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
				if err := ndr.ReadUTF16NString(ctx, w, &o.User[i1]); err != nil {
					return err
				}
				return nil
			})
			_s_szUser := func(ptr interface{}) { o.User[i1] = *ptr.(*string) }
			if err := w.ReadPointer(&o.User[i1], _s_szUser, _ptr_szUser); err != nil {
				return err
			}
		}
		return nil
	})
	_s_szUser := func(ptr interface{}) { o.User = *ptr.(*[]string) }
	if err := w.ReadPointer(&o.User, _s_szUser, _ptr_szUser); err != nil {
		return err
	}
	return nil
}

// ModifiedItem structure represents OPCHDA_MODIFIEDITEM RPC structure.
type ModifiedItem struct {
	Client           uint32           `idl:"name:hClient" json:"client"`
	Count            uint32           `idl:"name:dwCount" json:"count"`
	Timestamps       []*dtyp.Filetime `idl:"name:pftTimeStamps;size_is:(dwCount)" json:"timestamps"`
	Qualities        []uint32         `idl:"name:pdwQualities;size_is:(dwCount)" json:"qualities"`
	DataValues       []*oaut.Variant  `idl:"name:pvDataValues;size_is:(dwCount)" json:"data_values"`
	ModificationTime []*dtyp.Filetime `idl:"name:pftModificationTime;size_is:(dwCount)" json:"modification_time"`
	EditType         []EditType       `idl:"name:pEditType;size_is:(dwCount)" json:"edit_type"`
	User             []string         `idl:"name:szUser;size_is:(dwCount)" json:"user"`
}

func (o *ModifiedItem) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Timestamps != nil && o.Count == 0 {
		o.Count = uint32(len(o.Timestamps))
	}
	if o.Qualities != nil && o.Count == 0 {
		o.Count = uint32(len(o.Qualities))
	}
	if o.DataValues != nil && o.Count == 0 {
		o.Count = uint32(len(o.DataValues))
	}
	if o.ModificationTime != nil && o.Count == 0 {
		o.Count = uint32(len(o.ModificationTime))
	}
	if o.EditType != nil && o.Count == 0 {
		o.Count = uint32(len(o.EditType))
	}
	if o.User != nil && o.Count == 0 {
		o.Count = uint32(len(o.User))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}
func (o *ModifiedItem) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	if err := w.WriteAlign(9); err != nil {
		return err
	}
	if err := w.WriteData(o.Client); err != nil {
		return err
	}
	if err := w.WriteData(o.Count); err != nil {
		return err
	}
	if o.Timestamps != nil || o.Count > 0 {
		_ptr_pftTimeStamps := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.Count)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.Timestamps {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if o.Timestamps[i1] != nil {
					if err := o.Timestamps[i1].MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
			}
			for i1 := len(o.Timestamps); uint64(i1) < sizeInfo[0]; i1++ {
				if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.Timestamps, _ptr_pftTimeStamps); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	if o.Qualities != nil || o.Count > 0 {
		_ptr_pdwQualities := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.Count)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.Qualities {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if err := w.WriteData(o.Qualities[i1]); err != nil {
					return err
				}
			}
			for i1 := len(o.Qualities); uint64(i1) < sizeInfo[0]; i1++ {
				if err := w.WriteData(uint32(0)); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.Qualities, _ptr_pdwQualities); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	if o.DataValues != nil || o.Count > 0 {
		_ptr_pvDataValues := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.Count)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.DataValues {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if o.DataValues[i1] != nil {
					_ptr_pvDataValues := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
						if o.DataValues[i1] != nil {
							if err := o.DataValues[i1].MarshalNDR(ctx, w); err != nil {
								return err
							}
						} else {
							if err := (&oaut.Variant{}).MarshalNDR(ctx, w); err != nil {
								return err
							}
						}
						return nil
					})
					if err := w.WritePointer(&o.DataValues[i1], _ptr_pvDataValues); err != nil {
						return err
					}
				} else {
					if err := w.WritePointer(nil); err != nil {
						return err
					}
				}
			}
			for i1 := len(o.DataValues); uint64(i1) < sizeInfo[0]; i1++ {
				if err := w.WritePointer(nil); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.DataValues, _ptr_pvDataValues); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	if o.ModificationTime != nil || o.Count > 0 {
		_ptr_pftModificationTime := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.Count)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.ModificationTime {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if o.ModificationTime[i1] != nil {
					if err := o.ModificationTime[i1].MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
			}
			for i1 := len(o.ModificationTime); uint64(i1) < sizeInfo[0]; i1++ {
				if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.ModificationTime, _ptr_pftModificationTime); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	if o.EditType != nil || o.Count > 0 {
		_ptr_pEditType := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.Count)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.EditType {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if err := w.WriteEnum(uint16(o.EditType[i1])); err != nil {
					return err
				}
			}
			for i1 := len(o.EditType); uint64(i1) < sizeInfo[0]; i1++ {
				if err := w.WriteData(uint16(0)); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.EditType, _ptr_pEditType); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	if o.User != nil || o.Count > 0 {
		_ptr_szUser := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.Count)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.User {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if o.User[i1] != "" {
					_ptr_szUser := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
						if err := ndr.WriteUTF16String(ctx, w, o.User[i1]); err != nil {
							return err
						}
						return nil
					})
					if err := w.WritePointer(&o.User[i1], _ptr_szUser); err != nil {
						return err
					}
				} else {
					if err := w.WritePointer(nil); err != nil {
						return err
					}
				}
			}
			for i1 := len(o.User); uint64(i1) < sizeInfo[0]; i1++ {
				if err := w.WritePointer(nil); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.User, _ptr_szUser); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	return nil
}
func (o *ModifiedItem) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	if err := w.ReadAlign(9); err != nil {
		return err
	}
	if err := w.ReadData(&o.Client); err != nil {
		return err
	}
	if err := w.ReadData(&o.Count); err != nil {
		return err
	}
	_ptr_pftTimeStamps := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.Count > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.Count)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Timestamps", sizeInfo[0])
		}
		o.Timestamps = make([]*dtyp.Filetime, sizeInfo[0])
		for i1 := range o.Timestamps {
			i1 := i1
			if o.Timestamps[i1] == nil {
				o.Timestamps[i1] = &dtyp.Filetime{}
			}
			if err := o.Timestamps[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		return nil
	})
	_s_pftTimeStamps := func(ptr interface{}) { o.Timestamps = *ptr.(*[]*dtyp.Filetime) }
	if err := w.ReadPointer(&o.Timestamps, _s_pftTimeStamps, _ptr_pftTimeStamps); err != nil {
		return err
	}
	_ptr_pdwQualities := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.Count > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.Count)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Qualities", sizeInfo[0])
		}
		o.Qualities = make([]uint32, sizeInfo[0])
		for i1 := range o.Qualities {
			i1 := i1
			if err := w.ReadData(&o.Qualities[i1]); err != nil {
				return err
			}
		}
		return nil
	})
	_s_pdwQualities := func(ptr interface{}) { o.Qualities = *ptr.(*[]uint32) }
	if err := w.ReadPointer(&o.Qualities, _s_pdwQualities, _ptr_pdwQualities); err != nil {
		return err
	}
	_ptr_pvDataValues := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.Count > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.Count)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.DataValues", sizeInfo[0])
		}
		o.DataValues = make([]*oaut.Variant, sizeInfo[0])
		for i1 := range o.DataValues {
			i1 := i1
			_ptr_pvDataValues := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
				if o.DataValues[i1] == nil {
					o.DataValues[i1] = &oaut.Variant{}
				}
				if err := o.DataValues[i1].UnmarshalNDR(ctx, w); err != nil {
					return err
				}
				return nil
			})
			_s_pvDataValues := func(ptr interface{}) { o.DataValues[i1] = *ptr.(**oaut.Variant) }
			if err := w.ReadPointer(&o.DataValues[i1], _s_pvDataValues, _ptr_pvDataValues); err != nil {
				return err
			}
		}
		return nil
	})
	_s_pvDataValues := func(ptr interface{}) { o.DataValues = *ptr.(*[]*oaut.Variant) }
	if err := w.ReadPointer(&o.DataValues, _s_pvDataValues, _ptr_pvDataValues); err != nil {
		return err
	}
	_ptr_pftModificationTime := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.Count > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.Count)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.ModificationTime", sizeInfo[0])
		}
		o.ModificationTime = make([]*dtyp.Filetime, sizeInfo[0])
		for i1 := range o.ModificationTime {
			i1 := i1
			if o.ModificationTime[i1] == nil {
				o.ModificationTime[i1] = &dtyp.Filetime{}
			}
			if err := o.ModificationTime[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		return nil
	})
	_s_pftModificationTime := func(ptr interface{}) { o.ModificationTime = *ptr.(*[]*dtyp.Filetime) }
	if err := w.ReadPointer(&o.ModificationTime, _s_pftModificationTime, _ptr_pftModificationTime); err != nil {
		return err
	}
	_ptr_pEditType := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.Count > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.Count)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.EditType", sizeInfo[0])
		}
		o.EditType = make([]EditType, sizeInfo[0])
		for i1 := range o.EditType {
			i1 := i1
			if err := w.ReadEnum((*uint16)(&o.EditType[i1])); err != nil {
				return err
			}
		}
		return nil
	})
	_s_pEditType := func(ptr interface{}) { o.EditType = *ptr.(*[]EditType) }
	if err := w.ReadPointer(&o.EditType, _s_pEditType, _ptr_pEditType); err != nil {
		return err
	}
	_ptr_szUser := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.Count > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.Count)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.User", sizeInfo[0])
		}
		o.User = make([]string, sizeInfo[0])
		for i1 := range o.User {
			i1 := i1
			_ptr_szUser := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
				if err := ndr.ReadUTF16String(ctx, w, &o.User[i1]); err != nil {
					return err
				}
				return nil
			})
			_s_szUser := func(ptr interface{}) { o.User[i1] = *ptr.(*string) }
			if err := w.ReadPointer(&o.User[i1], _s_szUser, _ptr_szUser); err != nil {
				return err
			}
		}
		return nil
	})
	_s_szUser := func(ptr interface{}) { o.User = *ptr.(*[]string) }
	if err := w.ReadPointer(&o.User, _s_szUser, _ptr_szUser); err != nil {
		return err
	}
	return nil
}

// Attribute structure represents OPCHDA_ATTRIBUTE RPC structure.
type Attribute struct {
	Client          uint32           `idl:"name:hClient" json:"client"`
	NumValues       uint32           `idl:"name:dwNumValues" json:"num_values"`
	AttributeID     uint32           `idl:"name:dwAttributeID" json:"attribute_id"`
	Timestamps      []*dtyp.Filetime `idl:"name:ftTimeStamps;size_is:(dwNumValues)" json:"timestamps"`
	AttributeValues []*oaut.Variant  `idl:"name:vAttributeValues;size_is:(dwNumValues)" json:"attribute_values"`
}

func (o *Attribute) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Timestamps != nil && o.NumValues == 0 {
		o.NumValues = uint32(len(o.Timestamps))
	}
	if o.AttributeValues != nil && o.NumValues == 0 {
		o.NumValues = uint32(len(o.AttributeValues))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}
func (o *Attribute) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	if err := w.WriteAlign(9); err != nil {
		return err
	}
	if err := w.WriteData(o.Client); err != nil {
		return err
	}
	if err := w.WriteData(o.NumValues); err != nil {
		return err
	}
	if err := w.WriteData(o.AttributeID); err != nil {
		return err
	}
	if o.Timestamps != nil || o.NumValues > 0 {
		_ptr_ftTimeStamps := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.NumValues)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.Timestamps {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if o.Timestamps[i1] != nil {
					if err := o.Timestamps[i1].MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
			}
			for i1 := len(o.Timestamps); uint64(i1) < sizeInfo[0]; i1++ {
				if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.Timestamps, _ptr_ftTimeStamps); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	if o.AttributeValues != nil || o.NumValues > 0 {
		_ptr_vAttributeValues := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.NumValues)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.AttributeValues {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if o.AttributeValues[i1] != nil {
					_ptr_vAttributeValues := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
						if o.AttributeValues[i1] != nil {
							if err := o.AttributeValues[i1].MarshalNDR(ctx, w); err != nil {
								return err
							}
						} else {
							if err := (&oaut.Variant{}).MarshalNDR(ctx, w); err != nil {
								return err
							}
						}
						return nil
					})
					if err := w.WritePointer(&o.AttributeValues[i1], _ptr_vAttributeValues); err != nil {
						return err
					}
				} else {
					if err := w.WritePointer(nil); err != nil {
						return err
					}
				}
			}
			for i1 := len(o.AttributeValues); uint64(i1) < sizeInfo[0]; i1++ {
				if err := w.WritePointer(nil); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.AttributeValues, _ptr_vAttributeValues); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	return nil
}
func (o *Attribute) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	if err := w.ReadAlign(9); err != nil {
		return err
	}
	if err := w.ReadData(&o.Client); err != nil {
		return err
	}
	if err := w.ReadData(&o.NumValues); err != nil {
		return err
	}
	if err := w.ReadData(&o.AttributeID); err != nil {
		return err
	}
	_ptr_ftTimeStamps := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.NumValues > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.NumValues)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Timestamps", sizeInfo[0])
		}
		o.Timestamps = make([]*dtyp.Filetime, sizeInfo[0])
		for i1 := range o.Timestamps {
			i1 := i1
			if o.Timestamps[i1] == nil {
				o.Timestamps[i1] = &dtyp.Filetime{}
			}
			if err := o.Timestamps[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		return nil
	})
	_s_ftTimeStamps := func(ptr interface{}) { o.Timestamps = *ptr.(*[]*dtyp.Filetime) }
	if err := w.ReadPointer(&o.Timestamps, _s_ftTimeStamps, _ptr_ftTimeStamps); err != nil {
		return err
	}
	_ptr_vAttributeValues := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.NumValues > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.NumValues)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.AttributeValues", sizeInfo[0])
		}
		o.AttributeValues = make([]*oaut.Variant, sizeInfo[0])
		for i1 := range o.AttributeValues {
			i1 := i1
			_ptr_vAttributeValues := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
				if o.AttributeValues[i1] == nil {
					o.AttributeValues[i1] = &oaut.Variant{}
				}
				if err := o.AttributeValues[i1].UnmarshalNDR(ctx, w); err != nil {
					return err
				}
				return nil
			})
			_s_vAttributeValues := func(ptr interface{}) { o.AttributeValues[i1] = *ptr.(**oaut.Variant) }
			if err := w.ReadPointer(&o.AttributeValues[i1], _s_vAttributeValues, _ptr_vAttributeValues); err != nil {
				return err
			}
		}
		return nil
	})
	_s_vAttributeValues := func(ptr interface{}) { o.AttributeValues = *ptr.(*[]*oaut.Variant) }
	if err := w.ReadPointer(&o.AttributeValues, _s_vAttributeValues, _ptr_vAttributeValues); err != nil {
		return err
	}
	return nil
}

// Time structure represents OPCHDA_TIME RPC structure.
type Time struct {
	IsString   bool           `idl:"name:bString" json:"is_string"`
	StringTime string         `idl:"name:szTime;string" json:"string_time"`
	Time       *dtyp.Filetime `idl:"name:ftTime" json:"time"`
}

func (o *Time) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}
func (o *Time) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	if err := w.WriteAlign(9); err != nil {
		return err
	}
	if !o.IsString {
		if err := w.WriteData(int32(0)); err != nil {
			return err
		}
	} else {
		if err := w.WriteData(int32(1)); err != nil {
			return err
		}
	}
	if o.StringTime != "" {
		_ptr_szTime := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			if err := ndr.WriteUTF16NString(ctx, w, o.StringTime); err != nil {
				return err
			}
			return nil
		})
		if err := w.WritePointer(&o.StringTime, _ptr_szTime); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	if o.Time != nil {
		if err := o.Time.MarshalNDR(ctx, w); err != nil {
			return err
		}
	} else {
		if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
			return err
		}
	}
	if err := w.WriteTrailingGap(9); err != nil {
		return err
	}
	return nil
}
func (o *Time) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	if err := w.ReadAlign(9); err != nil {
		return err
	}
	var _bIsString int32
	if err := w.ReadData(&_bIsString); err != nil {
		return err
	}
	o.IsString = _bIsString != 0
	_ptr_szTime := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		if err := ndr.ReadUTF16NString(ctx, w, &o.StringTime); err != nil {
			return err
		}
		return nil
	})
	_s_szTime := func(ptr interface{}) { o.StringTime = *ptr.(*string) }
	if err := w.ReadPointer(&o.StringTime, _s_szTime, _ptr_szTime); err != nil {
		return err
	}
	if o.Time == nil {
		o.Time = &dtyp.Filetime{}
	}
	if err := o.Time.UnmarshalNDR(ctx, w); err != nil {
		return err
	}
	if err := w.ReadTrailingGap(9); err != nil {
		return err
	}
	return nil
}

// Item structure represents OPCHDA_ITEM RPC structure.
type Item struct {
	Client     uint32           `idl:"name:hClient" json:"client"`
	Aggregate  uint32           `idl:"name:haAggregate" json:"aggregate"`
	Count      uint32           `idl:"name:dwCount" json:"count"`
	Timestamps []*dtyp.Filetime `idl:"name:pftTimeStamps;size_is:(dwCount)" json:"timestamps"`
	Qualities  []uint32         `idl:"name:pdwQualities;size_is:(dwCount)" json:"qualities"`
	DataValues []*oaut.Variant  `idl:"name:pvDataValues;size_is:(dwCount)" json:"data_values"`
}

func (o *Item) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Timestamps != nil && o.Count == 0 {
		o.Count = uint32(len(o.Timestamps))
	}
	if o.Qualities != nil && o.Count == 0 {
		o.Count = uint32(len(o.Qualities))
	}
	if o.DataValues != nil && o.Count == 0 {
		o.Count = uint32(len(o.DataValues))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}
func (o *Item) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	if err := w.WriteAlign(9); err != nil {
		return err
	}
	if err := w.WriteData(o.Client); err != nil {
		return err
	}
	if err := w.WriteData(o.Aggregate); err != nil {
		return err
	}
	if err := w.WriteData(o.Count); err != nil {
		return err
	}
	if o.Timestamps != nil || o.Count > 0 {
		_ptr_pftTimeStamps := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.Count)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.Timestamps {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if o.Timestamps[i1] != nil {
					if err := o.Timestamps[i1].MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
			}
			for i1 := len(o.Timestamps); uint64(i1) < sizeInfo[0]; i1++ {
				if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.Timestamps, _ptr_pftTimeStamps); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	if o.Qualities != nil || o.Count > 0 {
		_ptr_pdwQualities := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.Count)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.Qualities {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if err := w.WriteData(o.Qualities[i1]); err != nil {
					return err
				}
			}
			for i1 := len(o.Qualities); uint64(i1) < sizeInfo[0]; i1++ {
				if err := w.WriteData(uint32(0)); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.Qualities, _ptr_pdwQualities); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	if o.DataValues != nil || o.Count > 0 {
		_ptr_pvDataValues := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
			dimSize1 := uint64(o.Count)
			if err := w.WriteSize(dimSize1); err != nil {
				return err
			}
			sizeInfo := []uint64{
				dimSize1,
			}
			for i1 := range o.DataValues {
				i1 := i1
				if uint64(i1) >= sizeInfo[0] {
					break
				}
				if o.DataValues[i1] != nil {
					_ptr_pvDataValues := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
						if o.DataValues[i1] != nil {
							if err := o.DataValues[i1].MarshalNDR(ctx, w); err != nil {
								return err
							}
						} else {
							if err := (&oaut.Variant{}).MarshalNDR(ctx, w); err != nil {
								return err
							}
						}
						return nil
					})
					if err := w.WritePointer(&o.DataValues[i1], _ptr_pvDataValues); err != nil {
						return err
					}
				} else {
					if err := w.WritePointer(nil); err != nil {
						return err
					}
				}
			}
			for i1 := len(o.DataValues); uint64(i1) < sizeInfo[0]; i1++ {
				if err := w.WritePointer(nil); err != nil {
					return err
				}
			}
			return nil
		})
		if err := w.WritePointer(&o.DataValues, _ptr_pvDataValues); err != nil {
			return err
		}
	} else {
		if err := w.WritePointer(nil); err != nil {
			return err
		}
	}
	return nil
}
func (o *Item) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	if err := w.ReadAlign(9); err != nil {
		return err
	}
	if err := w.ReadData(&o.Client); err != nil {
		return err
	}
	if err := w.ReadData(&o.Aggregate); err != nil {
		return err
	}
	if err := w.ReadData(&o.Count); err != nil {
		return err
	}
	_ptr_pftTimeStamps := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.Count > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.Count)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Timestamps", sizeInfo[0])
		}
		o.Timestamps = make([]*dtyp.Filetime, sizeInfo[0])
		for i1 := range o.Timestamps {
			i1 := i1
			if o.Timestamps[i1] == nil {
				o.Timestamps[i1] = &dtyp.Filetime{}
			}
			if err := o.Timestamps[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		return nil
	})
	_s_pftTimeStamps := func(ptr interface{}) { o.Timestamps = *ptr.(*[]*dtyp.Filetime) }
	if err := w.ReadPointer(&o.Timestamps, _s_pftTimeStamps, _ptr_pftTimeStamps); err != nil {
		return err
	}
	_ptr_pdwQualities := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.Count > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.Count)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Qualities", sizeInfo[0])
		}
		o.Qualities = make([]uint32, sizeInfo[0])
		for i1 := range o.Qualities {
			i1 := i1
			if err := w.ReadData(&o.Qualities[i1]); err != nil {
				return err
			}
		}
		return nil
	})
	_s_pdwQualities := func(ptr interface{}) { o.Qualities = *ptr.(*[]uint32) }
	if err := w.ReadPointer(&o.Qualities, _s_pdwQualities, _ptr_pdwQualities); err != nil {
		return err
	}
	_ptr_pvDataValues := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		// XXX: for opaque unmarshaling
		if o.Count > 0 && sizeInfo[0] == 0 {
			sizeInfo[0] = uint64(o.Count)
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.DataValues", sizeInfo[0])
		}
		o.DataValues = make([]*oaut.Variant, sizeInfo[0])
		for i1 := range o.DataValues {
			i1 := i1
			_ptr_pvDataValues := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
				if o.DataValues[i1] == nil {
					o.DataValues[i1] = &oaut.Variant{}
				}
				if err := o.DataValues[i1].UnmarshalNDR(ctx, w); err != nil {
					return err
				}
				return nil
			})
			_s_pvDataValues := func(ptr interface{}) { o.DataValues[i1] = *ptr.(**oaut.Variant) }
			if err := w.ReadPointer(&o.DataValues[i1], _s_pvDataValues, _ptr_pvDataValues); err != nil {
				return err
			}
		}
		return nil
	})
	_s_pvDataValues := func(ptr interface{}) { o.DataValues = *ptr.(*[]*oaut.Variant) }
	if err := w.ReadPointer(&o.DataValues, _s_pvDataValues, _ptr_pvDataValues); err != nil {
		return err
	}
	return nil
}

// SyncUpdate structure represents IOPCHDA_SyncUpdate RPC structure.
type SyncUpdate dcom.InterfacePointer

func (o *SyncUpdate) InterfacePointer() *dcom.InterfacePointer { return (*dcom.InterfacePointer)(o) }

func (o *SyncUpdate) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Data != nil && o.DataCount == 0 {
		o.DataCount = uint32(len(o.Data))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}

func (o *SyncUpdate) NDRSizeInfo() []uint64 {
	dimSize1 := uint64(o.DataCount)
	return []uint64{
		dimSize1,
	}
}
func (o *SyncUpdate) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for sz1 := range sizeInfo {
			if err := w.WriteSize(sizeInfo[sz1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.WriteAlign(4); err != nil {
		return err
	}
	if err := w.WriteData(o.DataCount); err != nil {
		return err
	}
	for i1 := range o.Data {
		i1 := i1
		if uint64(i1) >= sizeInfo[0] {
			break
		}
		if err := w.WriteData(o.Data[i1]); err != nil {
			return err
		}
	}
	for i1 := len(o.Data); uint64(i1) < sizeInfo[0]; i1++ {
		if err := w.WriteData(uint8(0)); err != nil {
			return err
		}
	}
	return nil
}
func (o *SyncUpdate) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for i1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[i1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.ReadAlign(4); err != nil {
		return err
	}
	if err := w.ReadData(&o.DataCount); err != nil {
		return err
	}
	// XXX: for opaque unmarshaling
	if o.DataCount > 0 && sizeInfo[0] == 0 {
		sizeInfo[0] = uint64(o.DataCount)
	}
	if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
		return fmt.Errorf("buffer overflow for size %d of array o.Data", sizeInfo[0])
	}
	o.Data = make([]byte, sizeInfo[0])
	for i1 := range o.Data {
		i1 := i1
		if err := w.ReadData(&o.Data[i1]); err != nil {
			return err
		}
	}
	return nil
}

// CategoryIDOPCHDAServer10 structure represents CATID_OPCHDAServer10 RPC structure.
type CategoryIDOPCHDAServer10 dcom.InterfacePointer

func (o *CategoryIDOPCHDAServer10) InterfacePointer() *dcom.InterfacePointer {
	return (*dcom.InterfacePointer)(o)
}

func (o *CategoryIDOPCHDAServer10) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Data != nil && o.DataCount == 0 {
		o.DataCount = uint32(len(o.Data))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}

func (o *CategoryIDOPCHDAServer10) NDRSizeInfo() []uint64 {
	dimSize1 := uint64(o.DataCount)
	return []uint64{
		dimSize1,
	}
}
func (o *CategoryIDOPCHDAServer10) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for sz1 := range sizeInfo {
			if err := w.WriteSize(sizeInfo[sz1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.WriteAlign(4); err != nil {
		return err
	}
	if err := w.WriteData(o.DataCount); err != nil {
		return err
	}
	for i1 := range o.Data {
		i1 := i1
		if uint64(i1) >= sizeInfo[0] {
			break
		}
		if err := w.WriteData(o.Data[i1]); err != nil {
			return err
		}
	}
	for i1 := len(o.Data); uint64(i1) < sizeInfo[0]; i1++ {
		if err := w.WriteData(uint8(0)); err != nil {
			return err
		}
	}
	return nil
}
func (o *CategoryIDOPCHDAServer10) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for i1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[i1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.ReadAlign(4); err != nil {
		return err
	}
	if err := w.ReadData(&o.DataCount); err != nil {
		return err
	}
	// XXX: for opaque unmarshaling
	if o.DataCount > 0 && sizeInfo[0] == 0 {
		sizeInfo[0] = uint64(o.DataCount)
	}
	if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
		return fmt.Errorf("buffer overflow for size %d of array o.Data", sizeInfo[0])
	}
	o.Data = make([]byte, sizeInfo[0])
	for i1 := range o.Data {
		i1 := i1
		if err := w.ReadData(&o.Data[i1]); err != nil {
			return err
		}
	}
	return nil
}

// SyncRead structure represents IOPCHDA_SyncRead RPC structure.
type SyncRead dcom.InterfacePointer

func (o *SyncRead) InterfacePointer() *dcom.InterfacePointer { return (*dcom.InterfacePointer)(o) }

func (o *SyncRead) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Data != nil && o.DataCount == 0 {
		o.DataCount = uint32(len(o.Data))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}

func (o *SyncRead) NDRSizeInfo() []uint64 {
	dimSize1 := uint64(o.DataCount)
	return []uint64{
		dimSize1,
	}
}
func (o *SyncRead) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for sz1 := range sizeInfo {
			if err := w.WriteSize(sizeInfo[sz1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.WriteAlign(4); err != nil {
		return err
	}
	if err := w.WriteData(o.DataCount); err != nil {
		return err
	}
	for i1 := range o.Data {
		i1 := i1
		if uint64(i1) >= sizeInfo[0] {
			break
		}
		if err := w.WriteData(o.Data[i1]); err != nil {
			return err
		}
	}
	for i1 := len(o.Data); uint64(i1) < sizeInfo[0]; i1++ {
		if err := w.WriteData(uint8(0)); err != nil {
			return err
		}
	}
	return nil
}
func (o *SyncRead) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for i1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[i1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.ReadAlign(4); err != nil {
		return err
	}
	if err := w.ReadData(&o.DataCount); err != nil {
		return err
	}
	// XXX: for opaque unmarshaling
	if o.DataCount > 0 && sizeInfo[0] == 0 {
		sizeInfo[0] = uint64(o.DataCount)
	}
	if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
		return fmt.Errorf("buffer overflow for size %d of array o.Data", sizeInfo[0])
	}
	o.Data = make([]byte, sizeInfo[0])
	for i1 := range o.Data {
		i1 := i1
		if err := w.ReadData(&o.Data[i1]); err != nil {
			return err
		}
	}
	return nil
}

// SyncAnnotations structure represents IOPCHDA_SyncAnnotations RPC structure.
type SyncAnnotations dcom.InterfacePointer

func (o *SyncAnnotations) InterfacePointer() *dcom.InterfacePointer {
	return (*dcom.InterfacePointer)(o)
}

func (o *SyncAnnotations) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Data != nil && o.DataCount == 0 {
		o.DataCount = uint32(len(o.Data))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}

func (o *SyncAnnotations) NDRSizeInfo() []uint64 {
	dimSize1 := uint64(o.DataCount)
	return []uint64{
		dimSize1,
	}
}
func (o *SyncAnnotations) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for sz1 := range sizeInfo {
			if err := w.WriteSize(sizeInfo[sz1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.WriteAlign(4); err != nil {
		return err
	}
	if err := w.WriteData(o.DataCount); err != nil {
		return err
	}
	for i1 := range o.Data {
		i1 := i1
		if uint64(i1) >= sizeInfo[0] {
			break
		}
		if err := w.WriteData(o.Data[i1]); err != nil {
			return err
		}
	}
	for i1 := len(o.Data); uint64(i1) < sizeInfo[0]; i1++ {
		if err := w.WriteData(uint8(0)); err != nil {
			return err
		}
	}
	return nil
}
func (o *SyncAnnotations) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for i1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[i1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.ReadAlign(4); err != nil {
		return err
	}
	if err := w.ReadData(&o.DataCount); err != nil {
		return err
	}
	// XXX: for opaque unmarshaling
	if o.DataCount > 0 && sizeInfo[0] == 0 {
		sizeInfo[0] = uint64(o.DataCount)
	}
	if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
		return fmt.Errorf("buffer overflow for size %d of array o.Data", sizeInfo[0])
	}
	o.Data = make([]byte, sizeInfo[0])
	for i1 := range o.Data {
		i1 := i1
		if err := w.ReadData(&o.Data[i1]); err != nil {
			return err
		}
	}
	return nil
}

// AsyncUpdate structure represents IOPCHDA_AsyncUpdate RPC structure.
type AsyncUpdate dcom.InterfacePointer

func (o *AsyncUpdate) InterfacePointer() *dcom.InterfacePointer { return (*dcom.InterfacePointer)(o) }

func (o *AsyncUpdate) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Data != nil && o.DataCount == 0 {
		o.DataCount = uint32(len(o.Data))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}

func (o *AsyncUpdate) NDRSizeInfo() []uint64 {
	dimSize1 := uint64(o.DataCount)
	return []uint64{
		dimSize1,
	}
}
func (o *AsyncUpdate) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for sz1 := range sizeInfo {
			if err := w.WriteSize(sizeInfo[sz1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.WriteAlign(4); err != nil {
		return err
	}
	if err := w.WriteData(o.DataCount); err != nil {
		return err
	}
	for i1 := range o.Data {
		i1 := i1
		if uint64(i1) >= sizeInfo[0] {
			break
		}
		if err := w.WriteData(o.Data[i1]); err != nil {
			return err
		}
	}
	for i1 := len(o.Data); uint64(i1) < sizeInfo[0]; i1++ {
		if err := w.WriteData(uint8(0)); err != nil {
			return err
		}
	}
	return nil
}
func (o *AsyncUpdate) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for i1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[i1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.ReadAlign(4); err != nil {
		return err
	}
	if err := w.ReadData(&o.DataCount); err != nil {
		return err
	}
	// XXX: for opaque unmarshaling
	if o.DataCount > 0 && sizeInfo[0] == 0 {
		sizeInfo[0] = uint64(o.DataCount)
	}
	if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
		return fmt.Errorf("buffer overflow for size %d of array o.Data", sizeInfo[0])
	}
	o.Data = make([]byte, sizeInfo[0])
	for i1 := range o.Data {
		i1 := i1
		if err := w.ReadData(&o.Data[i1]); err != nil {
			return err
		}
	}
	return nil
}

// AsyncAnnotations structure represents IOPCHDA_AsyncAnnotations RPC structure.
type AsyncAnnotations dcom.InterfacePointer

func (o *AsyncAnnotations) InterfacePointer() *dcom.InterfacePointer {
	return (*dcom.InterfacePointer)(o)
}

func (o *AsyncAnnotations) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Data != nil && o.DataCount == 0 {
		o.DataCount = uint32(len(o.Data))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}

func (o *AsyncAnnotations) NDRSizeInfo() []uint64 {
	dimSize1 := uint64(o.DataCount)
	return []uint64{
		dimSize1,
	}
}
func (o *AsyncAnnotations) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for sz1 := range sizeInfo {
			if err := w.WriteSize(sizeInfo[sz1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.WriteAlign(4); err != nil {
		return err
	}
	if err := w.WriteData(o.DataCount); err != nil {
		return err
	}
	for i1 := range o.Data {
		i1 := i1
		if uint64(i1) >= sizeInfo[0] {
			break
		}
		if err := w.WriteData(o.Data[i1]); err != nil {
			return err
		}
	}
	for i1 := len(o.Data); uint64(i1) < sizeInfo[0]; i1++ {
		if err := w.WriteData(uint8(0)); err != nil {
			return err
		}
	}
	return nil
}
func (o *AsyncAnnotations) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for i1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[i1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.ReadAlign(4); err != nil {
		return err
	}
	if err := w.ReadData(&o.DataCount); err != nil {
		return err
	}
	// XXX: for opaque unmarshaling
	if o.DataCount > 0 && sizeInfo[0] == 0 {
		sizeInfo[0] = uint64(o.DataCount)
	}
	if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
		return fmt.Errorf("buffer overflow for size %d of array o.Data", sizeInfo[0])
	}
	o.Data = make([]byte, sizeInfo[0])
	for i1 := range o.Data {
		i1 := i1
		if err := w.ReadData(&o.Data[i1]); err != nil {
			return err
		}
	}
	return nil
}

// DataCallback structure represents IOPCHDA_DataCallback RPC structure.
type DataCallback dcom.InterfacePointer

func (o *DataCallback) InterfacePointer() *dcom.InterfacePointer { return (*dcom.InterfacePointer)(o) }

func (o *DataCallback) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Data != nil && o.DataCount == 0 {
		o.DataCount = uint32(len(o.Data))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}

func (o *DataCallback) NDRSizeInfo() []uint64 {
	dimSize1 := uint64(o.DataCount)
	return []uint64{
		dimSize1,
	}
}
func (o *DataCallback) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for sz1 := range sizeInfo {
			if err := w.WriteSize(sizeInfo[sz1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.WriteAlign(4); err != nil {
		return err
	}
	if err := w.WriteData(o.DataCount); err != nil {
		return err
	}
	for i1 := range o.Data {
		i1 := i1
		if uint64(i1) >= sizeInfo[0] {
			break
		}
		if err := w.WriteData(o.Data[i1]); err != nil {
			return err
		}
	}
	for i1 := len(o.Data); uint64(i1) < sizeInfo[0]; i1++ {
		if err := w.WriteData(uint8(0)); err != nil {
			return err
		}
	}
	return nil
}
func (o *DataCallback) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for i1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[i1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.ReadAlign(4); err != nil {
		return err
	}
	if err := w.ReadData(&o.DataCount); err != nil {
		return err
	}
	// XXX: for opaque unmarshaling
	if o.DataCount > 0 && sizeInfo[0] == 0 {
		sizeInfo[0] = uint64(o.DataCount)
	}
	if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
		return fmt.Errorf("buffer overflow for size %d of array o.Data", sizeInfo[0])
	}
	o.Data = make([]byte, sizeInfo[0])
	for i1 := range o.Data {
		i1 := i1
		if err := w.ReadData(&o.Data[i1]); err != nil {
			return err
		}
	}
	return nil
}

// Browser structure represents IOPCHDA_Browser RPC structure.
type Browser dcom.InterfacePointer

func (o *Browser) InterfacePointer() *dcom.InterfacePointer { return (*dcom.InterfacePointer)(o) }

func (o *Browser) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Data != nil && o.DataCount == 0 {
		o.DataCount = uint32(len(o.Data))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}

func (o *Browser) NDRSizeInfo() []uint64 {
	dimSize1 := uint64(o.DataCount)
	return []uint64{
		dimSize1,
	}
}
func (o *Browser) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for sz1 := range sizeInfo {
			if err := w.WriteSize(sizeInfo[sz1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.WriteAlign(4); err != nil {
		return err
	}
	if err := w.WriteData(o.DataCount); err != nil {
		return err
	}
	for i1 := range o.Data {
		i1 := i1
		if uint64(i1) >= sizeInfo[0] {
			break
		}
		if err := w.WriteData(o.Data[i1]); err != nil {
			return err
		}
	}
	for i1 := len(o.Data); uint64(i1) < sizeInfo[0]; i1++ {
		if err := w.WriteData(uint8(0)); err != nil {
			return err
		}
	}
	return nil
}
func (o *Browser) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for i1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[i1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.ReadAlign(4); err != nil {
		return err
	}
	if err := w.ReadData(&o.DataCount); err != nil {
		return err
	}
	// XXX: for opaque unmarshaling
	if o.DataCount > 0 && sizeInfo[0] == 0 {
		sizeInfo[0] = uint64(o.DataCount)
	}
	if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
		return fmt.Errorf("buffer overflow for size %d of array o.Data", sizeInfo[0])
	}
	o.Data = make([]byte, sizeInfo[0])
	for i1 := range o.Data {
		i1 := i1
		if err := w.ReadData(&o.Data[i1]); err != nil {
			return err
		}
	}
	return nil
}

// Playback structure represents IOPCHDA_Playback RPC structure.
type Playback dcom.InterfacePointer

func (o *Playback) InterfacePointer() *dcom.InterfacePointer { return (*dcom.InterfacePointer)(o) }

func (o *Playback) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Data != nil && o.DataCount == 0 {
		o.DataCount = uint32(len(o.Data))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}

func (o *Playback) NDRSizeInfo() []uint64 {
	dimSize1 := uint64(o.DataCount)
	return []uint64{
		dimSize1,
	}
}
func (o *Playback) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for sz1 := range sizeInfo {
			if err := w.WriteSize(sizeInfo[sz1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.WriteAlign(4); err != nil {
		return err
	}
	if err := w.WriteData(o.DataCount); err != nil {
		return err
	}
	for i1 := range o.Data {
		i1 := i1
		if uint64(i1) >= sizeInfo[0] {
			break
		}
		if err := w.WriteData(o.Data[i1]); err != nil {
			return err
		}
	}
	for i1 := len(o.Data); uint64(i1) < sizeInfo[0]; i1++ {
		if err := w.WriteData(uint8(0)); err != nil {
			return err
		}
	}
	return nil
}
func (o *Playback) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for i1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[i1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.ReadAlign(4); err != nil {
		return err
	}
	if err := w.ReadData(&o.DataCount); err != nil {
		return err
	}
	// XXX: for opaque unmarshaling
	if o.DataCount > 0 && sizeInfo[0] == 0 {
		sizeInfo[0] = uint64(o.DataCount)
	}
	if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
		return fmt.Errorf("buffer overflow for size %d of array o.Data", sizeInfo[0])
	}
	o.Data = make([]byte, sizeInfo[0])
	for i1 := range o.Data {
		i1 := i1
		if err := w.ReadData(&o.Data[i1]); err != nil {
			return err
		}
	}
	return nil
}

// AsyncRead structure represents IOPCHDA_AsyncRead RPC structure.
type AsyncRead dcom.InterfacePointer

func (o *AsyncRead) InterfacePointer() *dcom.InterfacePointer { return (*dcom.InterfacePointer)(o) }

func (o *AsyncRead) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Data != nil && o.DataCount == 0 {
		o.DataCount = uint32(len(o.Data))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}

func (o *AsyncRead) NDRSizeInfo() []uint64 {
	dimSize1 := uint64(o.DataCount)
	return []uint64{
		dimSize1,
	}
}
func (o *AsyncRead) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for sz1 := range sizeInfo {
			if err := w.WriteSize(sizeInfo[sz1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.WriteAlign(4); err != nil {
		return err
	}
	if err := w.WriteData(o.DataCount); err != nil {
		return err
	}
	for i1 := range o.Data {
		i1 := i1
		if uint64(i1) >= sizeInfo[0] {
			break
		}
		if err := w.WriteData(o.Data[i1]); err != nil {
			return err
		}
	}
	for i1 := len(o.Data); uint64(i1) < sizeInfo[0]; i1++ {
		if err := w.WriteData(uint8(0)); err != nil {
			return err
		}
	}
	return nil
}
func (o *AsyncRead) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for i1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[i1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.ReadAlign(4); err != nil {
		return err
	}
	if err := w.ReadData(&o.DataCount); err != nil {
		return err
	}
	// XXX: for opaque unmarshaling
	if o.DataCount > 0 && sizeInfo[0] == 0 {
		sizeInfo[0] = uint64(o.DataCount)
	}
	if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
		return fmt.Errorf("buffer overflow for size %d of array o.Data", sizeInfo[0])
	}
	o.Data = make([]byte, sizeInfo[0])
	for i1 := range o.Data {
		i1 := i1
		if err := w.ReadData(&o.Data[i1]); err != nil {
			return err
		}
	}
	return nil
}

// Server structure represents IOPCHDA_Server RPC structure.
type Server dcom.InterfacePointer

func (o *Server) InterfacePointer() *dcom.InterfacePointer { return (*dcom.InterfacePointer)(o) }

func (o *Server) xxx_PreparePayload(ctx context.Context) error {
	if err := ndr.BeforePreparePayload(ctx, o); err != nil {
		return err
	}
	if o.Data != nil && o.DataCount == 0 {
		o.DataCount = uint32(len(o.Data))
	}
	if err := ndr.AfterPreparePayload(ctx, o); err != nil {
		return err
	}
	return nil
}

func (o *Server) NDRSizeInfo() []uint64 {
	dimSize1 := uint64(o.DataCount)
	return []uint64{
		dimSize1,
	}
}
func (o *Server) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PreparePayload(ctx); err != nil {
		return err
	}
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for sz1 := range sizeInfo {
			if err := w.WriteSize(sizeInfo[sz1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.WriteAlign(4); err != nil {
		return err
	}
	if err := w.WriteData(o.DataCount); err != nil {
		return err
	}
	for i1 := range o.Data {
		i1 := i1
		if uint64(i1) >= sizeInfo[0] {
			break
		}
		if err := w.WriteData(o.Data[i1]); err != nil {
			return err
		}
	}
	for i1 := len(o.Data); uint64(i1) < sizeInfo[0]; i1++ {
		if err := w.WriteData(uint8(0)); err != nil {
			return err
		}
	}
	return nil
}
func (o *Server) UnmarshalNDR(ctx context.Context, w ndr.Reader) error {
	sizeInfo, ok := ctx.Value(ndr.SizeInfo).([]uint64)
	if !ok {
		sizeInfo = o.NDRSizeInfo()
		for i1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[i1]); err != nil {
				return err
			}
		}
		ctx = context.WithValue(ctx, ndr.SizeInfo, sizeInfo)
	}
	if err := w.ReadAlign(4); err != nil {
		return err
	}
	if err := w.ReadData(&o.DataCount); err != nil {
		return err
	}
	// XXX: for opaque unmarshaling
	if o.DataCount > 0 && sizeInfo[0] == 0 {
		sizeInfo[0] = uint64(o.DataCount)
	}
	if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
		return fmt.Errorf("buffer overflow for size %d of array o.Data", sizeInfo[0])
	}
	o.Data = make([]byte, sizeInfo[0])
	for i1 := range o.Data {
		i1 := i1
		if err := w.ReadData(&o.Data[i1]); err != nil {
			return err
		}
	}
	return nil
}
