// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package opceventservercatid

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = iunknown.GoPackage
)

// OPCEventServerCATID server interface.
type EventServerCategoryIDServer interface {

	// IUnknown base class.
	iunknown.UnknownServer
}

func RegisterEventServerCategoryIDServer(conn dcerpc.Conn, o EventServerCategoryIDServer, opts ...dcerpc.Option) {
	conn.RegisterServer(NewEventServerCategoryIDServerHandle(o), append(opts, dcerpc.WithAbstractSyntax(EventServerCategoryIDSyntaxV0_0))...)
}

func NewEventServerCategoryIDServerHandle(o EventServerCategoryIDServer) dcerpc.ServerHandle {
	return func(ctx context.Context, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
		return EventServerCategoryIDServerHandle(ctx, o, opNum, r)
	}
}

func EventServerCategoryIDServerHandle(ctx context.Context, o EventServerCategoryIDServer, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
	switch opNum {
	}
	return nil, nil
}

// Unimplemented OPCEventServerCATID
type UnimplementedEventServerCategoryIDServer struct {
	iunknown.UnimplementedUnknownServer
}

var _ EventServerCategoryIDServer = (*UnimplementedEventServerCategoryIDServer)(nil)
