// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package opceventservercatid

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom.GoPackage
	_ = iunknown.GoPackage
)

var (
	// import guard
	GoPackage = "opcae"
)

var (
	// OPCEventServerCATID interface identifier 58e13251-ac87-11d1-84d5-00608cb8a7e9
	EventServerCategoryIDIID = &dcom.IID{Data1: 0x58e13251, Data2: 0xac87, Data3: 0x11d1, Data4: []byte{0x84, 0xd5, 0x00, 0x60, 0x8c, 0xb8, 0xa7, 0xe9}}
	// Syntax UUID
	EventServerCategoryIDSyntaxUUID = &uuid.UUID{TimeLow: 0x58e13251, TimeMid: 0xac87, TimeHiAndVersion: 0x11d1, ClockSeqHiAndReserved: 0x84, ClockSeqLow: 0xd5, Node: [6]uint8{0x0, 0x60, 0x8c, 0xb8, 0xa7, 0xe9}}
	// Syntax ID
	EventServerCategoryIDSyntaxV0_0 = &dcerpc.SyntaxID{IfUUID: EventServerCategoryIDSyntaxUUID, IfVersionMajor: 0, IfVersionMinor: 0}
)

// OPCEventServerCATID interface.
type EventServerCategoryIDClient interface {

	// IUnknown retrieval method.
	Unknown() iunknown.UnknownClient

	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn

	// IPID sets the object interface identifier.
	IPID(context.Context, *dcom.IPID) EventServerCategoryIDClient
}

type xxx_DefaultEventServerCategoryIDClient struct {
	iunknown.UnknownClient
	cc   dcerpc.Conn
	ipid *dcom.IPID
}

func (o *xxx_DefaultEventServerCategoryIDClient) Unknown() iunknown.UnknownClient {
	return o.UnknownClient
}

func (o *xxx_DefaultEventServerCategoryIDClient) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultEventServerCategoryIDClient) Conn() dcerpc.Conn {
	return o.cc
}

func (o *xxx_DefaultEventServerCategoryIDClient) IPID(ctx context.Context, ipid *dcom.IPID) EventServerCategoryIDClient {
	if ipid == nil {
		ipid = &dcom.IPID{}
	}
	return &xxx_DefaultEventServerCategoryIDClient{
		UnknownClient: o.UnknownClient.IPID(ctx, ipid),
		cc:            o.cc,
		ipid:          ipid,
	}
}

func NewEventServerCategoryIDClient(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (EventServerCategoryIDClient, error) {
	var err error
	if !dcom.IsSuperclass(opts) {
		cc, err = cc.Bind(ctx, append(opts, dcerpc.WithAbstractSyntax(EventServerCategoryIDSyntaxV0_0))...)
		if err != nil {
			return nil, err
		}
	}
	base, err := iunknown.NewUnknownClient(ctx, cc, append(opts, dcom.Superclass(cc))...)
	if err != nil {
		return nil, err
	}
	ipid, ok := dcom.HasIPID(opts)
	if ok {
		base = base.IPID(ctx, ipid)
	}
	return &xxx_DefaultEventServerCategoryIDClient{
		UnknownClient: base,
		cc:            cc,
		ipid:          ipid,
	}, nil
}
