// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopchda_asyncupdate

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = iunknown.GoPackage
)

// IOPCHDA_AsyncUpdate server interface.
type AsyncUpdateServer interface {

	// IUnknown base class.
	iunknown.UnknownServer

	// QueryCapabilities operation.
	QueryCapabilities(context.Context, *QueryCapabilitiesRequest) (*QueryCapabilitiesResponse, error)

	// Insert operation.
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)

	// Replace operation.
	Replace(context.Context, *ReplaceRequest) (*ReplaceResponse, error)

	// InsertReplace operation.
	InsertReplace(context.Context, *InsertReplaceRequest) (*InsertReplaceResponse, error)

	// DeleteRaw operation.
	DeleteRaw(context.Context, *DeleteRawRequest) (*DeleteRawResponse, error)

	// DeleteAtTime operation.
	DeleteAtTime(context.Context, *DeleteAtTimeRequest) (*DeleteAtTimeResponse, error)

	// Cancel operation.
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
}

func RegisterAsyncUpdateServer(conn dcerpc.Conn, o AsyncUpdateServer, opts ...dcerpc.Option) {
	conn.RegisterServer(NewAsyncUpdateServerHandle(o), append(opts, dcerpc.WithAbstractSyntax(AsyncUpdateSyntaxV0_0))...)
}

func NewAsyncUpdateServerHandle(o AsyncUpdateServer) dcerpc.ServerHandle {
	return func(ctx context.Context, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
		return AsyncUpdateServerHandle(ctx, o, opNum, r)
	}
}

func AsyncUpdateServerHandle(ctx context.Context, o AsyncUpdateServer, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
	if opNum < 3 {
		// IUnknown base method.
		return iunknown.UnknownServerHandle(ctx, o, opNum, r)
	}
	switch opNum {
	case 3: // QueryCapabilities
		op := &xxx_QueryCapabilitiesOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &QueryCapabilitiesRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.QueryCapabilities(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 4: // Insert
		op := &xxx_InsertOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &InsertRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.Insert(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 5: // Replace
		op := &xxx_ReplaceOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &ReplaceRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.Replace(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 6: // InsertReplace
		op := &xxx_InsertReplaceOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &InsertReplaceRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.InsertReplace(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 7: // DeleteRaw
		op := &xxx_DeleteRawOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &DeleteRawRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.DeleteRaw(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 8: // DeleteAtTime
		op := &xxx_DeleteAtTimeOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &DeleteAtTimeRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.DeleteAtTime(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 9: // Cancel
		op := &xxx_CancelOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &CancelRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.Cancel(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	}
	return nil, nil
}

// Unimplemented IOPCHDA_AsyncUpdate
type UnimplementedAsyncUpdateServer struct {
	iunknown.UnimplementedUnknownServer
}

func (UnimplementedAsyncUpdateServer) QueryCapabilities(context.Context, *QueryCapabilitiesRequest) (*QueryCapabilitiesResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedAsyncUpdateServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedAsyncUpdateServer) Replace(context.Context, *ReplaceRequest) (*ReplaceResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedAsyncUpdateServer) InsertReplace(context.Context, *InsertReplaceRequest) (*InsertReplaceResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedAsyncUpdateServer) DeleteRaw(context.Context, *DeleteRawRequest) (*DeleteRawResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedAsyncUpdateServer) DeleteAtTime(context.Context, *DeleteAtTimeRequest) (*DeleteAtTimeResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedAsyncUpdateServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}

var _ AsyncUpdateServer = (*UnimplementedAsyncUpdateServer)(nil)
