// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopchda_asyncupdate

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	oaut "github.com/oiweiwei/go-msrpc/msrpc/dcom/oaut"
	dtyp "github.com/oiweiwei/go-msrpc/msrpc/dtyp"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
	opchda "github.com/oiweiwei/go-opcda/opc/opchda"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom.GoPackage
	_ = iunknown.GoPackage
	_ = opchda.GoPackage
	_ = dtyp.GoPackage
	_ = oaut.GoPackage
)

var (
	// import guard
	GoPackage = "opchda"
)

var (
	// IOPCHDA_AsyncUpdate interface identifier 1f1217b6-dee0-11d2-a5e5-000086339399
	AsyncUpdateIID = &dcom.IID{Data1: 0x1f1217b6, Data2: 0xdee0, Data3: 0x11d2, Data4: []byte{0xa5, 0xe5, 0x00, 0x00, 0x86, 0x33, 0x93, 0x99}}
	// Syntax UUID
	AsyncUpdateSyntaxUUID = &uuid.UUID{TimeLow: 0x1f1217b6, TimeMid: 0xdee0, TimeHiAndVersion: 0x11d2, ClockSeqHiAndReserved: 0xa5, ClockSeqLow: 0xe5, Node: [6]uint8{0x0, 0x0, 0x86, 0x33, 0x93, 0x99}}
	// Syntax ID
	AsyncUpdateSyntaxV0_0 = &dcerpc.SyntaxID{IfUUID: AsyncUpdateSyntaxUUID, IfVersionMajor: 0, IfVersionMinor: 0}
)

// IOPCHDA_AsyncUpdate interface.
type AsyncUpdateClient interface {

	// IUnknown retrieval method.
	Unknown() iunknown.UnknownClient

	// QueryCapabilities operation.
	QueryCapabilities(context.Context, *QueryCapabilitiesRequest, ...dcerpc.CallOption) (*QueryCapabilitiesResponse, error)

	// Insert operation.
	Insert(context.Context, *InsertRequest, ...dcerpc.CallOption) (*InsertResponse, error)

	// Replace operation.
	Replace(context.Context, *ReplaceRequest, ...dcerpc.CallOption) (*ReplaceResponse, error)

	// InsertReplace operation.
	InsertReplace(context.Context, *InsertReplaceRequest, ...dcerpc.CallOption) (*InsertReplaceResponse, error)

	// DeleteRaw operation.
	DeleteRaw(context.Context, *DeleteRawRequest, ...dcerpc.CallOption) (*DeleteRawResponse, error)

	// DeleteAtTime operation.
	DeleteAtTime(context.Context, *DeleteAtTimeRequest, ...dcerpc.CallOption) (*DeleteAtTimeResponse, error)

	// Cancel operation.
	Cancel(context.Context, *CancelRequest, ...dcerpc.CallOption) (*CancelResponse, error)

	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn

	// IPID sets the object interface identifier.
	IPID(context.Context, *dcom.IPID) AsyncUpdateClient
}

type xxx_DefaultAsyncUpdateClient struct {
	iunknown.UnknownClient
	cc   dcerpc.Conn
	ipid *dcom.IPID
}

func (o *xxx_DefaultAsyncUpdateClient) Unknown() iunknown.UnknownClient {
	return o.UnknownClient
}

func (o *xxx_DefaultAsyncUpdateClient) QueryCapabilities(ctx context.Context, in *QueryCapabilitiesRequest, opts ...dcerpc.CallOption) (*QueryCapabilitiesResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &QueryCapabilitiesResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultAsyncUpdateClient) Insert(ctx context.Context, in *InsertRequest, opts ...dcerpc.CallOption) (*InsertResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &InsertResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultAsyncUpdateClient) Replace(ctx context.Context, in *ReplaceRequest, opts ...dcerpc.CallOption) (*ReplaceResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &ReplaceResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultAsyncUpdateClient) InsertReplace(ctx context.Context, in *InsertReplaceRequest, opts ...dcerpc.CallOption) (*InsertReplaceResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &InsertReplaceResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultAsyncUpdateClient) DeleteRaw(ctx context.Context, in *DeleteRawRequest, opts ...dcerpc.CallOption) (*DeleteRawResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &DeleteRawResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultAsyncUpdateClient) DeleteAtTime(ctx context.Context, in *DeleteAtTimeRequest, opts ...dcerpc.CallOption) (*DeleteAtTimeResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &DeleteAtTimeResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultAsyncUpdateClient) Cancel(ctx context.Context, in *CancelRequest, opts ...dcerpc.CallOption) (*CancelResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &CancelResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultAsyncUpdateClient) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultAsyncUpdateClient) Conn() dcerpc.Conn {
	return o.cc
}

func (o *xxx_DefaultAsyncUpdateClient) IPID(ctx context.Context, ipid *dcom.IPID) AsyncUpdateClient {
	if ipid == nil {
		ipid = &dcom.IPID{}
	}
	return &xxx_DefaultAsyncUpdateClient{
		UnknownClient: o.UnknownClient.IPID(ctx, ipid),
		cc:            o.cc,
		ipid:          ipid,
	}
}

func NewAsyncUpdateClient(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (AsyncUpdateClient, error) {
	var err error
	if !dcom.IsSuperclass(opts) {
		cc, err = cc.Bind(ctx, append(opts, dcerpc.WithAbstractSyntax(AsyncUpdateSyntaxV0_0))...)
		if err != nil {
			return nil, err
		}
	}
	base, err := iunknown.NewUnknownClient(ctx, cc, append(opts, dcom.Superclass(cc))...)
	if err != nil {
		return nil, err
	}
	ipid, ok := dcom.HasIPID(opts)
	if ok {
		base = base.IPID(ctx, ipid)
	}
	return &xxx_DefaultAsyncUpdateClient{
		UnknownClient: base,
		cc:            cc,
		ipid:          ipid,
	}, nil
}

// xxx_QueryCapabilitiesOperation structure represents the QueryCapabilities operation
type xxx_QueryCapabilitiesOperation struct {
	This         *dcom.ORPCThis            `idl:"name:This" json:"this"`
	That         *dcom.ORPCThat            `idl:"name:That" json:"that"`
	Capabilities opchda.UpdateCapabilities `idl:"name:pCapabilities" json:"capabilities"`
	Return       int32                     `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of QueryCapabilities operation.
func (o *xxx_QueryCapabilitiesOperation) OpNum() int { return 3 }

// OpName returns the operation name of QueryCapabilities operation.
func (o *xxx_QueryCapabilitiesOperation) OpName() string {
	return "/IOPCHDA_AsyncUpdate/v0/QueryCapabilities"
}

func (o *xxx_QueryCapabilitiesOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_QueryCapabilitiesOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_QueryCapabilitiesOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_QueryCapabilitiesOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_QueryCapabilitiesOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pCapabilities {out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_UPDATECAPABILITIES}(enum))
	{
		if err := w.WriteEnum(uint16(o.Capabilities)); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_QueryCapabilitiesOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pCapabilities {out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_UPDATECAPABILITIES}(enum))
	{
		if err := w.ReadEnum((*uint16)(&o.Capabilities)); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// QueryCapabilitiesRequest structure represents the QueryCapabilities operation request
type QueryCapabilitiesRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This *dcom.ORPCThis `idl:"name:This" json:"this"`
}

func (o *QueryCapabilitiesRequest) xxx_ToOp(ctx context.Context, op *xxx_QueryCapabilitiesOperation) *xxx_QueryCapabilitiesOperation {
	if op == nil {
		op = &xxx_QueryCapabilitiesOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	return op
}

func (o *QueryCapabilitiesRequest) xxx_FromOp(ctx context.Context, op *xxx_QueryCapabilitiesOperation) {
	if o == nil {
		return
	}
	o.This = op.This
}
func (o *QueryCapabilitiesRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *QueryCapabilitiesRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_QueryCapabilitiesOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeQueryCapabilitiesRequest build a response structure from the given request structure.
func (o *QueryCapabilitiesRequest) MakeResponse() *QueryCapabilitiesResponse {
	return &QueryCapabilitiesResponse{}
}

// OpNum returns the operation number of QueryCapabilities operation.
func (o *QueryCapabilitiesRequest) OpNum() int { return 3 }

// OpName returns the operation name of QueryCapabilities operation.
func (o *QueryCapabilitiesRequest) OpName() string {
	return "/IOPCHDA_AsyncUpdate/v0/QueryCapabilities"
}

// QueryCapabilitiesResponse structure represents the QueryCapabilities operation response
type QueryCapabilitiesResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That         *dcom.ORPCThat            `idl:"name:That" json:"that"`
	Capabilities opchda.UpdateCapabilities `idl:"name:pCapabilities" json:"capabilities"`
	// Return: The QueryCapabilities return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *QueryCapabilitiesResponse) xxx_ToOp(ctx context.Context, op *xxx_QueryCapabilitiesOperation) *xxx_QueryCapabilitiesOperation {
	if op == nil {
		op = &xxx_QueryCapabilitiesOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Capabilities = o.Capabilities
	op.Return = o.Return
	return op
}

func (o *QueryCapabilitiesResponse) xxx_FromOp(ctx context.Context, op *xxx_QueryCapabilitiesOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Capabilities = op.Capabilities
	o.Return = op.Return
}
func (o *QueryCapabilitiesResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *QueryCapabilitiesResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_QueryCapabilitiesOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_InsertOperation structure represents the Insert operation
type xxx_InsertOperation struct {
	This          *dcom.ORPCThis   `idl:"name:This" json:"this"`
	That          *dcom.ORPCThat   `idl:"name:That" json:"that"`
	TransactionID uint32           `idl:"name:dwTransactionID" json:"transaction_id"`
	NumItems      uint32           `idl:"name:dwNumItems" json:"num_items"`
	Server        []uint32         `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
	Timestamps    []*dtyp.Filetime `idl:"name:ftTimeStamps;size_is:(dwNumItems)" json:"timestamps"`
	DataValues    []*oaut.Variant  `idl:"name:vDataValues;size_is:(dwNumItems)" json:"data_values"`
	Qualities     []uint32         `idl:"name:pdwQualities;size_is:(dwNumItems)" json:"qualities"`
	CancelID      uint32           `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors        []int32          `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	Return        int32            `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of Insert operation.
func (o *xxx_InsertOperation) OpNum() int { return 4 }

// OpName returns the operation name of Insert operation.
func (o *xxx_InsertOperation) OpName() string { return "/IOPCHDA_AsyncUpdate/v0/Insert" }

func (o *xxx_InsertOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if o.Server != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Server))
	}
	if o.Timestamps != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Timestamps))
	}
	if o.DataValues != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.DataValues))
	}
	if o.Qualities != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Qualities))
	}
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_InsertOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.TransactionID); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Server {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if err := w.WriteData(o.Server[i1]); err != nil {
				return err
			}
		}
		for i1 := len(o.Server); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WriteData(uint32(0)); err != nil {
				return err
			}
		}
	}
	// ftTimeStamps {in} (1:{pointer=ref}*(1))(2:{alias=FILETIME}[dim:0,size_is=dwNumItems](struct))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Timestamps {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if o.Timestamps[i1] != nil {
				if err := o.Timestamps[i1].MarshalNDR(ctx, w); err != nil {
					return err
				}
			} else {
				if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
		}
		for i1 := len(o.Timestamps); uint64(i1) < sizeInfo[0]; i1++ {
			if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
	}
	// vDataValues {in} (1:{pointer=ref}*(1))(2:{alias=VARIANT}[dim:0,size_is=dwNumItems]*(1))(3:{alias=_VARIANT}(struct))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.DataValues {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if o.DataValues[i1] != nil {
				_ptr_vDataValues := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
					if o.DataValues[i1] != nil {
						if err := o.DataValues[i1].MarshalNDR(ctx, w); err != nil {
							return err
						}
					} else {
						if err := (&oaut.Variant{}).MarshalNDR(ctx, w); err != nil {
							return err
						}
					}
					return nil
				})
				if err := w.WritePointer(&o.DataValues[i1], _ptr_vDataValues); err != nil {
					return err
				}
			} else {
				if err := w.WritePointer(nil); err != nil {
					return err
				}
			}
		}
		for i1 := len(o.DataValues); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pdwQualities {in} (1:{pointer=ref}*(1))(2:{alias=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Qualities {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if err := w.WriteData(o.Qualities[i1]); err != nil {
				return err
			}
		}
		for i1 := len(o.Qualities); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WriteData(uint32(0)); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_InsertOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.TransactionID); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Server", sizeInfo[0])
		}
		o.Server = make([]uint32, sizeInfo[0])
		for i1 := range o.Server {
			i1 := i1
			if err := w.ReadData(&o.Server[i1]); err != nil {
				return err
			}
		}
	}
	// ftTimeStamps {in} (1:{pointer=ref}*(1))(2:{alias=FILETIME}[dim:0,size_is=dwNumItems](struct))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Timestamps", sizeInfo[0])
		}
		o.Timestamps = make([]*dtyp.Filetime, sizeInfo[0])
		for i1 := range o.Timestamps {
			i1 := i1
			if o.Timestamps[i1] == nil {
				o.Timestamps[i1] = &dtyp.Filetime{}
			}
			if err := o.Timestamps[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
	}
	// vDataValues {in} (1:{pointer=ref}*(1))(2:{alias=VARIANT}[dim:0,size_is=dwNumItems]*(1))(3:{alias=_VARIANT}(struct))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.DataValues", sizeInfo[0])
		}
		o.DataValues = make([]*oaut.Variant, sizeInfo[0])
		for i1 := range o.DataValues {
			i1 := i1
			_ptr_vDataValues := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
				if o.DataValues[i1] == nil {
					o.DataValues[i1] = &oaut.Variant{}
				}
				if err := o.DataValues[i1].UnmarshalNDR(ctx, w); err != nil {
					return err
				}
				return nil
			})
			_s_vDataValues := func(ptr interface{}) { o.DataValues[i1] = *ptr.(**oaut.Variant) }
			if err := w.ReadPointer(&o.DataValues[i1], _s_vDataValues, _ptr_vDataValues); err != nil {
				return err
			}
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pdwQualities {in} (1:{pointer=ref}*(1))(2:{alias=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Qualities", sizeInfo[0])
		}
		o.Qualities = make([]uint32, sizeInfo[0])
		for i1 := range o.Qualities {
			i1 := i1
			if err := w.ReadData(&o.Qualities[i1]); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_InsertOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_InsertOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		if o.Errors != nil || o.NumItems > 0 {
			_ptr_ppErrors := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				dimSize1 := uint64(o.NumItems)
				if err := w.WriteSize(dimSize1); err != nil {
					return err
				}
				sizeInfo := []uint64{
					dimSize1,
				}
				for i1 := range o.Errors {
					i1 := i1
					if uint64(i1) >= sizeInfo[0] {
						break
					}
					if err := w.WriteData(o.Errors[i1]); err != nil {
						return err
					}
				}
				for i1 := len(o.Errors); uint64(i1) < sizeInfo[0]; i1++ {
					if err := w.WriteData(int32(0)); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Errors, _ptr_ppErrors); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_InsertOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		_ptr_ppErrors := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			sizeInfo := []uint64{
				0,
			}
			for sz1 := range sizeInfo {
				if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
					return err
				}
			}
			if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
				return fmt.Errorf("buffer overflow for size %d of array o.Errors", sizeInfo[0])
			}
			o.Errors = make([]int32, sizeInfo[0])
			for i1 := range o.Errors {
				i1 := i1
				if err := w.ReadData(&o.Errors[i1]); err != nil {
					return err
				}
			}
			return nil
		})
		_s_ppErrors := func(ptr interface{}) { o.Errors = *ptr.(*[]int32) }
		if err := w.ReadPointer(&o.Errors, _s_ppErrors, _ptr_ppErrors); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// InsertRequest structure represents the Insert operation request
type InsertRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This          *dcom.ORPCThis   `idl:"name:This" json:"this"`
	TransactionID uint32           `idl:"name:dwTransactionID" json:"transaction_id"`
	NumItems      uint32           `idl:"name:dwNumItems" json:"num_items"`
	Server        []uint32         `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
	Timestamps    []*dtyp.Filetime `idl:"name:ftTimeStamps;size_is:(dwNumItems)" json:"timestamps"`
	DataValues    []*oaut.Variant  `idl:"name:vDataValues;size_is:(dwNumItems)" json:"data_values"`
	Qualities     []uint32         `idl:"name:pdwQualities;size_is:(dwNumItems)" json:"qualities"`
}

func (o *InsertRequest) xxx_ToOp(ctx context.Context, op *xxx_InsertOperation) *xxx_InsertOperation {
	if op == nil {
		op = &xxx_InsertOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.TransactionID = o.TransactionID
	op.NumItems = o.NumItems
	op.Server = o.Server
	op.Timestamps = o.Timestamps
	op.DataValues = o.DataValues
	op.Qualities = o.Qualities
	return op
}

func (o *InsertRequest) xxx_FromOp(ctx context.Context, op *xxx_InsertOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.TransactionID = op.TransactionID
	o.NumItems = op.NumItems
	o.Server = op.Server
	o.Timestamps = op.Timestamps
	o.DataValues = op.DataValues
	o.Qualities = op.Qualities
}
func (o *InsertRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *InsertRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_InsertOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeInsertRequest build a response structure from the given request structure.
func (o *InsertRequest) MakeResponse() *InsertResponse {
	if o == nil {
		return &InsertResponse{}
	}
	return &InsertResponse{
		NumItems: o.NumItems,
	}
}

// OpNum returns the operation number of Insert operation.
func (o *InsertRequest) OpNum() int { return 4 }

// OpName returns the operation name of Insert operation.
func (o *InsertRequest) OpName() string { return "/IOPCHDA_AsyncUpdate/v0/Insert" }

// InsertResponse structure represents the Insert operation response
type InsertResponse struct {
	// XXX: dwNumItems is an implicit input depedency for output parameters
	NumItems uint32 `idl:"name:dwNumItems" json:"num_items"`

	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That     *dcom.ORPCThat `idl:"name:That" json:"that"`
	CancelID uint32         `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors   []int32        `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	// Return: The Insert return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *InsertResponse) xxx_ToOp(ctx context.Context, op *xxx_InsertOperation) *xxx_InsertOperation {
	if op == nil {
		op = &xxx_InsertOperation{}
	}
	if o == nil {
		return op
	}
	// XXX: implicit input dependencies for output parameters
	if op.NumItems == uint32(0) {
		op.NumItems = o.NumItems
	}

	op.That = o.That
	op.CancelID = o.CancelID
	op.Errors = o.Errors
	op.Return = o.Return
	return op
}

func (o *InsertResponse) xxx_FromOp(ctx context.Context, op *xxx_InsertOperation) {
	if o == nil {
		return
	}
	// XXX: implicit input dependencies for output parameters
	o.NumItems = op.NumItems

	o.That = op.That
	o.CancelID = op.CancelID
	o.Errors = op.Errors
	o.Return = op.Return
}
func (o *InsertResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *InsertResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_InsertOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_ReplaceOperation structure represents the Replace operation
type xxx_ReplaceOperation struct {
	This          *dcom.ORPCThis   `idl:"name:This" json:"this"`
	That          *dcom.ORPCThat   `idl:"name:That" json:"that"`
	TransactionID uint32           `idl:"name:dwTransactionID" json:"transaction_id"`
	NumItems      uint32           `idl:"name:dwNumItems" json:"num_items"`
	Server        []uint32         `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
	Timestamps    []*dtyp.Filetime `idl:"name:ftTimeStamps;size_is:(dwNumItems)" json:"timestamps"`
	DataValues    []*oaut.Variant  `idl:"name:vDataValues;size_is:(dwNumItems)" json:"data_values"`
	Qualities     []uint32         `idl:"name:pdwQualities;size_is:(dwNumItems)" json:"qualities"`
	CancelID      uint32           `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors        []int32          `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	Return        int32            `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of Replace operation.
func (o *xxx_ReplaceOperation) OpNum() int { return 5 }

// OpName returns the operation name of Replace operation.
func (o *xxx_ReplaceOperation) OpName() string { return "/IOPCHDA_AsyncUpdate/v0/Replace" }

func (o *xxx_ReplaceOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if o.Server != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Server))
	}
	if o.Timestamps != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Timestamps))
	}
	if o.DataValues != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.DataValues))
	}
	if o.Qualities != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Qualities))
	}
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_ReplaceOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.TransactionID); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Server {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if err := w.WriteData(o.Server[i1]); err != nil {
				return err
			}
		}
		for i1 := len(o.Server); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WriteData(uint32(0)); err != nil {
				return err
			}
		}
	}
	// ftTimeStamps {in} (1:{pointer=ref}*(1))(2:{alias=FILETIME}[dim:0,size_is=dwNumItems](struct))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Timestamps {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if o.Timestamps[i1] != nil {
				if err := o.Timestamps[i1].MarshalNDR(ctx, w); err != nil {
					return err
				}
			} else {
				if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
		}
		for i1 := len(o.Timestamps); uint64(i1) < sizeInfo[0]; i1++ {
			if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
	}
	// vDataValues {in} (1:{pointer=ref}*(1))(2:{alias=VARIANT}[dim:0,size_is=dwNumItems]*(1))(3:{alias=_VARIANT}(struct))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.DataValues {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if o.DataValues[i1] != nil {
				_ptr_vDataValues := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
					if o.DataValues[i1] != nil {
						if err := o.DataValues[i1].MarshalNDR(ctx, w); err != nil {
							return err
						}
					} else {
						if err := (&oaut.Variant{}).MarshalNDR(ctx, w); err != nil {
							return err
						}
					}
					return nil
				})
				if err := w.WritePointer(&o.DataValues[i1], _ptr_vDataValues); err != nil {
					return err
				}
			} else {
				if err := w.WritePointer(nil); err != nil {
					return err
				}
			}
		}
		for i1 := len(o.DataValues); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pdwQualities {in} (1:{pointer=ref}*(1))(2:{alias=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Qualities {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if err := w.WriteData(o.Qualities[i1]); err != nil {
				return err
			}
		}
		for i1 := len(o.Qualities); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WriteData(uint32(0)); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_ReplaceOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.TransactionID); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Server", sizeInfo[0])
		}
		o.Server = make([]uint32, sizeInfo[0])
		for i1 := range o.Server {
			i1 := i1
			if err := w.ReadData(&o.Server[i1]); err != nil {
				return err
			}
		}
	}
	// ftTimeStamps {in} (1:{pointer=ref}*(1))(2:{alias=FILETIME}[dim:0,size_is=dwNumItems](struct))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Timestamps", sizeInfo[0])
		}
		o.Timestamps = make([]*dtyp.Filetime, sizeInfo[0])
		for i1 := range o.Timestamps {
			i1 := i1
			if o.Timestamps[i1] == nil {
				o.Timestamps[i1] = &dtyp.Filetime{}
			}
			if err := o.Timestamps[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
	}
	// vDataValues {in} (1:{pointer=ref}*(1))(2:{alias=VARIANT}[dim:0,size_is=dwNumItems]*(1))(3:{alias=_VARIANT}(struct))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.DataValues", sizeInfo[0])
		}
		o.DataValues = make([]*oaut.Variant, sizeInfo[0])
		for i1 := range o.DataValues {
			i1 := i1
			_ptr_vDataValues := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
				if o.DataValues[i1] == nil {
					o.DataValues[i1] = &oaut.Variant{}
				}
				if err := o.DataValues[i1].UnmarshalNDR(ctx, w); err != nil {
					return err
				}
				return nil
			})
			_s_vDataValues := func(ptr interface{}) { o.DataValues[i1] = *ptr.(**oaut.Variant) }
			if err := w.ReadPointer(&o.DataValues[i1], _s_vDataValues, _ptr_vDataValues); err != nil {
				return err
			}
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pdwQualities {in} (1:{pointer=ref}*(1))(2:{alias=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Qualities", sizeInfo[0])
		}
		o.Qualities = make([]uint32, sizeInfo[0])
		for i1 := range o.Qualities {
			i1 := i1
			if err := w.ReadData(&o.Qualities[i1]); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_ReplaceOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_ReplaceOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		if o.Errors != nil || o.NumItems > 0 {
			_ptr_ppErrors := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				dimSize1 := uint64(o.NumItems)
				if err := w.WriteSize(dimSize1); err != nil {
					return err
				}
				sizeInfo := []uint64{
					dimSize1,
				}
				for i1 := range o.Errors {
					i1 := i1
					if uint64(i1) >= sizeInfo[0] {
						break
					}
					if err := w.WriteData(o.Errors[i1]); err != nil {
						return err
					}
				}
				for i1 := len(o.Errors); uint64(i1) < sizeInfo[0]; i1++ {
					if err := w.WriteData(int32(0)); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Errors, _ptr_ppErrors); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_ReplaceOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		_ptr_ppErrors := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			sizeInfo := []uint64{
				0,
			}
			for sz1 := range sizeInfo {
				if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
					return err
				}
			}
			if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
				return fmt.Errorf("buffer overflow for size %d of array o.Errors", sizeInfo[0])
			}
			o.Errors = make([]int32, sizeInfo[0])
			for i1 := range o.Errors {
				i1 := i1
				if err := w.ReadData(&o.Errors[i1]); err != nil {
					return err
				}
			}
			return nil
		})
		_s_ppErrors := func(ptr interface{}) { o.Errors = *ptr.(*[]int32) }
		if err := w.ReadPointer(&o.Errors, _s_ppErrors, _ptr_ppErrors); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// ReplaceRequest structure represents the Replace operation request
type ReplaceRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This          *dcom.ORPCThis   `idl:"name:This" json:"this"`
	TransactionID uint32           `idl:"name:dwTransactionID" json:"transaction_id"`
	NumItems      uint32           `idl:"name:dwNumItems" json:"num_items"`
	Server        []uint32         `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
	Timestamps    []*dtyp.Filetime `idl:"name:ftTimeStamps;size_is:(dwNumItems)" json:"timestamps"`
	DataValues    []*oaut.Variant  `idl:"name:vDataValues;size_is:(dwNumItems)" json:"data_values"`
	Qualities     []uint32         `idl:"name:pdwQualities;size_is:(dwNumItems)" json:"qualities"`
}

func (o *ReplaceRequest) xxx_ToOp(ctx context.Context, op *xxx_ReplaceOperation) *xxx_ReplaceOperation {
	if op == nil {
		op = &xxx_ReplaceOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.TransactionID = o.TransactionID
	op.NumItems = o.NumItems
	op.Server = o.Server
	op.Timestamps = o.Timestamps
	op.DataValues = o.DataValues
	op.Qualities = o.Qualities
	return op
}

func (o *ReplaceRequest) xxx_FromOp(ctx context.Context, op *xxx_ReplaceOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.TransactionID = op.TransactionID
	o.NumItems = op.NumItems
	o.Server = op.Server
	o.Timestamps = op.Timestamps
	o.DataValues = op.DataValues
	o.Qualities = op.Qualities
}
func (o *ReplaceRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *ReplaceRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_ReplaceOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeReplaceRequest build a response structure from the given request structure.
func (o *ReplaceRequest) MakeResponse() *ReplaceResponse {
	if o == nil {
		return &ReplaceResponse{}
	}
	return &ReplaceResponse{
		NumItems: o.NumItems,
	}
}

// OpNum returns the operation number of Replace operation.
func (o *ReplaceRequest) OpNum() int { return 5 }

// OpName returns the operation name of Replace operation.
func (o *ReplaceRequest) OpName() string { return "/IOPCHDA_AsyncUpdate/v0/Replace" }

// ReplaceResponse structure represents the Replace operation response
type ReplaceResponse struct {
	// XXX: dwNumItems is an implicit input depedency for output parameters
	NumItems uint32 `idl:"name:dwNumItems" json:"num_items"`

	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That     *dcom.ORPCThat `idl:"name:That" json:"that"`
	CancelID uint32         `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors   []int32        `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	// Return: The Replace return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *ReplaceResponse) xxx_ToOp(ctx context.Context, op *xxx_ReplaceOperation) *xxx_ReplaceOperation {
	if op == nil {
		op = &xxx_ReplaceOperation{}
	}
	if o == nil {
		return op
	}
	// XXX: implicit input dependencies for output parameters
	if op.NumItems == uint32(0) {
		op.NumItems = o.NumItems
	}

	op.That = o.That
	op.CancelID = o.CancelID
	op.Errors = o.Errors
	op.Return = o.Return
	return op
}

func (o *ReplaceResponse) xxx_FromOp(ctx context.Context, op *xxx_ReplaceOperation) {
	if o == nil {
		return
	}
	// XXX: implicit input dependencies for output parameters
	o.NumItems = op.NumItems

	o.That = op.That
	o.CancelID = op.CancelID
	o.Errors = op.Errors
	o.Return = op.Return
}
func (o *ReplaceResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *ReplaceResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_ReplaceOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_InsertReplaceOperation structure represents the InsertReplace operation
type xxx_InsertReplaceOperation struct {
	This          *dcom.ORPCThis   `idl:"name:This" json:"this"`
	That          *dcom.ORPCThat   `idl:"name:That" json:"that"`
	TransactionID uint32           `idl:"name:dwTransactionID" json:"transaction_id"`
	NumItems      uint32           `idl:"name:dwNumItems" json:"num_items"`
	Server        []uint32         `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
	Timestamps    []*dtyp.Filetime `idl:"name:ftTimeStamps;size_is:(dwNumItems)" json:"timestamps"`
	DataValues    []*oaut.Variant  `idl:"name:vDataValues;size_is:(dwNumItems)" json:"data_values"`
	Qualities     []uint32         `idl:"name:pdwQualities;size_is:(dwNumItems)" json:"qualities"`
	CancelID      uint32           `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors        []int32          `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	Return        int32            `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of InsertReplace operation.
func (o *xxx_InsertReplaceOperation) OpNum() int { return 6 }

// OpName returns the operation name of InsertReplace operation.
func (o *xxx_InsertReplaceOperation) OpName() string { return "/IOPCHDA_AsyncUpdate/v0/InsertReplace" }

func (o *xxx_InsertReplaceOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if o.Server != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Server))
	}
	if o.Timestamps != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Timestamps))
	}
	if o.DataValues != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.DataValues))
	}
	if o.Qualities != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Qualities))
	}
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_InsertReplaceOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.TransactionID); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Server {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if err := w.WriteData(o.Server[i1]); err != nil {
				return err
			}
		}
		for i1 := len(o.Server); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WriteData(uint32(0)); err != nil {
				return err
			}
		}
	}
	// ftTimeStamps {in} (1:{pointer=ref}*(1))(2:{alias=FILETIME}[dim:0,size_is=dwNumItems](struct))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Timestamps {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if o.Timestamps[i1] != nil {
				if err := o.Timestamps[i1].MarshalNDR(ctx, w); err != nil {
					return err
				}
			} else {
				if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
		}
		for i1 := len(o.Timestamps); uint64(i1) < sizeInfo[0]; i1++ {
			if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
	}
	// vDataValues {in} (1:{pointer=ref}*(1))(2:{alias=VARIANT}[dim:0,size_is=dwNumItems]*(1))(3:{alias=_VARIANT}(struct))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.DataValues {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if o.DataValues[i1] != nil {
				_ptr_vDataValues := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
					if o.DataValues[i1] != nil {
						if err := o.DataValues[i1].MarshalNDR(ctx, w); err != nil {
							return err
						}
					} else {
						if err := (&oaut.Variant{}).MarshalNDR(ctx, w); err != nil {
							return err
						}
					}
					return nil
				})
				if err := w.WritePointer(&o.DataValues[i1], _ptr_vDataValues); err != nil {
					return err
				}
			} else {
				if err := w.WritePointer(nil); err != nil {
					return err
				}
			}
		}
		for i1 := len(o.DataValues); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pdwQualities {in} (1:{pointer=ref}*(1))(2:{alias=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Qualities {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if err := w.WriteData(o.Qualities[i1]); err != nil {
				return err
			}
		}
		for i1 := len(o.Qualities); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WriteData(uint32(0)); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_InsertReplaceOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.TransactionID); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Server", sizeInfo[0])
		}
		o.Server = make([]uint32, sizeInfo[0])
		for i1 := range o.Server {
			i1 := i1
			if err := w.ReadData(&o.Server[i1]); err != nil {
				return err
			}
		}
	}
	// ftTimeStamps {in} (1:{pointer=ref}*(1))(2:{alias=FILETIME}[dim:0,size_is=dwNumItems](struct))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Timestamps", sizeInfo[0])
		}
		o.Timestamps = make([]*dtyp.Filetime, sizeInfo[0])
		for i1 := range o.Timestamps {
			i1 := i1
			if o.Timestamps[i1] == nil {
				o.Timestamps[i1] = &dtyp.Filetime{}
			}
			if err := o.Timestamps[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
	}
	// vDataValues {in} (1:{pointer=ref}*(1))(2:{alias=VARIANT}[dim:0,size_is=dwNumItems]*(1))(3:{alias=_VARIANT}(struct))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.DataValues", sizeInfo[0])
		}
		o.DataValues = make([]*oaut.Variant, sizeInfo[0])
		for i1 := range o.DataValues {
			i1 := i1
			_ptr_vDataValues := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
				if o.DataValues[i1] == nil {
					o.DataValues[i1] = &oaut.Variant{}
				}
				if err := o.DataValues[i1].UnmarshalNDR(ctx, w); err != nil {
					return err
				}
				return nil
			})
			_s_vDataValues := func(ptr interface{}) { o.DataValues[i1] = *ptr.(**oaut.Variant) }
			if err := w.ReadPointer(&o.DataValues[i1], _s_vDataValues, _ptr_vDataValues); err != nil {
				return err
			}
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pdwQualities {in} (1:{pointer=ref}*(1))(2:{alias=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Qualities", sizeInfo[0])
		}
		o.Qualities = make([]uint32, sizeInfo[0])
		for i1 := range o.Qualities {
			i1 := i1
			if err := w.ReadData(&o.Qualities[i1]); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_InsertReplaceOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_InsertReplaceOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		if o.Errors != nil || o.NumItems > 0 {
			_ptr_ppErrors := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				dimSize1 := uint64(o.NumItems)
				if err := w.WriteSize(dimSize1); err != nil {
					return err
				}
				sizeInfo := []uint64{
					dimSize1,
				}
				for i1 := range o.Errors {
					i1 := i1
					if uint64(i1) >= sizeInfo[0] {
						break
					}
					if err := w.WriteData(o.Errors[i1]); err != nil {
						return err
					}
				}
				for i1 := len(o.Errors); uint64(i1) < sizeInfo[0]; i1++ {
					if err := w.WriteData(int32(0)); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Errors, _ptr_ppErrors); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_InsertReplaceOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		_ptr_ppErrors := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			sizeInfo := []uint64{
				0,
			}
			for sz1 := range sizeInfo {
				if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
					return err
				}
			}
			if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
				return fmt.Errorf("buffer overflow for size %d of array o.Errors", sizeInfo[0])
			}
			o.Errors = make([]int32, sizeInfo[0])
			for i1 := range o.Errors {
				i1 := i1
				if err := w.ReadData(&o.Errors[i1]); err != nil {
					return err
				}
			}
			return nil
		})
		_s_ppErrors := func(ptr interface{}) { o.Errors = *ptr.(*[]int32) }
		if err := w.ReadPointer(&o.Errors, _s_ppErrors, _ptr_ppErrors); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// InsertReplaceRequest structure represents the InsertReplace operation request
type InsertReplaceRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This          *dcom.ORPCThis   `idl:"name:This" json:"this"`
	TransactionID uint32           `idl:"name:dwTransactionID" json:"transaction_id"`
	NumItems      uint32           `idl:"name:dwNumItems" json:"num_items"`
	Server        []uint32         `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
	Timestamps    []*dtyp.Filetime `idl:"name:ftTimeStamps;size_is:(dwNumItems)" json:"timestamps"`
	DataValues    []*oaut.Variant  `idl:"name:vDataValues;size_is:(dwNumItems)" json:"data_values"`
	Qualities     []uint32         `idl:"name:pdwQualities;size_is:(dwNumItems)" json:"qualities"`
}

func (o *InsertReplaceRequest) xxx_ToOp(ctx context.Context, op *xxx_InsertReplaceOperation) *xxx_InsertReplaceOperation {
	if op == nil {
		op = &xxx_InsertReplaceOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.TransactionID = o.TransactionID
	op.NumItems = o.NumItems
	op.Server = o.Server
	op.Timestamps = o.Timestamps
	op.DataValues = o.DataValues
	op.Qualities = o.Qualities
	return op
}

func (o *InsertReplaceRequest) xxx_FromOp(ctx context.Context, op *xxx_InsertReplaceOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.TransactionID = op.TransactionID
	o.NumItems = op.NumItems
	o.Server = op.Server
	o.Timestamps = op.Timestamps
	o.DataValues = op.DataValues
	o.Qualities = op.Qualities
}
func (o *InsertReplaceRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *InsertReplaceRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_InsertReplaceOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeInsertReplaceRequest build a response structure from the given request structure.
func (o *InsertReplaceRequest) MakeResponse() *InsertReplaceResponse {
	if o == nil {
		return &InsertReplaceResponse{}
	}
	return &InsertReplaceResponse{
		NumItems: o.NumItems,
	}
}

// OpNum returns the operation number of InsertReplace operation.
func (o *InsertReplaceRequest) OpNum() int { return 6 }

// OpName returns the operation name of InsertReplace operation.
func (o *InsertReplaceRequest) OpName() string { return "/IOPCHDA_AsyncUpdate/v0/InsertReplace" }

// InsertReplaceResponse structure represents the InsertReplace operation response
type InsertReplaceResponse struct {
	// XXX: dwNumItems is an implicit input depedency for output parameters
	NumItems uint32 `idl:"name:dwNumItems" json:"num_items"`

	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That     *dcom.ORPCThat `idl:"name:That" json:"that"`
	CancelID uint32         `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors   []int32        `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	// Return: The InsertReplace return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *InsertReplaceResponse) xxx_ToOp(ctx context.Context, op *xxx_InsertReplaceOperation) *xxx_InsertReplaceOperation {
	if op == nil {
		op = &xxx_InsertReplaceOperation{}
	}
	if o == nil {
		return op
	}
	// XXX: implicit input dependencies for output parameters
	if op.NumItems == uint32(0) {
		op.NumItems = o.NumItems
	}

	op.That = o.That
	op.CancelID = o.CancelID
	op.Errors = o.Errors
	op.Return = o.Return
	return op
}

func (o *InsertReplaceResponse) xxx_FromOp(ctx context.Context, op *xxx_InsertReplaceOperation) {
	if o == nil {
		return
	}
	// XXX: implicit input dependencies for output parameters
	o.NumItems = op.NumItems

	o.That = op.That
	o.CancelID = op.CancelID
	o.Errors = op.Errors
	o.Return = op.Return
}
func (o *InsertReplaceResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *InsertReplaceResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_InsertReplaceOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_DeleteRawOperation structure represents the DeleteRaw operation
type xxx_DeleteRawOperation struct {
	This          *dcom.ORPCThis `idl:"name:This" json:"this"`
	That          *dcom.ORPCThat `idl:"name:That" json:"that"`
	TransactionID uint32         `idl:"name:dwTransactionID" json:"transaction_id"`
	StartTime     *opchda.Time   `idl:"name:htStartTime" json:"start_time"`
	EndTime       *opchda.Time   `idl:"name:htEndTime" json:"end_time"`
	NumItems      uint32         `idl:"name:dwNumItems" json:"num_items"`
	Server        []uint32       `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
	CancelID      uint32         `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors        []int32        `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	Return        int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of DeleteRaw operation.
func (o *xxx_DeleteRawOperation) OpNum() int { return 7 }

// OpName returns the operation name of DeleteRaw operation.
func (o *xxx_DeleteRawOperation) OpName() string { return "/IOPCHDA_AsyncUpdate/v0/DeleteRaw" }

func (o *xxx_DeleteRawOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if o.Server != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Server))
	}
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_DeleteRawOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.TransactionID); err != nil {
			return err
		}
	}
	// htStartTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.StartTime != nil {
			if err := o.StartTime.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&opchda.Time{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// htEndTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.EndTime != nil {
			if err := o.EndTime.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&opchda.Time{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Server {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if err := w.WriteData(o.Server[i1]); err != nil {
				return err
			}
		}
		for i1 := len(o.Server); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WriteData(uint32(0)); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_DeleteRawOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.TransactionID); err != nil {
			return err
		}
	}
	// htStartTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.StartTime == nil {
			o.StartTime = &opchda.Time{}
		}
		if err := o.StartTime.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// htEndTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.EndTime == nil {
			o.EndTime = &opchda.Time{}
		}
		if err := o.EndTime.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Server", sizeInfo[0])
		}
		o.Server = make([]uint32, sizeInfo[0])
		for i1 := range o.Server {
			i1 := i1
			if err := w.ReadData(&o.Server[i1]); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_DeleteRawOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_DeleteRawOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// htStartTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.StartTime != nil {
			if err := o.StartTime.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&opchda.Time{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// htEndTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.EndTime != nil {
			if err := o.EndTime.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&opchda.Time{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		if o.Errors != nil || o.NumItems > 0 {
			_ptr_ppErrors := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				dimSize1 := uint64(o.NumItems)
				if err := w.WriteSize(dimSize1); err != nil {
					return err
				}
				sizeInfo := []uint64{
					dimSize1,
				}
				for i1 := range o.Errors {
					i1 := i1
					if uint64(i1) >= sizeInfo[0] {
						break
					}
					if err := w.WriteData(o.Errors[i1]); err != nil {
						return err
					}
				}
				for i1 := len(o.Errors); uint64(i1) < sizeInfo[0]; i1++ {
					if err := w.WriteData(int32(0)); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Errors, _ptr_ppErrors); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_DeleteRawOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// htStartTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.StartTime == nil {
			o.StartTime = &opchda.Time{}
		}
		if err := o.StartTime.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// htEndTime {in, out} (1:{pointer=ref}*(1))(2:{alias=OPCHDA_TIME}(struct))
	{
		if o.EndTime == nil {
			o.EndTime = &opchda.Time{}
		}
		if err := o.EndTime.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		_ptr_ppErrors := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			sizeInfo := []uint64{
				0,
			}
			for sz1 := range sizeInfo {
				if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
					return err
				}
			}
			if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
				return fmt.Errorf("buffer overflow for size %d of array o.Errors", sizeInfo[0])
			}
			o.Errors = make([]int32, sizeInfo[0])
			for i1 := range o.Errors {
				i1 := i1
				if err := w.ReadData(&o.Errors[i1]); err != nil {
					return err
				}
			}
			return nil
		})
		_s_ppErrors := func(ptr interface{}) { o.Errors = *ptr.(*[]int32) }
		if err := w.ReadPointer(&o.Errors, _s_ppErrors, _ptr_ppErrors); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// DeleteRawRequest structure represents the DeleteRaw operation request
type DeleteRawRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This          *dcom.ORPCThis `idl:"name:This" json:"this"`
	TransactionID uint32         `idl:"name:dwTransactionID" json:"transaction_id"`
	StartTime     *opchda.Time   `idl:"name:htStartTime" json:"start_time"`
	EndTime       *opchda.Time   `idl:"name:htEndTime" json:"end_time"`
	NumItems      uint32         `idl:"name:dwNumItems" json:"num_items"`
	Server        []uint32       `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
}

func (o *DeleteRawRequest) xxx_ToOp(ctx context.Context, op *xxx_DeleteRawOperation) *xxx_DeleteRawOperation {
	if op == nil {
		op = &xxx_DeleteRawOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.TransactionID = o.TransactionID
	op.StartTime = o.StartTime
	op.EndTime = o.EndTime
	op.NumItems = o.NumItems
	op.Server = o.Server
	return op
}

func (o *DeleteRawRequest) xxx_FromOp(ctx context.Context, op *xxx_DeleteRawOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.TransactionID = op.TransactionID
	o.StartTime = op.StartTime
	o.EndTime = op.EndTime
	o.NumItems = op.NumItems
	o.Server = op.Server
}
func (o *DeleteRawRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *DeleteRawRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_DeleteRawOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeDeleteRawRequest build a response structure from the given request structure.
func (o *DeleteRawRequest) MakeResponse() *DeleteRawResponse {
	if o == nil {
		return &DeleteRawResponse{}
	}
	return &DeleteRawResponse{
		NumItems: o.NumItems,
	}
}

// OpNum returns the operation number of DeleteRaw operation.
func (o *DeleteRawRequest) OpNum() int { return 7 }

// OpName returns the operation name of DeleteRaw operation.
func (o *DeleteRawRequest) OpName() string { return "/IOPCHDA_AsyncUpdate/v0/DeleteRaw" }

// DeleteRawResponse structure represents the DeleteRaw operation response
type DeleteRawResponse struct {
	// XXX: dwNumItems is an implicit input depedency for output parameters
	NumItems uint32 `idl:"name:dwNumItems" json:"num_items"`

	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That      *dcom.ORPCThat `idl:"name:That" json:"that"`
	StartTime *opchda.Time   `idl:"name:htStartTime" json:"start_time"`
	EndTime   *opchda.Time   `idl:"name:htEndTime" json:"end_time"`
	CancelID  uint32         `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors    []int32        `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	// Return: The DeleteRaw return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *DeleteRawResponse) xxx_ToOp(ctx context.Context, op *xxx_DeleteRawOperation) *xxx_DeleteRawOperation {
	if op == nil {
		op = &xxx_DeleteRawOperation{}
	}
	if o == nil {
		return op
	}
	// XXX: implicit input dependencies for output parameters
	if op.NumItems == uint32(0) {
		op.NumItems = o.NumItems
	}

	op.That = o.That
	op.StartTime = o.StartTime
	op.EndTime = o.EndTime
	op.CancelID = o.CancelID
	op.Errors = o.Errors
	op.Return = o.Return
	return op
}

func (o *DeleteRawResponse) xxx_FromOp(ctx context.Context, op *xxx_DeleteRawOperation) {
	if o == nil {
		return
	}
	// XXX: implicit input dependencies for output parameters
	o.NumItems = op.NumItems

	o.That = op.That
	o.StartTime = op.StartTime
	o.EndTime = op.EndTime
	o.CancelID = op.CancelID
	o.Errors = op.Errors
	o.Return = op.Return
}
func (o *DeleteRawResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *DeleteRawResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_DeleteRawOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_DeleteAtTimeOperation structure represents the DeleteAtTime operation
type xxx_DeleteAtTimeOperation struct {
	This          *dcom.ORPCThis   `idl:"name:This" json:"this"`
	That          *dcom.ORPCThat   `idl:"name:That" json:"that"`
	TransactionID uint32           `idl:"name:dwTransactionID" json:"transaction_id"`
	NumItems      uint32           `idl:"name:dwNumItems" json:"num_items"`
	Server        []uint32         `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
	Timestamps    []*dtyp.Filetime `idl:"name:ftTimeStamps;size_is:(dwNumItems)" json:"timestamps"`
	CancelID      uint32           `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors        []int32          `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	Return        int32            `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of DeleteAtTime operation.
func (o *xxx_DeleteAtTimeOperation) OpNum() int { return 8 }

// OpName returns the operation name of DeleteAtTime operation.
func (o *xxx_DeleteAtTimeOperation) OpName() string { return "/IOPCHDA_AsyncUpdate/v0/DeleteAtTime" }

func (o *xxx_DeleteAtTimeOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if o.Server != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Server))
	}
	if o.Timestamps != nil && o.NumItems == 0 {
		o.NumItems = uint32(len(o.Timestamps))
	}
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_DeleteAtTimeOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.TransactionID); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Server {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if err := w.WriteData(o.Server[i1]); err != nil {
				return err
			}
		}
		for i1 := len(o.Server); uint64(i1) < sizeInfo[0]; i1++ {
			if err := w.WriteData(uint32(0)); err != nil {
				return err
			}
		}
	}
	// ftTimeStamps {in} (1:{pointer=ref}*(1))(2:{alias=FILETIME}[dim:0,size_is=dwNumItems](struct))
	{
		dimSize1 := uint64(o.NumItems)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Timestamps {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if o.Timestamps[i1] != nil {
				if err := o.Timestamps[i1].MarshalNDR(ctx, w); err != nil {
					return err
				}
			} else {
				if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
		}
		for i1 := len(o.Timestamps); uint64(i1) < sizeInfo[0]; i1++ {
			if err := (&dtyp.Filetime{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_DeleteAtTimeOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwTransactionID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.TransactionID); err != nil {
			return err
		}
	}
	// dwNumItems {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.NumItems); err != nil {
			return err
		}
	}
	// phServer {in} (1:{pointer=ref}*(1))(2:{alias=OPCHANDLE, names=DWORD}[dim:0,size_is=dwNumItems](uint32))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Server", sizeInfo[0])
		}
		o.Server = make([]uint32, sizeInfo[0])
		for i1 := range o.Server {
			i1 := i1
			if err := w.ReadData(&o.Server[i1]); err != nil {
				return err
			}
		}
	}
	// ftTimeStamps {in} (1:{pointer=ref}*(1))(2:{alias=FILETIME}[dim:0,size_is=dwNumItems](struct))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Timestamps", sizeInfo[0])
		}
		o.Timestamps = make([]*dtyp.Filetime, sizeInfo[0])
		for i1 := range o.Timestamps {
			i1 := i1
			if o.Timestamps[i1] == nil {
				o.Timestamps[i1] = &dtyp.Filetime{}
			}
			if err := o.Timestamps[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
	}
	return nil
}

func (o *xxx_DeleteAtTimeOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_DeleteAtTimeOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		if o.Errors != nil || o.NumItems > 0 {
			_ptr_ppErrors := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				dimSize1 := uint64(o.NumItems)
				if err := w.WriteSize(dimSize1); err != nil {
					return err
				}
				sizeInfo := []uint64{
					dimSize1,
				}
				for i1 := range o.Errors {
					i1 := i1
					if uint64(i1) >= sizeInfo[0] {
						break
					}
					if err := w.WriteData(o.Errors[i1]); err != nil {
						return err
					}
				}
				for i1 := len(o.Errors); uint64(i1) < sizeInfo[0]; i1++ {
					if err := w.WriteData(int32(0)); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Errors, _ptr_ppErrors); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_DeleteAtTimeOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// pdwCancelID {out} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.CancelID); err != nil {
			return err
		}
	}
	// ppErrors {out} (1:{pointer=ref}*(2)*(1))(2:{alias=HRESULT, names=LONG}[dim:0,size_is=dwNumItems](int32))
	{
		_ptr_ppErrors := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			sizeInfo := []uint64{
				0,
			}
			for sz1 := range sizeInfo {
				if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
					return err
				}
			}
			if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
				return fmt.Errorf("buffer overflow for size %d of array o.Errors", sizeInfo[0])
			}
			o.Errors = make([]int32, sizeInfo[0])
			for i1 := range o.Errors {
				i1 := i1
				if err := w.ReadData(&o.Errors[i1]); err != nil {
					return err
				}
			}
			return nil
		})
		_s_ppErrors := func(ptr interface{}) { o.Errors = *ptr.(*[]int32) }
		if err := w.ReadPointer(&o.Errors, _s_ppErrors, _ptr_ppErrors); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// DeleteAtTimeRequest structure represents the DeleteAtTime operation request
type DeleteAtTimeRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This          *dcom.ORPCThis   `idl:"name:This" json:"this"`
	TransactionID uint32           `idl:"name:dwTransactionID" json:"transaction_id"`
	NumItems      uint32           `idl:"name:dwNumItems" json:"num_items"`
	Server        []uint32         `idl:"name:phServer;size_is:(dwNumItems)" json:"server"`
	Timestamps    []*dtyp.Filetime `idl:"name:ftTimeStamps;size_is:(dwNumItems)" json:"timestamps"`
}

func (o *DeleteAtTimeRequest) xxx_ToOp(ctx context.Context, op *xxx_DeleteAtTimeOperation) *xxx_DeleteAtTimeOperation {
	if op == nil {
		op = &xxx_DeleteAtTimeOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.TransactionID = o.TransactionID
	op.NumItems = o.NumItems
	op.Server = o.Server
	op.Timestamps = o.Timestamps
	return op
}

func (o *DeleteAtTimeRequest) xxx_FromOp(ctx context.Context, op *xxx_DeleteAtTimeOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.TransactionID = op.TransactionID
	o.NumItems = op.NumItems
	o.Server = op.Server
	o.Timestamps = op.Timestamps
}
func (o *DeleteAtTimeRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *DeleteAtTimeRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_DeleteAtTimeOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeDeleteAtTimeRequest build a response structure from the given request structure.
func (o *DeleteAtTimeRequest) MakeResponse() *DeleteAtTimeResponse {
	if o == nil {
		return &DeleteAtTimeResponse{}
	}
	return &DeleteAtTimeResponse{
		NumItems: o.NumItems,
	}
}

// OpNum returns the operation number of DeleteAtTime operation.
func (o *DeleteAtTimeRequest) OpNum() int { return 8 }

// OpName returns the operation name of DeleteAtTime operation.
func (o *DeleteAtTimeRequest) OpName() string { return "/IOPCHDA_AsyncUpdate/v0/DeleteAtTime" }

// DeleteAtTimeResponse structure represents the DeleteAtTime operation response
type DeleteAtTimeResponse struct {
	// XXX: dwNumItems is an implicit input depedency for output parameters
	NumItems uint32 `idl:"name:dwNumItems" json:"num_items"`

	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That     *dcom.ORPCThat `idl:"name:That" json:"that"`
	CancelID uint32         `idl:"name:pdwCancelID" json:"cancel_id"`
	Errors   []int32        `idl:"name:ppErrors;size_is:(, dwNumItems)" json:"errors"`
	// Return: The DeleteAtTime return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *DeleteAtTimeResponse) xxx_ToOp(ctx context.Context, op *xxx_DeleteAtTimeOperation) *xxx_DeleteAtTimeOperation {
	if op == nil {
		op = &xxx_DeleteAtTimeOperation{}
	}
	if o == nil {
		return op
	}
	// XXX: implicit input dependencies for output parameters
	if op.NumItems == uint32(0) {
		op.NumItems = o.NumItems
	}

	op.That = o.That
	op.CancelID = o.CancelID
	op.Errors = o.Errors
	op.Return = o.Return
	return op
}

func (o *DeleteAtTimeResponse) xxx_FromOp(ctx context.Context, op *xxx_DeleteAtTimeOperation) {
	if o == nil {
		return
	}
	// XXX: implicit input dependencies for output parameters
	o.NumItems = op.NumItems

	o.That = op.That
	o.CancelID = op.CancelID
	o.Errors = op.Errors
	o.Return = op.Return
}
func (o *DeleteAtTimeResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *DeleteAtTimeResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_DeleteAtTimeOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_CancelOperation structure represents the Cancel operation
type xxx_CancelOperation struct {
	This     *dcom.ORPCThis `idl:"name:This" json:"this"`
	That     *dcom.ORPCThat `idl:"name:That" json:"that"`
	CancelID uint32         `idl:"name:dwCancelID" json:"cancel_id"`
	Return   int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of Cancel operation.
func (o *xxx_CancelOperation) OpNum() int { return 9 }

// OpName returns the operation name of Cancel operation.
func (o *xxx_CancelOperation) OpName() string { return "/IOPCHDA_AsyncUpdate/v0/Cancel" }

func (o *xxx_CancelOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CancelOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dwCancelID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.CancelID); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CancelOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dwCancelID {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.CancelID); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CancelOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CancelOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_CancelOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// CancelRequest structure represents the Cancel operation request
type CancelRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This     *dcom.ORPCThis `idl:"name:This" json:"this"`
	CancelID uint32         `idl:"name:dwCancelID" json:"cancel_id"`
}

func (o *CancelRequest) xxx_ToOp(ctx context.Context, op *xxx_CancelOperation) *xxx_CancelOperation {
	if op == nil {
		op = &xxx_CancelOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.CancelID = o.CancelID
	return op
}

func (o *CancelRequest) xxx_FromOp(ctx context.Context, op *xxx_CancelOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.CancelID = op.CancelID
}
func (o *CancelRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *CancelRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_CancelOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeCancelRequest build a response structure from the given request structure.
func (o *CancelRequest) MakeResponse() *CancelResponse {
	return &CancelResponse{}
}

// OpNum returns the operation number of Cancel operation.
func (o *CancelRequest) OpNum() int { return 9 }

// OpName returns the operation name of Cancel operation.
func (o *CancelRequest) OpName() string { return "/IOPCHDA_AsyncUpdate/v0/Cancel" }

// CancelResponse structure represents the Cancel operation response
type CancelResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That *dcom.ORPCThat `idl:"name:That" json:"that"`
	// Return: The Cancel return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *CancelResponse) xxx_ToOp(ctx context.Context, op *xxx_CancelOperation) *xxx_CancelOperation {
	if op == nil {
		op = &xxx_CancelOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Return = o.Return
	return op
}

func (o *CancelResponse) xxx_FromOp(ctx context.Context, op *xxx_CancelOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Return = op.Return
}
func (o *CancelResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *CancelResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_CancelOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}
