// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopceventsink

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
	opcae "github.com/oiweiwei/go-opcda/opc/opcae"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom.GoPackage
	_ = iunknown.GoPackage
	_ = opcae.GoPackage
)

var (
	// import guard
	GoPackage = "opcae"
)

var (
	// IOPCEventSink interface identifier 6516885f-5783-11d1-84a0-00608cb8a7e9
	EventSinkIID = &dcom.IID{Data1: 0x6516885f, Data2: 0x5783, Data3: 0x11d1, Data4: []byte{0x84, 0xa0, 0x00, 0x60, 0x8c, 0xb8, 0xa7, 0xe9}}
	// Syntax UUID
	EventSinkSyntaxUUID = &uuid.UUID{TimeLow: 0x6516885f, TimeMid: 0x5783, TimeHiAndVersion: 0x11d1, ClockSeqHiAndReserved: 0x84, ClockSeqLow: 0xa0, Node: [6]uint8{0x0, 0x60, 0x8c, 0xb8, 0xa7, 0xe9}}
	// Syntax ID
	EventSinkSyntaxV0_0 = &dcerpc.SyntaxID{IfUUID: EventSinkSyntaxUUID, IfVersionMajor: 0, IfVersionMinor: 0}
)

// IOPCEventSink interface.
type EventSinkClient interface {

	// IUnknown retrieval method.
	Unknown() iunknown.UnknownClient

	// OnEvent operation.
	OnEvent(context.Context, *OnEventRequest, ...dcerpc.CallOption) (*OnEventResponse, error)

	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn

	// IPID sets the object interface identifier.
	IPID(context.Context, *dcom.IPID) EventSinkClient
}

type xxx_DefaultEventSinkClient struct {
	iunknown.UnknownClient
	cc   dcerpc.Conn
	ipid *dcom.IPID
}

func (o *xxx_DefaultEventSinkClient) Unknown() iunknown.UnknownClient {
	return o.UnknownClient
}

func (o *xxx_DefaultEventSinkClient) OnEvent(ctx context.Context, in *OnEventRequest, opts ...dcerpc.CallOption) (*OnEventResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &OnEventResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultEventSinkClient) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultEventSinkClient) Conn() dcerpc.Conn {
	return o.cc
}

func (o *xxx_DefaultEventSinkClient) IPID(ctx context.Context, ipid *dcom.IPID) EventSinkClient {
	if ipid == nil {
		ipid = &dcom.IPID{}
	}
	return &xxx_DefaultEventSinkClient{
		UnknownClient: o.UnknownClient.IPID(ctx, ipid),
		cc:            o.cc,
		ipid:          ipid,
	}
}

func NewEventSinkClient(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (EventSinkClient, error) {
	var err error
	if !dcom.IsSuperclass(opts) {
		cc, err = cc.Bind(ctx, append(opts, dcerpc.WithAbstractSyntax(EventSinkSyntaxV0_0))...)
		if err != nil {
			return nil, err
		}
	}
	base, err := iunknown.NewUnknownClient(ctx, cc, append(opts, dcom.Superclass(cc))...)
	if err != nil {
		return nil, err
	}
	ipid, ok := dcom.HasIPID(opts)
	if ok {
		base = base.IPID(ctx, ipid)
	}
	return &xxx_DefaultEventSinkClient{
		UnknownClient: base,
		cc:            cc,
		ipid:          ipid,
	}, nil
}

// xxx_OnEventOperation structure represents the OnEvent operation
type xxx_OnEventOperation struct {
	This               *dcom.ORPCThis   `idl:"name:This" json:"this"`
	That               *dcom.ORPCThat   `idl:"name:That" json:"that"`
	ClientSubscription uint32           `idl:"name:hClientSubscription" json:"client_subscription"`
	Refresh            bool             `idl:"name:bRefresh" json:"refresh"`
	LastRefresh        bool             `idl:"name:bLastRefresh" json:"last_refresh"`
	Count              uint32           `idl:"name:dwCount" json:"count"`
	Events             []*opcae.OnEvent `idl:"name:pEvents;size_is:(dwCount)" json:"events"`
	Return             int32            `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of OnEvent operation.
func (o *xxx_OnEventOperation) OpNum() int { return 3 }

// OpName returns the operation name of OnEvent operation.
func (o *xxx_OnEventOperation) OpName() string { return "/IOPCEventSink/v0/OnEvent" }

func (o *xxx_OnEventOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if o.Events != nil && o.Count == 0 {
		o.Count = uint32(len(o.Events))
	}
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_OnEventOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// hClientSubscription {in} (1:{alias=OPCHANDLE, names=DWORD}(uint32))
	{
		if err := w.WriteData(o.ClientSubscription); err != nil {
			return err
		}
	}
	// bRefresh {in} (1:{alias=BOOL}(int32))
	{
		if !o.Refresh {
			if err := w.WriteData(int32(0)); err != nil {
				return err
			}
		} else {
			if err := w.WriteData(int32(1)); err != nil {
				return err
			}
		}
	}
	// bLastRefresh {in} (1:{alias=BOOL}(int32))
	{
		if !o.LastRefresh {
			if err := w.WriteData(int32(0)); err != nil {
				return err
			}
		} else {
			if err := w.WriteData(int32(1)); err != nil {
				return err
			}
		}
	}
	// dwCount {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.Count); err != nil {
			return err
		}
	}
	// pEvents {in} (1:{pointer=ref}*(1))(2:{alias=ONEVENTSTRUCT}[dim:0,size_is=dwCount](struct))
	{
		dimSize1 := uint64(o.Count)
		if err := w.WriteSize(dimSize1); err != nil {
			return err
		}
		sizeInfo := []uint64{
			dimSize1,
		}
		for i1 := range o.Events {
			i1 := i1
			if uint64(i1) >= sizeInfo[0] {
				break
			}
			if o.Events[i1] != nil {
				if err := o.Events[i1].MarshalNDR(ctx, w); err != nil {
					return err
				}
			} else {
				if err := (&opcae.OnEvent{}).MarshalNDR(ctx, w); err != nil {
					return err
				}
			}
		}
		for i1 := len(o.Events); uint64(i1) < sizeInfo[0]; i1++ {
			if err := (&opcae.OnEvent{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_OnEventOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// hClientSubscription {in} (1:{alias=OPCHANDLE, names=DWORD}(uint32))
	{
		if err := w.ReadData(&o.ClientSubscription); err != nil {
			return err
		}
	}
	// bRefresh {in} (1:{alias=BOOL}(int32))
	{
		var _bRefresh int32
		if err := w.ReadData(&_bRefresh); err != nil {
			return err
		}
		o.Refresh = _bRefresh != 0
	}
	// bLastRefresh {in} (1:{alias=BOOL}(int32))
	{
		var _bLastRefresh int32
		if err := w.ReadData(&_bLastRefresh); err != nil {
			return err
		}
		o.LastRefresh = _bLastRefresh != 0
	}
	// dwCount {in} (1:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.Count); err != nil {
			return err
		}
	}
	// pEvents {in} (1:{pointer=ref}*(1))(2:{alias=ONEVENTSTRUCT}[dim:0,size_is=dwCount](struct))
	{
		sizeInfo := []uint64{
			0,
		}
		for sz1 := range sizeInfo {
			if err := w.ReadSize(&sizeInfo[sz1]); err != nil {
				return err
			}
		}
		if sizeInfo[0] > uint64(w.Len()) /* sanity-check */ {
			return fmt.Errorf("buffer overflow for size %d of array o.Events", sizeInfo[0])
		}
		o.Events = make([]*opcae.OnEvent, sizeInfo[0])
		for i1 := range o.Events {
			i1 := i1
			if o.Events[i1] == nil {
				o.Events[i1] = &opcae.OnEvent{}
			}
			if err := o.Events[i1].UnmarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_OnEventOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_OnEventOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_OnEventOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// OnEventRequest structure represents the OnEvent operation request
type OnEventRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This               *dcom.ORPCThis   `idl:"name:This" json:"this"`
	ClientSubscription uint32           `idl:"name:hClientSubscription" json:"client_subscription"`
	Refresh            bool             `idl:"name:bRefresh" json:"refresh"`
	LastRefresh        bool             `idl:"name:bLastRefresh" json:"last_refresh"`
	Count              uint32           `idl:"name:dwCount" json:"count"`
	Events             []*opcae.OnEvent `idl:"name:pEvents;size_is:(dwCount)" json:"events"`
}

func (o *OnEventRequest) xxx_ToOp(ctx context.Context, op *xxx_OnEventOperation) *xxx_OnEventOperation {
	if op == nil {
		op = &xxx_OnEventOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.ClientSubscription = o.ClientSubscription
	op.Refresh = o.Refresh
	op.LastRefresh = o.LastRefresh
	op.Count = o.Count
	op.Events = o.Events
	return op
}

func (o *OnEventRequest) xxx_FromOp(ctx context.Context, op *xxx_OnEventOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.ClientSubscription = op.ClientSubscription
	o.Refresh = op.Refresh
	o.LastRefresh = op.LastRefresh
	o.Count = op.Count
	o.Events = op.Events
}
func (o *OnEventRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *OnEventRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_OnEventOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeOnEventRequest build a response structure from the given request structure.
func (o *OnEventRequest) MakeResponse() *OnEventResponse {
	return &OnEventResponse{}
}

// OpNum returns the operation number of OnEvent operation.
func (o *OnEventRequest) OpNum() int { return 3 }

// OpName returns the operation name of OnEvent operation.
func (o *OnEventRequest) OpName() string { return "/IOPCEventSink/v0/OnEvent" }

// OnEventResponse structure represents the OnEvent operation response
type OnEventResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That *dcom.ORPCThat `idl:"name:That" json:"that"`
	// Return: The OnEvent return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *OnEventResponse) xxx_ToOp(ctx context.Context, op *xxx_OnEventOperation) *xxx_OnEventOperation {
	if op == nil {
		op = &xxx_OnEventOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Return = o.Return
	return op
}

func (o *OnEventResponse) xxx_FromOp(ctx context.Context, op *xxx_OnEventOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Return = op.Return
}
func (o *OnEventResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *OnEventResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_OnEventOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}
