// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopcpublicgroupstatemgt

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = iunknown.GoPackage
)

// IOPCPublicGroupStateMgt server interface.
type PublicGroupStateManagementServer interface {

	// IUnknown base class.
	iunknown.UnknownServer

	// GetState operation.
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)

	// MoveToPublic operation.
	MoveToPublic(context.Context, *MoveToPublicRequest) (*MoveToPublicResponse, error)
}

func RegisterPublicGroupStateManagementServer(conn dcerpc.Conn, o PublicGroupStateManagementServer, opts ...dcerpc.Option) {
	conn.RegisterServer(NewPublicGroupStateManagementServerHandle(o), append(opts, dcerpc.WithAbstractSyntax(PublicGroupStateManagementSyntaxV0_0))...)
}

func NewPublicGroupStateManagementServerHandle(o PublicGroupStateManagementServer) dcerpc.ServerHandle {
	return func(ctx context.Context, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
		return PublicGroupStateManagementServerHandle(ctx, o, opNum, r)
	}
}

func PublicGroupStateManagementServerHandle(ctx context.Context, o PublicGroupStateManagementServer, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
	if opNum < 3 {
		// IUnknown base method.
		return iunknown.UnknownServerHandle(ctx, o, opNum, r)
	}
	switch opNum {
	case 3: // GetState
		op := &xxx_GetStateOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &GetStateRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.GetState(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 4: // MoveToPublic
		op := &xxx_MoveToPublicOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &MoveToPublicRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.MoveToPublic(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	}
	return nil, nil
}

// Unimplemented IOPCPublicGroupStateMgt
type UnimplementedPublicGroupStateManagementServer struct {
	iunknown.UnimplementedUnknownServer
}

func (UnimplementedPublicGroupStateManagementServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedPublicGroupStateManagementServer) MoveToPublic(context.Context, *MoveToPublicRequest) (*MoveToPublicResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}

var _ PublicGroupStateManagementServer = (*UnimplementedPublicGroupStateManagementServer)(nil)
