// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package iopceventsubscriptionmgt2

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
	iopceventsubscriptionmgt "github.com/oiweiwei/go-opcda/opc/opcae/iopceventsubscriptionmgt/v0"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = iopceventsubscriptionmgt.GoPackage
)

// IOPCEventSubscriptionMgt2 server interface.
type EventSubscriptionManagement2Server interface {

	// IOPCEventSubscriptionMgt base class.
	iopceventsubscriptionmgt.EventSubscriptionManagementServer

	// SetKeepAlive operation.
	SetKeepAlive(context.Context, *SetKeepAliveRequest) (*SetKeepAliveResponse, error)

	// GetKeepAlive operation.
	GetKeepAlive(context.Context, *GetKeepAliveRequest) (*GetKeepAliveResponse, error)
}

func RegisterEventSubscriptionManagement2Server(conn dcerpc.Conn, o EventSubscriptionManagement2Server, opts ...dcerpc.Option) {
	conn.RegisterServer(NewEventSubscriptionManagement2ServerHandle(o), append(opts, dcerpc.WithAbstractSyntax(EventSubscriptionManagement2SyntaxV0_0))...)
}

func NewEventSubscriptionManagement2ServerHandle(o EventSubscriptionManagement2Server) dcerpc.ServerHandle {
	return func(ctx context.Context, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
		return EventSubscriptionManagement2ServerHandle(ctx, o, opNum, r)
	}
}

func EventSubscriptionManagement2ServerHandle(ctx context.Context, o EventSubscriptionManagement2Server, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
	if opNum < 11 {
		// IOPCEventSubscriptionMgt base method.
		return iopceventsubscriptionmgt.EventSubscriptionManagementServerHandle(ctx, o, opNum, r)
	}
	switch opNum {
	case 11: // SetKeepAlive
		op := &xxx_SetKeepAliveOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &SetKeepAliveRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.SetKeepAlive(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 12: // GetKeepAlive
		op := &xxx_GetKeepAliveOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &GetKeepAliveRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.GetKeepAlive(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	}
	return nil, nil
}

// Unimplemented IOPCEventSubscriptionMgt2
type UnimplementedEventSubscriptionManagement2Server struct {
	iopceventsubscriptionmgt.UnimplementedEventSubscriptionManagementServer
}

func (UnimplementedEventSubscriptionManagement2Server) SetKeepAlive(context.Context, *SetKeepAliveRequest) (*SetKeepAliveResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedEventSubscriptionManagement2Server) GetKeepAlive(context.Context, *GetKeepAliveRequest) (*GetKeepAliveResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}

var _ EventSubscriptionManagement2Server = (*UnimplementedEventSubscriptionManagement2Server)(nil)
