// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package icatinformation

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = iunknown.GoPackage
)

// ICatInformation server interface.
type ICategoryInformationServer interface {

	// IUnknown base class.
	iunknown.UnknownServer

	// EnumCategories operation.
	EnumCategories(context.Context, *EnumCategoriesRequest) (*EnumCategoriesResponse, error)

	// GetCategoryDesc operation.
	GetCategoryDescription(context.Context, *GetCategoryDescriptionRequest) (*GetCategoryDescriptionResponse, error)

	// EnumClassesOfCategories operation.
	EnumClassesOfCategories(context.Context, *EnumClassesOfCategoriesRequest) (*EnumClassesOfCategoriesResponse, error)

	// RemoteEnumClassesOfCategories operation.
	RemoteEnumClassesOfCategories(context.Context, *RemoteEnumClassesOfCategoriesRequest) (*RemoteEnumClassesOfCategoriesResponse, error)

	// IsClassOfCategories operation.
	IsClassOfCategories(context.Context, *IsClassOfCategoriesRequest) (*IsClassOfCategoriesResponse, error)

	// RemoteIsClassOfCategories operation.
	RemoteIsClassOfCategories(context.Context, *RemoteIsClassOfCategoriesRequest) (*RemoteIsClassOfCategoriesResponse, error)

	// EnumImplCategoriesOfClass operation.
	EnumImplementedCategoriesOfClass(context.Context, *EnumImplementedCategoriesOfClassRequest) (*EnumImplementedCategoriesOfClassResponse, error)

	// EnumReqCategoriesOfClass operation.
	EnumRequiredCategoriesOfClass(context.Context, *EnumRequiredCategoriesOfClassRequest) (*EnumRequiredCategoriesOfClassResponse, error)
}

func RegisterICategoryInformationServer(conn dcerpc.Conn, o ICategoryInformationServer, opts ...dcerpc.Option) {
	conn.RegisterServer(NewICategoryInformationServerHandle(o), append(opts, dcerpc.WithAbstractSyntax(ICategoryInformationSyntaxV0_0))...)
}

func NewICategoryInformationServerHandle(o ICategoryInformationServer) dcerpc.ServerHandle {
	return func(ctx context.Context, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
		return ICategoryInformationServerHandle(ctx, o, opNum, r)
	}
}

func ICategoryInformationServerHandle(ctx context.Context, o ICategoryInformationServer, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
	if opNum < 3 {
		// IUnknown base method.
		return iunknown.UnknownServerHandle(ctx, o, opNum, r)
	}
	switch opNum {
	case 3: // EnumCategories
		op := &xxx_EnumCategoriesOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &EnumCategoriesRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.EnumCategories(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 4: // GetCategoryDesc
		op := &xxx_GetCategoryDescriptionOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &GetCategoryDescriptionRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.GetCategoryDescription(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 5: // EnumClassesOfCategories
		op := &xxx_EnumClassesOfCategoriesOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &EnumClassesOfCategoriesRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.EnumClassesOfCategories(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 6: // RemoteEnumClassesOfCategories
		op := &xxx_RemoteEnumClassesOfCategoriesOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &RemoteEnumClassesOfCategoriesRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.RemoteEnumClassesOfCategories(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 7: // IsClassOfCategories
		op := &xxx_IsClassOfCategoriesOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &IsClassOfCategoriesRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.IsClassOfCategories(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 8: // RemoteIsClassOfCategories
		op := &xxx_RemoteIsClassOfCategoriesOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &RemoteIsClassOfCategoriesRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.RemoteIsClassOfCategories(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 9: // EnumImplCategoriesOfClass
		op := &xxx_EnumImplementedCategoriesOfClassOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &EnumImplementedCategoriesOfClassRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.EnumImplementedCategoriesOfClass(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 10: // EnumReqCategoriesOfClass
		op := &xxx_EnumRequiredCategoriesOfClassOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &EnumRequiredCategoriesOfClassRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.EnumRequiredCategoriesOfClass(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	}
	return nil, nil
}

// Unimplemented ICatInformation
type UnimplementedICategoryInformationServer struct {
	iunknown.UnimplementedUnknownServer
}

func (UnimplementedICategoryInformationServer) EnumCategories(context.Context, *EnumCategoriesRequest) (*EnumCategoriesResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedICategoryInformationServer) GetCategoryDescription(context.Context, *GetCategoryDescriptionRequest) (*GetCategoryDescriptionResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedICategoryInformationServer) EnumClassesOfCategories(context.Context, *EnumClassesOfCategoriesRequest) (*EnumClassesOfCategoriesResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedICategoryInformationServer) RemoteEnumClassesOfCategories(context.Context, *RemoteEnumClassesOfCategoriesRequest) (*RemoteEnumClassesOfCategoriesResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedICategoryInformationServer) IsClassOfCategories(context.Context, *IsClassOfCategoriesRequest) (*IsClassOfCategoriesResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedICategoryInformationServer) RemoteIsClassOfCategories(context.Context, *RemoteIsClassOfCategoriesRequest) (*RemoteIsClassOfCategoriesResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedICategoryInformationServer) EnumImplementedCategoriesOfClass(context.Context, *EnumImplementedCategoriesOfClassRequest) (*EnumImplementedCategoriesOfClassResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedICategoryInformationServer) EnumRequiredCategoriesOfClass(context.Context, *EnumRequiredCategoriesOfClassRequest) (*EnumRequiredCategoriesOfClassResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}

var _ ICategoryInformationServer = (*UnimplementedICategoryInformationServer)(nil)
